import { useState } from 'preact/hooks';
import type { EconomicCatalog } from './economics';
import { economicState } from './economics';
import type { Indicators, InstrumentId, Interval, JournalEntry, MarketDataset, SkyEvent, WatchRule } from './types';
import { eventDay, formatEventDate, formatEventTime } from './events';
import { estimateRisk } from './risk';

interface Props { instrument: InstrumentId; interval: Interval; timeZone: string; data: MarketDataset | null; marketError: string; indicators: Indicators; events: SkyEvent[]; economics: EconomicCatalog | null; rules: WatchRule[]; entries: JournalEntry[]; onSetup: () => void; onJournal: () => void; onSelect: (event: SkyEvent) => void }
export default function BriefPanel({ instrument, interval, timeZone, data, marketError, indicators, events, economics, rules, entries, onSetup, onJournal, onSelect }: Props) {
  const [setupId, setSetupId] = useState(''); const [checked, setChecked] = useState<string[]>([]);
  const now = Date.now(); const day = eventDay(now, timeZone);
  const last = data?.candles.filter(c => c.complete).at(-1);
  const setups = entries.filter(entry => entry.instrument === instrument && entry.setup).slice().sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  const setup = setups.find(entry => entry.id === setupId) ?? setups[0];
  const previous = entries.filter(entry => entry.instrument === instrument && eventDay(entry.createdAt, timeZone) < day).slice().sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0];
  const activeRules = rules.filter(rule => rule.enabled && rule.instrument === instrument && rule.interval === interval);
  const upcoming = events.filter(event => Date.parse(event.at) >= now && Date.parse(event.at) < now + 7 * 86400000).slice(0, 12);
  const checklist = ['Verify price and schedule freshness', 'Confirm the technical setup on finalized candles', 'Check confirmation and invalidation', 'Review spot size, fees and slippage', 'Review scheduled releases and overlapping windows', 'Record the plan before the outcome'];
  const latestValue = (points: Indicators['sma20']) => last ? points.find(point => point.time === last.time)?.value.toFixed(2) ?? 'Unavailable at latest finalized bar' : 'Unavailable';
  const risk = setup?.setup ? estimateRisk(setup.setup.risk) : null;
  return <section class="lens-panel" data-testid="lens-brief"><h2>Session preparation</h2><p>{instrument} · {interval} · {day} ({timeZone})</p><p class="lens-muted">Crypto trades continuously. This is your chosen preparation session; there is no universal market open or close. Rules are monitored while this page is open. No background notifications are implied.</p>
    <h3>Finalized market observation</h3>{last ? <><p>Close {last.close.toLocaleString('en-US')} {data!.instrument.quote} · bar begins {formatEventDate(last.time * 1000, timeZone)} {formatEventTime(last.time * 1000, timeZone)} · finalized. Dataset fetched {data!.fetchedAt}{(data!.stale || marketError) && ' · stale / refresh unavailable'}.</p><div class="lens-metrics">{[['SMA 20', indicators.sma20], ['SMA 50', indicators.sma50], ['EMA 20', indicators.ema20], ['RSI 14', indicators.rsi14]].map(([label, points]) => <div><span>{label as string}</span><strong>{latestValue(points as Indicators['sma20'])}</strong></div>)}</div></> : <p class="lens-notice">Finalized market data unavailable. Price and indicator observations are withheld.</p>}
    <h3>Selected upcoming context · next 7 days</h3><p class="lens-muted">Uses your current layer and body filters. Economic coverage: {economics ? economicState(economics, day) : 'unavailable'}.</p><div class="lens-list">{upcoming.map(event => <button class="lens-event-row" onClick={() => onSelect(event)}><span>{formatEventDate(event.at, timeZone)}<br />{formatEventTime(event.at, timeZone)}</span><strong>{event.title}</strong><span class="lens-tag">{event.economic ? 'economic' : event.personal ? 'personal' : 'shared sky'}</span></button>)}{!upcoming.length && <p class="lens-muted">No loaded qualifying events; this is not an all-clear signal.</p>}</div>
    <h3>Active watch rules ({activeRules.length})</h3><p class="lens-muted">Watch rules use shared sky events. Personal and economic timing appears in preparation context.</p>{activeRules.map(rule => <p>{rule.condition} {rule.threshold ?? ''} · {rule.family} · ±{rule.windowHours} h · version {rule.version}</p>)}{!activeRules.length && <p class="lens-muted">No active rules for this asset and timeframe.</p>}
    <h3>Saved setup and risk</h3>{setups.length > 0 && <label class="lens-field">Review saved setup<select value={setup?.id} onChange={event => setSetupId(event.currentTarget.value)}>{setups.map(entry => <option value={entry.id}>{entry.setup!.technicalSetup.slice(0, 70)}</option>)}</select></label>}
    {setup?.setup && risk ? <><p>{setup.setup.technicalSetup}<br />Confirmation: {setup.setup.confirmation}<br />Invalidation: {setup.setup.invalidation}<br />{setup.setup.interval} · {setup.horizonHours} h horizon · entry {setup.setup.risk.entry} · stop {setup.setup.risk.stop} {risk.currency}</p><p>{risk.units.toFixed(8)} units · {risk.notional.toFixed(2)} {risk.currency} notional · {risk.stopLoss.toFixed(2)} {risk.currency} estimated stop loss incl. costs · {risk.rewardRisk === null ? 'no target' : `${risk.rewardRisk.toFixed(2)} reward : risk`}</p>{setup.setup.window && <p>Associated {setup.setup.window.kind} window: {setup.setup.window.from} to {setup.setup.window.to}.</p>}</> : <p class="lens-muted">No saved setup. Prepare your confirmation, invalidation and risk.</p>}
    <h3>Pre-session checklist</h3><fieldset class="lens-form"><legend>Checks for this open-page session</legend>{checklist.map(item => <label class="lens-inline"><input type="checkbox" checked={checked.includes(item)} onChange={() => setChecked(current => current.includes(item) ? current.filter(value => value !== item) : [...current, item])} />{item}</label>)}</fieldset>
    <h3>Previous recorded session</h3>{previous ? <><p>{formatEventDate(previous.createdAt, timeZone)} · {previous.method}<br />Plan: {previous.plan}<br />User-entered review: {previous.outcome || 'not recorded'}</p><p class="lens-muted">This is your latest earlier journal entry, not a calculated or verified trade result. Self-selected notes cannot establish incremental predictive benefit.</p></> : <p class="lens-muted">No earlier journal entry for this asset.</p>}
    <div class="lens-inline"><button class="lens-button" onClick={onSetup}>Prepare setup &amp; risk</button><button class="lens-button" onClick={onJournal}>Record session in journal</button></div>
  </section>;
}
