import { useMemo, useState } from 'preact/hooks';
import { analyzeOccurrences, matchingEvents, matchedNonEventObservations } from './history';
import { formatEventDate, formatEventTime } from './events';
import type { MarketDataset, SkyEvent } from './types';

interface Props { eventCoverage: { start: number; end: number }; data: MarketDataset | null; events: SkyEvent[]; selectedEvent: SkyEvent | null; timeZone: string; onSelect: (event: SkyEvent) => void; onExpand: () => void; loading: boolean }
const number = (value: number | null) => value === null ? '—' : `${value > 0 ? '+' : ''}${value.toFixed(2)}%`;

export default function HistoryPanel({ eventCoverage, data, events, selectedEvent, timeZone, onSelect, onExpand, loading }: Props) {
  const [horizon, setHorizon] = useState(24);
  const summary = useMemo(() => data && selectedEvent && !selectedEvent.economic ? analyzeOccurrences(matchingEvents(selectedEvent, events), data.candles, {
    sessions: data.sessions, interval: data.interval, horizonHours: horizon, beforeHours: horizon, contextEvents: events,
  }) : null, [data, events, selectedEvent, horizon]);
  const controls = useMemo(() => summary && data && !data.sessions ? matchedNonEventObservations(summary, data.candles, { sessions: data.sessions, interval: data.interval, horizonHours: horizon, beforeHours: horizon, contextEvents: events, controlCoverage: eventCoverage }) : null, [summary, data, horizon, events, eventCoverage]);
  return <section class="lens-panel" aria-labelledby="lens-history-title">
    <div class="lens-section-head"><div><h2 id="lens-history-title">Previous occurrences</h2><p class="lens-muted">Inspect the same event family, bodies and aspect. Every qualifying occurrence in the loaded catalog is shown.</p></div>
      <button class="lens-button" onClick={onExpand} disabled={loading}>Load 900 daily candles</button></div>
    {!selectedEvent ? <p class="lens-muted">Select a sky event to inspect its previous occurrences.</p> : selectedEvent.economic ? <p class="lens-muted">Economic schedules provide preparation context. Historical release-response comparisons are not available; select a sky event to inspect its observations.</p> : <>
      <div class="lens-inline"><strong>{selectedEvent.title}</strong><label class="lens-field">Before &amp; after window<select value={horizon} onChange={(e) => setHorizon(Number(e.currentTarget.value))}><option value={24}>{data?.sessions ? '1 session' : '24 hours'}</option><option value={72}>{data?.sessions ? '3 sessions' : '3 days'}</option><option value={168}>{data?.sessions ? '7 sessions' : '7 days'}</option></select></label></div>
      {summary && <>
        <div class="lens-metrics"><div><span>Completed windows</span><strong>{summary.complete} / {summary.total}</strong></div><div><span>Median return after</span><strong>{number(summary.medianReturnPct)}</strong></div><div><span>Mean return after</span><strong>{number(summary.meanReturnPct)}</strong></div><div><span>Pending / incomplete</span><strong>{summary.pending} / {summary.incomplete}</strong></div></div>
        <p class="lens-muted">{summary.convention} These are descriptive observations, with no entry rule or transaction costs. Overlapping and linked events are flagged; {summary.independent} completed windows are isolated from the other loaded events.</p>
        {data?.sessions && <p class="lens-muted">UTC weekday matched controls are unavailable for exchange sessions. Session outcomes remain descriptive and do not establish predictive benefit.</p>}
        {controls && <details class="lens-method"><summary>Matched non-event comparison · {controls.matchedEvents} matched / {controls.unmatchedEvents} unmatched completed events</summary><p>{controls.convention}</p><div class="lens-table-scroll"><table><caption>Descriptive comparison, identical window lengths; no strategy or efficacy claim</caption><thead><tr><th>Metric</th><th>Event windows</th><th>Matched non-event windows</th></tr></thead><tbody><tr><th>Completed n</th><td>{controls.pairedEvents.length}</td><td>{controls.observations.length} ({controls.uniqueControls} unique)</td></tr><tr><th>Mean return</th><td>{number(controls.eventMeanReturnPct)}</td><td>{number(controls.meanReturnPct)}</td></tr><tr><th>Mean range</th><td>{number(controls.eventMeanRangePct)}</td><td>{number(controls.meanRangePct)}</td></tr><tr><th>Mean realized volatility</th><td>{number(controls.eventMeanVolatilityPct)}</td><td>{number(controls.meanVolatilityPct)}</td></tr><tr><th>Reversal fraction</th><td>{number(controls.eventReversalFraction === null ? null : controls.eventReversalFraction * 100)}</td><td>{number(controls.reversalFraction === null ? null : controls.reversalFraction * 100)}</td></tr></tbody></table></div><p>Paired event return distribution (%): {controls.pairedEvents.map(row => row.returnPct!).map(value => value.toFixed(3)).join(', ') || 'unavailable'}</p><p>Control return distribution (%): {controls.returnDistribution.map(value => value.toFixed(3)).join(', ') || 'unavailable'}</p><div class="lens-table-scroll"><table><caption>Every selected non-event observation</caption><thead><tr><th>UTC anchor</th><th>Return</th><th>Range</th><th>Volatility</th></tr></thead><tbody>{controls.observations.map(row => <tr><th>{new Date(row.anchor * 1000).toISOString()}</th><td>{number(row.returnPct)}</td><td>{number(row.rangePct)}</td><td>{number(row.volatilityPct)}</td></tr>)}</tbody></table></div></details>}
        {summary.complete < 10 && <p class="lens-notice">Few completed occurrences are available. This sample cannot establish a reliable predictive effect.</p>}
        <div class="lens-table-scroll"><table><caption>Occurrence outcomes · {data?.instrument.id} · {data?.interval} · {data?.attribution ?? data?.instrument.venue}</caption><thead><tr><th>Date</th><th>Time ({timeZone})</th><th>Before</th><th>After</th><th>Range after</th><th>Volatility</th><th>Reversal</th><th>Coverage</th></tr></thead>
          <tbody>{summary.occurrences.map((row) => <tr key={row.event.id}><th scope="row"><button class="lens-text-button" onClick={() => onSelect(row.event)}>{formatEventDate(row.event, timeZone)}</button></th><td>{formatEventTime(row.event, timeZone)}</td><td>{number(row.beforeReturnPct)}</td><td>{number(row.returnPct)}</td><td>{number(row.rangePct)}</td><td>{number(row.volatilityPct)}</td><td>{row.reversal === null ? 'unavailable / flat' : row.reversal ? 'yes' : 'no'}</td><td>{row.status}{row.overlappingIds.length > 0 && ' · overlapping'}{row.linkedIds.length > 0 && ' · linked'}{row.reason && <small>{row.reason}</small>}</td></tr>)}</tbody></table></div>
      </>}
    </>}
    <details class="lens-method"><summary>Forecasting experiment</summary><p>A fixed lunar-feature experiment found no consistent added predictive benefit. The separate research report compares technical-only, lunar-only and combined models on chronological holdout data, with source receipts, calibration and uncertainty. Public model forecasts remain disabled.</p><a href="/terminal/desk/research/">Read the experiment results →</a><p>The separate frozen paper study compares identical SMA rules with and without its predeclared lunar filter, including fixed costs, all eligible decisions, missing days, return, drawdown, exposure and trade count. New personal-calendar hypotheses need a new frozen protocol and fresh evaluation period; the consumed 2023 holdout cannot be reused for tuning.</p><a href="/terminal/desk/research/#prospective-paper">Paper-study protocol and coverage →</a></details>
  </section>;
}
