import { OUTLOOK_MODEL, outlookLabel, type OutlookDay } from './outlook';
export default function OutlookPanel({ days, selectedDate, reliable }: { days: OutlookDay[]; selectedDate: string; reliable: boolean }) {
  const selected = days.find(day => day.date === selectedDate);
  const month = days.filter(day => day.date.startsWith(selectedDate.slice(0, 7)));
  const weekEnd = new Date(Date.parse(`${selectedDate}T12:00:00Z`) + 7 * 86400000).toISOString().slice(0, 10);
  const week = days.filter(day => day.date >= selectedDate && day.date < weekEnd);
  const summary = (period: OutlookDay[]) => period.length ? `Mean ${(period.reduce((sum, day) => sum + day.score, 0) / period.length).toFixed(1)}; highest ${[...period].sort((a, b) => b.score - a.score || a.date.localeCompare(b.date))[0].date}; lowest ${[...period].sort((a, b) => a.score - b.score || a.date.localeCompare(b.date))[0].date}.` : 'Outside calculated coverage.';
  return <section class="lens-panel" data-testid="lens-outlook"><h3>Interpretive astrology outlook · optional</h3><p class="lens-muted">This 0–100 interpretive astrology score is a traditional reflection aid. It measures no probability, expected return or trading opportunity. Sampling: {OUTLOOK_MODEL.sample}. {reliable ? 'Reliable natal angles and house context included.' : 'Natal Moon, angles and houses omitted because birth time is unknown or uncertain.'}</p><p>Month: {summary(month)}<br />7 days from {selectedDate}: {summary(week)}</p>
    {selected && <><p class={`lens-outlook--${outlookLabel(selected.score)}`}><strong>{selectedDate} · {selected.score} / 100 · {outlookLabel(selected.score)} astrology</strong></p><details><summary>Every score contribution ({selected.contributions.length})</summary><div class="lens-table-scroll"><table><thead><tr><th>Transit / natal target</th><th>Deviation</th><th>House</th><th>Weight</th><th>Contribution</th></tr></thead><tbody>{selected.contributions.map(row => <tr><th>{row.id.replaceAll(':', ' · ')}</th><td>{row.separation.toFixed(3)}°</td><td>{row.house ?? 'unknown'}</td><td>{row.weight}</td><td>{row.contribution.toFixed(3)}</td></tr>)}</tbody></table></div></details></>}
    <details class="lens-method"><summary>Version, weights and fixed thresholds</summary><p>{OUTLOOK_MODEL.version}. Base 50; conjunction 0 (neutral by convention), sextile +1, trine +2, square −2, opposition −2. Body weights: Moon 0.5; Jupiter / Saturn 1.5; other supported bodies 1. Natal house 2 / 5 / 8 multiplies weight by 1.25 when houses are reliable. Each contribution = weight × (1 − deviation / selected orb). Sum with base, clamp to [0,100], round to one decimal. Supportive ≥70; challenging ≤30; mixed otherwise. These arbitrary traditional weights were not optimized against market outcomes. Every view uses the same daily value; no period-relative normalization.</p></details>
  </section>;
}
