import { INSTRUMENTS } from './catalog';
import { useEffect, useState } from 'preact/hooks';
import type { InstrumentId, Interval, JournalEntry, SetupPlan, SkyEvent } from './types';
import { estimateRisk, type RiskEstimate } from './risk';
import { formatEventDate } from './events';

interface Props { instrument: InstrumentId; interval: Interval; selectedEvent: SkyEvent | null; entries: JournalEntry[]; storageError: string | null; onSave: (input: { id?: string; baseUpdatedAt?: string; hypothesis: string; plan: string; setup: SetupPlan; horizonHours: number; method: JournalEntry['method']; eventIds: string[] }) => Promise<void>; onJournal: () => void }

export default function SetupPanel({ instrument, interval, selectedEvent, entries, storageError, onSave, onJournal }: Props) {
  const currency = INSTRUMENTS[instrument].quote;
  const dollars = (value: number) => `${value.toLocaleString('en-US', { maximumFractionDigits: 2 })} ${currency}`;
  const [baseUpdatedAt, setBaseUpdatedAt] = useState<string | undefined>();
  const [editingId, setEditingId] = useState<string | undefined>();
  const [technical, setTechnical] = useState(''); const [confirmation, setConfirmation] = useState(''); const [invalidation, setInvalidation] = useState(''); const [hypothesis, setHypothesis] = useState('');
  const [fields, setFields] = useState({ equity: '10000', riskValue: '1', entry: '', stop: '', target: '', feeBps: '10', slippageBps: '5' });
  const [mode, setMode] = useState<'percent' | 'usd' | 'quote'>('percent'); const [timeframe, setTimeframe] = useState<Interval>(interval); const [horizon, setHorizon] = useState('24');
  const [window, setWindow] = useState<SetupPlan['window']>(); const [attach, setAttach] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const [method, setMethod] = useState<JournalEntry['method']>('TA + astrology');
  const risk: SetupPlan['risk'] = { instrumentId: instrument, currency, funding: 'cash', equity: Number(fields.equity), riskMode: mode, riskValue: Number(fields.riskValue), entry: Number(fields.entry), stop: Number(fields.stop), ...(fields.target ? { target: Number(fields.target) } : {}), feeBps: Number(fields.feeBps), slippageBps: Number(fields.slippageBps) };
  let estimate: RiskEstimate | null = null; let validation = '';
  try { estimate = estimateRisk(risk); } catch (reason) { validation = reason instanceof Error ? reason.message : 'Check your inputs.'; }
  useEffect(() => { const clear = () => { setWindow(value => value?.kind === 'personal' ? undefined : value); setAttach(false); }; globalThis.addEventListener('zodiacs:profile-access', clear); globalThis.addEventListener('zodiacs:profile', clear); return () => { globalThis.removeEventListener('zodiacs:profile-access', clear); globalThis.removeEventListener('zodiacs:profile', clear); }; }, []);
  const selectedWindow = selectedEvent ? { kind: selectedEvent.personal ? 'personal' as const : selectedEvent.economic ? 'economic' as const : 'shared' as const, id: selectedEvent.id, ...(selectedEvent.personal ? { sourceId: selectedEvent.personal.sourceId, sourceUpdatedAt: selectedEvent.personal.sourceUpdatedAt } : {}), from: selectedEvent.personal?.window.startUtc ?? selectedEvent.at, to: selectedEvent.personal?.window.endUtc ?? selectedEvent.end ?? selectedEvent.at } : undefined;
  const currentWindow = attach ? selectedWindow : window;
  async function save(event: Event) {
    event.preventDefault(); setMessage('');
    if (!estimate) { setMessage(validation); return; }
    if (![technical, confirmation, invalidation, hypothesis].every(text => text.trim())) { setMessage('Write the setup, confirmation, invalidation and timing hypothesis.'); return; }
    if (!Number.isInteger(Number(horizon)) || Number(horizon) < 1 || Number(horizon) > 8760) { setMessage('Choose a whole horizon from 1 to 8,760 hours.'); return; }
    setBusy(true);
    try {
      await onSave({ id: editingId, baseUpdatedAt, hypothesis, plan: `${technical}\nConfirmation: ${confirmation}\nInvalidation: ${invalidation}`, setup: { interval: timeframe, technicalSetup: technical, confirmation, invalidation, risk, ...(currentWindow ? { window: currentWindow } : {}) }, horizonHours: Number(horizon), method, eventIds: currentWindow ? [currentWindow.id] : [] });
      setMessage(editingId ? 'Setup revision saved; the original remains in your journal.' : 'Setup saved in your private journal. Enter outcomes separately in Journal.'); setEditingId(undefined);
    } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Setup could not save.'); } finally { setBusy(false); }
  }
  function edit(entry: JournalEntry) {
    const setup = entry.setup!; setEditingId(entry.id); setBaseUpdatedAt(entry.updatedAt); setHypothesis(entry.hypothesis); setTechnical(setup.technicalSetup); setConfirmation(setup.confirmation); setInvalidation(setup.invalidation); setMode(setup.risk.riskMode); setTimeframe(setup.interval); setHorizon(String(entry.horizonHours)); setMethod(entry.method); setWindow(setup.window); setAttach(false); setFields({ equity: String(setup.risk.equity), riskValue: String(setup.risk.riskValue), entry: String(setup.risk.entry), stop: String(setup.risk.stop), target: setup.risk.target === undefined ? '' : String(setup.risk.target), feeBps: String(setup.risk.feeBps), slippageBps: String(setup.risk.slippageBps) }); setMessage('Editing a setup. Every saved revision remains inspectable.');
  }
  return <section class="lens-panel" data-testid="lens-setup"><h2>Setup &amp; spot risk</h2><p class="lens-muted">{instrument} · long {currency} cash instrument · cash funded · no leverage. Estimates assume both fills incur the entered fee and adverse slippage. A stop is not a guaranteed execution price.</p>
    <form class="lens-form" onSubmit={save}><div class="lens-inline"><label class="lens-field">Setup timeframe<select value={timeframe} onChange={e => setTimeframe(e.currentTarget.value as Interval)}><option value="1h">1 hour</option><option value="1d">1 day</option></select></label><label class="lens-field">Setup method<select value={method} disabled={Boolean(editingId)} onChange={e => setMethod(e.currentTarget.value as JournalEntry['method'])}><option>TA + astrology</option><option>TA only</option></select></label><label class="lens-field">Horizon (hours)<input type="number" min="1" max="8760" value={horizon} disabled={Boolean(editingId)} onInput={e => setHorizon(e.currentTarget.value)} /></label></div>
      {([['Technical setup / price levels', technical, setTechnical], ['Confirmation condition', confirmation, setConfirmation], ['Invalidation condition', invalidation, setInvalidation], ['Timing hypothesis', hypothesis, setHypothesis]] as const).map(([label, value, set]) => <label class="lens-field">{label}<textarea required maxLength={5000} value={value} onInput={e => set(e.currentTarget.value)} /></label>)}
      <fieldset class="lens-form"><legend>{currency} cash risk calculator</legend><label class="lens-field">Risk mode<select value={mode} onChange={e => setMode(e.currentTarget.value as 'percent' | 'usd' | 'quote')}><option value="percent">Percent of equity</option><option value="quote">{currency} risk budget</option></select></label><div class="lens-risk-grid">{Object.entries(fields).map(([key, value]) => <label class="lens-field">{({ equity: `Cash equity (${currency})`, riskValue: mode === 'percent' ? 'Risk (%)' : `Risk (${currency})`, entry: `Entry (${currency})`, stop: `Stop (${currency})`, target: `Target (optional ${currency})`, feeBps: 'Fee (bps per side)', slippageBps: 'Slippage (bps per side)' })[key as keyof typeof fields]}<input type="number" step="any" min="0" max={key === 'feeBps' || key === 'slippageBps' ? '1000' : undefined} value={value} required={key !== 'target'} onInput={e => setFields(current => ({ ...current, [key]: e.currentTarget.value }))} /></label>)}</div></fieldset>
      {estimate ? <div class="lens-metrics" data-testid="risk-estimate"><div><span>Units</span><strong>{estimate.units.toFixed(8)}</strong></div><div><span>{currency} notional / cash needed</span><strong>{dollars(estimate.notional)} / {dollars(estimate.funding)}</strong></div><div><span>Planned stop loss incl. costs</span><strong>{dollars(estimate.stopLoss)}</strong></div><div><span>Estimated stop costs</span><strong>{dollars(estimate.costsAtStop)}</strong></div><div><span>Net target reward : risk</span><strong>{estimate.rewardRisk === null ? 'No target' : `${estimate.rewardRisk.toFixed(2)} : 1`}</strong></div>{estimate.equityCapped && <p class="lens-notice">Size is capped by available cash equity.</p>}</div> : <p class="lens-muted" role="status">{validation}</p>}
      {selectedEvent && <label class="lens-inline"><input type="checkbox" checked={attach} onChange={() => setAttach(!attach)} />Associate selected {selectedEvent.personal ? 'personal' : selectedEvent.economic ? 'economic' : 'shared'} window: {selectedEvent.title}</label>}
      {currentWindow && <p class="lens-muted">Associated {currentWindow.kind} context · {currentWindow.from} to {currentWindow.to}. <button type="button" class="lens-text-button" onClick={() => { setAttach(false); setWindow(undefined); }}>Remove context</button></p>}
      <div class="lens-inline"><button class="lens-button lens-button--primary" disabled={busy || Boolean(storageError) || !estimate}>{busy ? 'Saving…' : editingId ? 'Save setup revision' : 'Save setup to journal'}</button>{editingId && <button type="button" class="lens-button" onClick={() => { setEditingId(undefined); setWindow(undefined); }}>Save as a new setup</button>}<button type="button" class="lens-button" onClick={onJournal}>Open journal</button></div><p role="status">{message || storageError}</p>
    </form><details class="lens-method"><summary>Sizing formula &amp; assumptions</summary><p>Entry fill = entry × (1 + slippage); stop fill = stop × (1 − slippage). Loss per unit = entry fill × (1 + fee) − stop fill × (1 − fee). Units = minimum of risk budget / loss per unit and cash equity / entry funding per unit. Target uses the same adverse slippage and two-side fees. Entry fills round up and exit fills down to the catalog tick. Units round down to the lot size, with the contract multiplier included. Equity uses the quote currency (GBX means pence); no currency conversion, taxes, financing or liquidity model. Derivative sizing requires a separately verified individual contract and explicit margin; it is unavailable for these cash plans. These are planning estimates; gaps and worse fills can exceed the budget.</p></details>
    <h3>Saved setups</h3>{entries.filter(entry => entry.instrument === instrument && entry.setup).slice().reverse().map(entry => <div class="lens-card"><p>{entry.setup!.technicalSetup}<br /><span class="lens-muted">{formatEventDate(entry.createdAt, 'UTC')} · {entry.revisions.length} saved version(s)</span></p><button class="lens-button" onClick={() => edit(entry)}>Revise setup</button></div>)}
  </section>;
}
