import assert from 'node:assert/strict';
import { ENGINE_VERSION, natalChart, moonPhase, positions } from '@zodiacs/engine';
import { execFileSync } from 'node:child_process';
assert.equal(ENGINE_VERSION, '0.1.1-rc.16');
const utc = new Date('1990-06-15T13:30:00Z'), offset = new Date('1990-06-15T19:00:00+05:30');
assert.deepEqual(positions(utc), positions(offset));
const unknown = natalChart({ utc: new Date('1990-06-15T12:00:00Z'), timeKnown: false });
assert.equal(unknown.angles, null); assert.equal(unknown.houses, null);
assert.ok(moonPhase(utc).illumination >= 0 && moonPhase(utc).illumination <= 1);
const calendar = execFileSync(process.execPath, [new URL('./calendar.mjs', import.meta.url).pathname], { encoding: 'utf8' });
assert.ok(calendar.startsWith('BEGIN:VCALENDAR\r\n')); assert.ok(calendar.includes('BEGIN:VEVENT'));
assert.ok(calendar.includes('SUMMARY:Full Moon')); assert.ok(calendar.includes('SUMMARY:New Moon'));
console.log('Published-engine recipes: version, offset equivalence, unknown time, Moon phase and calendar passed.');
