import type { CatalogLocale as Locale } from '../../lib/i18n';

export const COMPOSITE_NOTE = `A composite chart is the midpoint of two charts — a portrait of the relationship itself rather than either person. Composite houses need a location convention we won't fake, so this chart is shown without houses.`;

export type CompositeCopyKey =
  | "title"
  | "placements"
  | "aspects"
  | "noAspects"
  | "note"
  | "wheelLabel"
  | "selectionHint"
  | "noPlacements"
  | "clearSelection"
  | "readingTitle"
  | "roleTitle"
  | "pairTitle"
  | "promptTitle"
  | "englishNarrative"
  | "referencePlacement"
  | "referenceContact"
  | "provisionalMoon"
  | "moonTimeNotice"
  | "oppositeConvention"
  | "imageAction"
  | "imageTitle"
  | "imageReceipt"
  | "imageAlt"
  | "imageNoTime"
  | "imageReady"
  | "shareAction"
  | "downloadAction"
  | "shareBusy"
  | "shared"
  | "downloaded"
  | "cancelled"
  | "shareError"
  | "retry"
  | "closeImage";

export const COMPOSITE_COPY = {
  en: {
    title: 'Two charts, one midpoint',
    placements: 'Composite placements',
    aspects: 'Composite aspects',
    noAspects: 'No major composite aspects are in orb.',
    note: COMPOSITE_NOTE,
    wheelLabel: "Composite chart wheel",
    selectionHint: "Select a placement or aspect to see its details.",
    noPlacements: "These charts have no shared placements.",
    clearSelection: "Clear selection",
    readingTitle: "Reading this composite",
    roleTitle: "The role in this relationship",
    pairTitle: "How these parts meet",
    promptTitle: "A question to explore",
    englishNarrative: "Interpretive reading in English.",
    referencePlacement: "Reference placement",
    referenceContact: "Reference aspect",
    provisionalMoon: "Provisional Moon",
    moonTimeNotice: "One or both birth times are unknown. The composite Moon and its aspects are provisional; their reference positions are shown without an interpretation.",
    oppositeConvention: "Exact opposite positions use the midpoint eastward from the first chart.",
    imageAction: "Create composite image",
    imageTitle: "Composite chart",
    imageReceipt: "Midpoints of two charts · No houses or angles",
    imageAlt: "Composite chart image with midpoint placements and aspects, without houses or angles.",
    imageNoTime: "A chart without a birth time is drawn from the sky at 12:00 UTC on its date, without the Moon.",
    imageReady: "Image ready. Choose Share or Download.",
    shareAction: "Share",
    downloadAction: "Download",
    shareBusy: "Preparing composite image…",
    shared: "Composite image shared.",
    downloaded: "Composite image downloaded.",
    cancelled: "Sharing cancelled. The image is still ready.",
    shareError: "The composite image could not be prepared or shared.",
    retry: "Try again",
    closeImage: "Close image",
  },
  es: {
    title: 'Dos cartas, un punto medio',
    placements: 'Posiciones de la carta compuesta',
    aspects: 'Aspectos de la carta compuesta',
    noAspects: 'No hay aspectos mayores dentro del orbe.',
    note: 'Una carta compuesta es el punto medio de dos cartas: un retrato de la relación en sí, no de ninguna de las dos personas. Las casas compuestas requieren una convención de ubicación que no vamos a fingir, por eso esta carta se muestra sin casas.',
    wheelLabel: "Rueda de la carta compuesta",
    selectionHint: "Selecciona una posición o un aspecto para ver sus detalles.",
    noPlacements: "Estas cartas no tienen posiciones en común.",
    clearSelection: "Borrar selección",
    readingTitle: "Lectura de esta carta compuesta",
    roleTitle: "El papel en esta relación",
    pairTitle: "Cómo se encuentran estas partes",
    promptTitle: "Una pregunta para explorar",
    englishNarrative: "La interpretación que sigue está en inglés.",
    referencePlacement: "Posición de referencia",
    referenceContact: "Aspecto de referencia",
    provisionalMoon: "Luna provisional",
    moonTimeNotice: "Se desconoce una o ambas horas de nacimiento. La Luna compuesta y sus aspectos son provisionales; se muestran sus posiciones de referencia sin interpretación.",
    oppositeConvention: "Las posiciones exactamente opuestas usan el punto medio hacia el este desde la primera carta.",
    imageAction: "Crear imagen de la carta compuesta",
    imageTitle: "Carta compuesta",
    imageReceipt: "Puntos medios de dos cartas · Sin casas ni ángulos",
    imageAlt: "Imagen de la carta compuesta con posiciones de los puntos medios y aspectos, sin casas ni ángulos.",
    imageNoTime: "Una carta sin hora de nacimiento se dibuja con el cielo de las 12:00 UTC de su fecha, sin la Luna.",
    imageReady: "Imagen lista. Elige Compartir o Descargar.",
    shareAction: "Compartir",
    downloadAction: "Descargar",
    shareBusy: "Preparando imagen de la carta compuesta…",
    shared: "Imagen de la carta compuesta compartida.",
    downloaded: "Imagen de la carta compuesta descargada.",
    cancelled: "Se canceló el envío. La imagen sigue lista.",
    shareError: "No se pudo preparar o compartir la imagen de la carta compuesta.",
    retry: "Intentar de nuevo",
    closeImage: "Cerrar imagen",
  },
  pt: {
    title: 'Dois mapas, um ponto médio',
    placements: 'Posições do mapa composto',
    aspects: 'Aspectos do mapa composto',
    noAspects: 'Nenhum aspecto maior está dentro do orbe.',
    note: 'Um mapa composto é o ponto médio de dois mapas: um retrato da própria relação, não de nenhuma das duas pessoas. As casas do mapa composto exigem uma convenção de localização, e não vamos fingir que adotamos uma; por isso, este mapa é mostrado sem casas.',
    wheelLabel: "Roda do mapa composto",
    selectionHint: "Selecione uma posição ou um aspecto para ver os detalhes.",
    noPlacements: "Estes mapas não têm posições em comum.",
    clearSelection: "Limpar seleção",
    readingTitle: "Leitura deste mapa composto",
    roleTitle: "O papel nesta relação",
    pairTitle: "Como estas partes se encontram",
    promptTitle: "Uma pergunta para explorar",
    englishNarrative: "A interpretação a seguir está em inglês.",
    referencePlacement: "Posição de referência",
    referenceContact: "Aspecto de referência",
    provisionalMoon: "Lua provisória",
    moonTimeNotice: "Uma ou ambas as horas de nascimento são desconhecidas. A Lua composta e seus aspectos são provisórios; as posições de referência são mostradas sem interpretação.",
    oppositeConvention: "Posições exatamente opostas usam o ponto médio a leste a partir do primeiro mapa.",
    imageAction: "Criar imagem do mapa composto",
    imageTitle: "Mapa composto",
    imageReceipt: "Pontos médios de dois mapas · Sem casas nem ângulos",
    imageAlt: "Imagem do mapa composto com posições dos pontos médios e aspectos, sem casas nem ângulos.",
    imageNoTime: "Um mapa sem hora de nascimento é desenhado com o céu das 12:00 UTC da sua data, sem a Lua.",
    imageReady: "Imagem pronta. Escolha Compartilhar ou Baixar.",
    shareAction: "Compartilhar",
    downloadAction: "Baixar",
    shareBusy: "Preparando imagem do mapa composto…",
    shared: "Imagem do mapa composto compartilhada.",
    downloaded: "Imagem do mapa composto baixada.",
    cancelled: "Compartilhamento cancelado. A imagem continua pronta.",
    shareError: "Não foi possível preparar ou compartilhar a imagem do mapa composto.",
    retry: "Tentar novamente",
    closeImage: "Fechar imagem",
  },
  fr: {
    title: 'Deux thèmes, un point médian',
    placements: 'Positions du thème composite',
    aspects: 'Aspects du thème composite',
    noAspects: 'Aucun aspect majeur du thème composite ne se trouve dans l’orbe.',
    note: 'Un thème composite correspond aux points médians de deux thèmes : il décrit la relation elle-même, et non l’une ou l’autre personne. Les maisons du thème composite exigent une convention de lieu que nous n’allons pas inventer ; ce thème est donc présenté sans maisons.',
    wheelLabel: "Roue du thème composite",
    selectionHint: "Sélectionne une position ou un aspect pour en voir les détails.",
    noPlacements: "Ces thèmes n’ont aucune position en commun.",
    clearSelection: "Effacer la sélection",
    readingTitle: "Lecture de ce thème composite",
    roleTitle: "Le rôle dans cette relation",
    pairTitle: "Comment ces éléments se rencontrent",
    promptTitle: "Une question à explorer",
    englishNarrative: "L’interprétation qui suit est en anglais.",
    referencePlacement: "Position de référence",
    referenceContact: "Aspect de référence",
    provisionalMoon: "Lune provisoire",
    moonTimeNotice: "Une ou les deux heures de naissance sont inconnues. La Lune composite et ses aspects sont provisoires ; leurs positions de référence sont présentées sans interprétation.",
    oppositeConvention: "Les positions exactement opposées utilisent le point médian vers l’est à partir du premier thème.",
    imageAction: "Créer une image du thème composite",
    imageTitle: "Thème composite",
    imageReceipt: "Points médians de deux thèmes · Sans maisons ni angles",
    imageAlt: "Image du thème composite avec les positions des points médians et les aspects, sans maisons ni angles.",
    imageNoTime: "Un thème sans heure de naissance est dessiné avec le ciel de 12:00 UTC à sa date, sans la Lune.",
    imageReady: "Image prête. Choisis Partager ou Télécharger.",
    shareAction: "Partager",
    downloadAction: "Télécharger",
    shareBusy: "Préparation de l’image du thème composite…",
    shared: "Image du thème composite partagée.",
    downloaded: "Image du thème composite téléchargée.",
    cancelled: "Partage annulé. L’image reste prête.",
    shareError: "Impossible de préparer ou de partager l’image du thème composite.",
    retry: "Réessayer",
    closeImage: "Fermer l’image",
  },
  it: {
    title: 'Due temi, un punto medio',
    placements: 'Posizioni del tema composito',
    aspects: 'Aspetti del tema composito',
    noAspects: 'Nessun aspetto maggiore del tema composito rientra nell’orbita.',
    note: 'Un tema composito corrisponde ai punti medi di due temi: descrive la relazione stessa, non l’una o l’altra persona. Le case del tema composito richiedono una convenzione sul luogo che non intendiamo inventare, quindi questo tema viene mostrato senza case.',
    wheelLabel: "Ruota del tema composito",
    selectionHint: "Seleziona una posizione o un aspetto per vedere i dettagli.",
    noPlacements: "Questi temi non hanno posizioni in comune.",
    clearSelection: "Cancella selezione",
    readingTitle: "Lettura di questo tema composito",
    roleTitle: "Il ruolo in questa relazione",
    pairTitle: "Come si incontrano queste parti",
    promptTitle: "Una domanda da esplorare",
    englishNarrative: "L’interpretazione che segue è in inglese.",
    referencePlacement: "Posizione di riferimento",
    referenceContact: "Aspetto di riferimento",
    provisionalMoon: "Luna provvisoria",
    moonTimeNotice: "Una o entrambe le ore di nascita sono sconosciute. La Luna composita e i suoi aspetti sono provvisori; le posizioni di riferimento sono mostrate senza interpretazione.",
    oppositeConvention: "Le posizioni esattamente opposte usano il punto medio verso est a partire dal primo tema.",
    imageAction: "Crea immagine del tema composito",
    imageTitle: "Tema composito",
    imageReceipt: "Punti medi di due temi · Senza case né angoli",
    imageAlt: "Immagine del tema composito con le posizioni dei punti medi e gli aspetti, senza case né angoli.",
    imageNoTime: "Un tema senza ora di nascita è disegnato con il cielo delle 12:00 UTC della sua data, senza la Luna.",
    imageReady: "Immagine pronta. Scegli Condividi o Scarica.",
    shareAction: "Condividi",
    downloadAction: "Scarica",
    shareBusy: "Preparazione dell’immagine del tema composito…",
    shared: "Immagine del tema composito condivisa.",
    downloaded: "Immagine del tema composito scaricata.",
    cancelled: "Condivisione annullata. L’immagine è ancora pronta.",
    shareError: "Impossibile preparare o condividere l’immagine del tema composito.",
    retry: "Riprova",
    closeImage: "Chiudi immagine",
  },
  ru: {
    title: 'Две карты, одна середина',
    placements: 'Положения композитной карты',
    aspects: 'Аспекты композитной карты',
    noAspects: 'Мажорных композитных аспектов в орбисе нет.',
    note: 'Композитная карта строится по средним точкам двух карт и описывает сами отношения, а не одного из людей. Для композитных домов нужна договорённость о месте, которую мы не станем выдумывать, поэтому карта показана без домов.',
    wheelLabel: "Колесо композитной карты",
    selectionHint: "Выберите положение или аспект, чтобы увидеть подробности.",
    noPlacements: "В этих картах нет общих положений.",
    clearSelection: "Снять выделение",
    readingTitle: "Чтение этой композитной карты",
    roleTitle: "Роль в этих отношениях",
    pairTitle: "Как взаимодействуют эти части",
    promptTitle: "Вопрос для размышления",
    englishNarrative: "Следующее толкование дано на английском языке.",
    referencePlacement: "Опорное положение",
    referenceContact: "Опорный аспект",
    provisionalMoon: "Предварительное положение Луны",
    moonTimeNotice: "Время рождения одного или обоих людей неизвестно. Положение композитной Луны и её аспекты предварительны; опорные положения показаны без толкования.",
    oppositeConvention: "Для точно противоположных положений используется средняя точка к востоку от положения в первой карте.",
    imageAction: "Создать изображение композитной карты",
    imageTitle: "Композитная карта",
    imageReceipt: "Средние точки двух карт · Без домов и углов",
    imageAlt: "Изображение композитной карты с положениями средних точек и аспектами, без домов и углов.",
    imageNoTime: "Карта без времени рождения нарисована по небу на 12:00 UTC в её дату, без Луны.",
    imageReady: "Изображение готово. Выберите «Поделиться» или «Скачать».",
    shareAction: "Поделиться",
    downloadAction: "Скачать",
    shareBusy: "Подготовка изображения композитной карты…",
    shared: "Вы поделились изображением композитной карты.",
    downloaded: "Изображение композитной карты скачано.",
    cancelled: "Отправка отменена. Изображение по-прежнему готово.",
    shareError: "Не удалось подготовить изображение композитной карты или поделиться им.",
    retry: "Повторить",
    closeImage: "Закрыть изображение",
  },
} as const satisfies Record<Locale, Record<CompositeCopyKey, string>>;
