/**
 * Brazilian Portuguese copy for the additive Trust/Growth handoff.
 *
 * This flat sidecar intentionally contains only keys whose PT locale is
 * marked pending in i18n-additions.md. Shared wiring remains in the owning
 * domain catalogues.
 */
export const PT_ADDITIONS = Object.freeze({
  // WS1 — trust, disclosure, and archive receipts
  'archive.archivedReceipt': 'Cópia arquivada',
  'archive.entries.accidental-libra.receipts.mintAddress': 'Publicação de Portnoy que contém o endereço de mint de Libra',
  'archive.entries.accidental-libra.receipts.wrongLibra': 'Portnoy: “Estou comprando a Libra errada”',
  'archive.entries.astrologers-arrive.receipts.primary': 'TikTokInvestors: “Os astrólogos chegaram”',
  'archive.entries.astrology-girlies.receipts.primary': 'iJaadee: chamada da comunidade de astrologia',
  'archive.entries.horoscopes-to-hodl.receipts.primary': 'Numinous Realm: “Horóscopos para HODL”',
  'archive.entries.oldest-meme.receipts.primary': 'Andrew Kang: “O meme mais antigo da civilização humana”',
  'archive.entries.onboarding-wave.receipts.primary': 'wantonwallet: registro da entrada de mais de 1.200 carteiras',
  'archive.entries.origin.receipts.registry': 'Registro legível por máquina publicado',
  'archive.entries.pure-belief.receipts.primary': 'CZ: “Apenas um sistema de crença pura”',
  'archive.entries.zodiac-iwo.receipts.primary': 'inversebrah: publicação com abreviações do zodíaco',
  'archive.pendingPrimary': 'Cópia arquivada da fonte primária ainda pendente',
  'archive.receiptsLabel': 'Comprovantes',
  'archive.verifiedRegistry': 'Corresponde ao registro oficial',
  'disclosure.aboutLink': 'Leia as divulgações do Registro',
  'disclosure.aboutNotice': 'As declarações do operador e de interesse econômico do Registro, os doze recibos de origem datados e a procedência da criação estão publicados na página de divulgações.',
  'disclosure.adviceEvidence': '“Oficial” é apenas uma classificação do Registro: significa que um endereço, contrato, mint ou representação corresponde à lista publicada pelo Registro — não aprovação governamental, verificação de identidade, segurança, valor, liquidez ou desempenho futuro. Os avisos contextuais e os termos informam os riscos dos ativos digitais.',
  'disclosure.adviceLabel': 'Aconselhamento financeiro e solicitação',
  'disclosure.adviceStatement': 'Os registros, o contexto de mercado e o Registry Collection não constituem aconselhamento financeiro nem solicitação para comprar, vender ou manter um ativo. A Collection é uma reflexão simbólica, não uma pontuação de carteira nem um sinal de preço, e nenhuma compra é necessária.',
  'disclosure.backRegistry': 'Voltar ao Registro Zodiacs',
  'disclosure.economicEvidence': 'A declaração de posições é do próprio operador, datada de 2026-08-02 e sem verificação independente; não enumera ativos, carteiras, valores nem políticas de bloqueio, aquisição gradual ou desinvestimento, e posições privadas não são inferidas de nenhuma carteira. A distribuição de detentores é publicada por meio de capturas públicas. Em 20 de julho de 2026, a participação das dez maiores contas de token variava de 23,0% a 30,6% entre os doze ativos, com mediana de 27,2%. Os números podem ser conferidos nas capturas publicadas e nos registros públicos da blockchain.',
  'disclosure.economicLabel': 'Interesse econômico',
  'disclosure.economicSnapshotsLink': 'Capturas de distribuição',
  'disclosure.economicStatement': 'O operador declara (2026-08-02) manter posições em um ou mais dos doze ativos do Registro e não receber remuneração de indicação, taxa de plataforma, liquidez ou marketplace por nenhuma operação realizada por meio do site.',
  'disclosure.establishedLabel': 'Criação do Registro',
  'disclosure.establishedPending': 'Procedência da implantação mais antiga — pendente',
  'disclosure.establishedPrefix': 'Est.',
  'disclosure.establishedProvenance': 'Primeiro recibo de origem · 2024-07-05',
  'disclosure.evidenceHeading': 'Situação e evidências',
  'disclosure.intro': 'Esta página separa os fatos sustentados por evidências públicas das declarações fornecidas pelo operador, Zodiacs LLC. Uma declaração do operador é datada e rotulada como tal; nunca é apresentada como verificada de forma independente.',
  'disclosure.kicker': 'Divulgações do Registro',
  'disclosure.linkLabel': 'Divulgações',
  'disclosure.linkMethodology': 'Metodologia',
  'disclosure.linkPrivacy': 'Privacidade',
  'disclosure.linkRegistry': 'Registro legível por máquina',
  'disclosure.linkSdk': 'Postura do SDK',
  'disclosure.linkTerms': 'Termos',
  'disclosure.linkThesis': 'Tese',
  'disclosure.metaDescription': 'Divulgações claras sobre operador, interesse econômico, procedência, separação, acesso somente para consulta, negociação incorporada e aconselhamento financeiro no Registro do Zodiacs.org.',
  'disclosure.metaTitle': 'Divulgações — Registro do Zodiacs.org',
  'disclosure.operatorEvidence': 'Baseado em uma atualização de domínio fornecida pelo operador e datada de 2026-08-23; sem verificação independente. Substitui apenas a afirmação de 2026-08-02 de que o domínio anterior e Astrofolio eram superfícies de consumo separadas. A declaração sobre posições e ausência de remuneração mantém separadamente a data de 2026-08-02.',
  'disclosure.operatorLabel': 'Relação com o operador',
  'disclosure.operatorRequest': 'O que significa “declarado pelo operador”',
  'disclosure.operatorRequestBody': 'A linha sobre a relação com o operador resume a atualização de domínio fornecida por ele, com data. A linha de interesse econômico preserva a declaração do operador, datada separadamente. Nenhuma das duas tem verificação independente; por isso ambas levam o selo de declaração, e não o de verificado. Todas as outras linhas apontam para evidências que qualquer pessoa pode conferir.',
  'disclosure.operatorStatement': 'Atualização do operador (2026-08-23): o operador controla o domínio zodiacs.org, o repositório, as implantações, o conteúdo do Registro e a experiência oficial de Astrofolio para consumidores em zodiacs.org/astrofolio. astrofolio.xyz redireciona para essa página e não é uma superfície de consumo separada. Esta atualização não estabelece quem controla a implantação ou as autoridades administrativas dos tokens, a tesouraria, a liquidez ou a atividade de mercado.',
  'disclosure.originEvidence': 'Os doze recibos têm data de 5 de julho de 2024. Cada um foi localizado por inspeção das instruções em um RPC de arquivo e conferido nas páginas públicas da Solscan, indexadas de forma independente; os nomes dos tokens nunca foram usados como prova. As representações na Base são pontes oficiais, divulgadas separadamente na tabela do instrumento da tese.',
  'disclosure.originLabel': 'Origem',
  'disclosure.originSlot': 'Recibo de origem de {sign} — {date}',
  'disclosure.originStatement': 'Cada registro canônico é comprovado pelo seu recibo de origem: a transação que criou o mint nativo do signo na Solana.',
  'disclosure.provenancePendingShort': 'Procedência da implantação pendente',
  'disclosure.provenanceShort': 'Recibos de origem — 5 jul 2024',
  'disclosure.readOnlyEvidence': 'Aura também aceita um endereço colado, encaminha somente o endereço usado em sua consulta de ativos e o SDK documenta e testa uma superfície somente para leitura. Uma conexão não comprova identidade, controle ou propriedade legal.',
  'disclosure.tradeLabel': 'Limite de transações do catálogo',
  'disclosure.tradeStatement': 'Os perfis do catálogo do Registro não contêm um painel de negociação, um percurso de compra nem uma ligação externa a um mercado; mostram apenas contexto público de mercado e endereços verificados. Depois de uma ação explícita e da confirmação de elegibilidade, a página separada Como comprar do Astrofolio pode carregar uma ferramenta independente da Jupiter. A Jupiter monta e recebe a transação proposta, e a carteira da pessoa usuária a revisa e assina localmente. O Zodiacs.org nunca guarda chaves ou fundos, assina uma transação nem passa a poder revertê-la.',
  'disclosure.tradeEvidence': 'As páginas geradas do catálogo do Registro não contêm um anfitrião de carteira, um sinalizador ou programa de negociação, instruções de transação nem uma ligação direta a um mercado. O código permite verificar que a ferramenta separada do Astrofolio é opcional: ela carrega a Jupiter somente após o clique da pessoa usuária e mantém montagem, assinatura e envio entre a Jupiter e a carteira dessa pessoa.',
  'disclosure.linkTradeExample': 'Ferramenta opcional de compra do Astrofolio',
  'disclosure.readOnlyLabel': 'Operação somente para consulta',
  'disclosure.readOnlyStatement': 'As superfícies de consulta do Registro, os perfis do catálogo e o @zodiacs/sdk são somente para leitura. O Registry Collection pode se conectar a uma carteira compatível apenas após um clique da pessoa usuária para obter as contas públicas autorizadas; ele usa um endereço compatível na consulta e não detém ativos, solicita assinaturas ou aprovações, constrói ou envia transações nem troca de rede. Esta declaração de somente leitura não descreve a ferramenta separada e opcional Como comprar do Astrofolio.',
  'disclosure.scope': 'Estas divulgações se aplicam à Ala do acervo. As ferramentas de astrologia continuam gratuitas, calculadas no navegador e utilizáveis sem o Registro.',
  'disclosure.separationEvidence': 'As calculadoras fazem os cálculos no navegador e não exigem interação com o Registro. Aura mantém o cálculo do mapa no dispositivo e envia somente o endereço público selecionado por sua consulta de ativos.',
  'disclosure.separationLabel': 'Separação',
  'disclosure.separationStatement': 'As principais ferramentas de astrologia continuam gratuitas, não contêm publicidade nem rastreadores entre sites e podem ser usadas sem o Registro. Registry Collection é uma ligação opcional que lê lado a lado um mapa salvo e o registro público de uma carteira; o registro da carteira não altera o cálculo do mapa.',
  'disclosure.statementHeading': 'Declaração',
  'disclosure.statusAttested': 'Declarado pelo operador — sem verificação independente',
  'disclosure.statusPending': 'Confirmação do operador pendente',
  'disclosure.statusVerified': 'Verificado em materiais publicados',
  'disclosure.tableLabel': 'Divulgações do Registro e situação das evidências',
  'disclosure.title': 'Os fatos, inclusive os ainda não resolvidos.',
  'registry.establishmentProvenanceLink': 'Procedência ↗',
  'registry.ogLotAlt': '{sign} — Nº {number} de 12, lote {lot} de XII no Registro oficial do Zodiacs.org.',
  'registry.verifierNotFoundInline': 'não encontrado no registro oficial do Zodiacs.org',
  'registry.verifierNotFoundSentence': 'Não encontrado no registro oficial do Zodiacs.org.',

  // WS2b — email capture and shared footer
  'emailCaptureChangeSign': 'Alterar',
  'emailCaptureCopy': 'Uma previsão semanal para seu signo. Grátis, cancele quando quiser.',
  'emailCaptureEmailLabel': 'Endereço de e-mail',
  'emailCaptureEmailPlaceholder': 'voce@exemplo.com',
  'emailCaptureError': 'Não foi possível iniciar a assinatura. Tente de novo.',
  'emailCaptureErrorTitle': 'Assinatura indisponível',
  'emailCaptureHoneypot': 'Deixe este campo em branco',
  'emailCaptureKicker': 'Previsão semanal gratuita',
  'emailCaptureNoSign': 'Pular o signo',
  'emailCapturePersonalTitle': 'Sua semana de {sign} pela frente.',
  'emailCapturePrivacy': 'Armazenamos apenas seu e-mail e o signo escolhido — nunca seus dados de nascimento.',
  'emailCaptureSignLegend': 'Seu signo solar (opcional)',
  'emailCaptureSubmit': 'Enviar minha semana',
  'emailCaptureSubmitting': 'Inscrevendo…',
  'emailCaptureSuccess': 'Confira seu e-mail para confirmar a assinatura.',
  'emailCaptureTitle': 'Sua semana pela frente.',
  'emailCaptureUsingSign': 'Usando seu signo solar: {sign}',
  'emailConfirmAction': 'Confirmar assinatura',
  'emailConfirmBody': 'Confirme esta assinatura para começar a receber a previsão semanal gratuita. Até lá, nenhuma assinatura semanal estará ativa.',
  'emailConfirmedBody': 'Sua previsão semanal gratuita está ativa. Toda mensagem inclui um link para cancelar a assinatura.',
  'emailConfirmedTitle': 'Assinatura confirmada.',
  'emailConfirmIgnore': 'Se você não solicitou isto, ignore este e-mail. Nenhuma assinatura será ativada.',
  'emailConfirmInvalidBody': 'O link de confirmação é inválido ou expirou. Volte ao Zodiacs.org para solicitar outro.',
  'emailConfirmInvalidTitle': 'Este link não é válido.',
  'emailConfirmMessage': 'Confirme que você quer receber a previsão semanal gratuita do Zodiacs.org:',
  'emailConfirmSubject': 'Confirme sua previsão semanal do Zodiacs.org',
  'emailConfirmTitle': 'Só mais uma confirmação.',
  'emailPendingBody': 'Use o link de confirmação que enviamos antes de começar a receber sua previsão semanal.',
  'emailPendingTitle': 'Confira seu e-mail.',
  'emailReturnHome': 'Voltar ao Zodiacs.org',
  'footerDisclosure': 'Divulgações',
  'footerWidgets': 'Widgets',

  // WS2c — OG and social-card art
  'og.compatibility.data': 'O que funciona · o que pesa · o que faz durar',
  'og.compatibility.kicker': 'Compatibilidade',
  'og.compatibility.title': '{a}<br/>e {b}',
  'og.disclosure.alt': 'Divulgações do Registro — fatos verificados e confirmações pendentes do operador.',
  'og.disclosure.kicker': 'Divulgações do Registro',
  'og.disclosure.subtitle': 'Divulgações sobre operador, interesse econômico, procedência, separação e consulta.',
  'og.disclosure.title': 'Os fatos, inclusive os ainda não resolvidos.',
  'og.fallbackAlt': 'Zodiacs.org — mapas astrais, guias dos signos e ferramentas de astrologia gratuitos.',
  'og.horoscope.kicker': 'Horóscopo mensal',
  'og.horoscope.subtitle': 'Horóscopos mensais baseados em fases reais da Lua, retrógrados e trânsitos importantes.',
  'og.pin.horoscope.kicker': 'Horóscopo mensal',
  'og.pin.horoscope.subtitle': 'Baseado no céu real: fases da Lua, retrógrados e trânsitos importantes, cada um com sua data.',
  'og.pin.horoscope.title': '{sign}, neste mês',
  'og.pin.howTo.kicker': 'Aprenda astrologia',
  'og.pin.howTo.steps.aspects': '3 · Os aspectos atuantes',
  'og.pin.howTo.steps.bigThree': '1 · O trio principal',
  'og.pin.howTo.steps.rooms': '2 · Planetas, casa por casa',
  'og.pin.howTo.steps.weather': '4 · O clima do mapa',
  'og.pin.howTo.title': 'Como ler um mapa astral.',
  'og.pin.signGuide.kicker': 'Guia do signo',
  'og.placements.kicker': 'Posicionamentos',
  'og.placements.subtitle': 'Os doze posicionamentos de {planet}, em detalhes.',
  'og.placements.title': '{planet} pelos<br/>signos',
  'og.planetNames.jupiter': 'Júpiter',
  'og.planetNames.mars': 'Marte',
  'og.planetNames.mercury': 'Mercúrio',
  'og.planetNames.moon': 'Lua',
  'og.planetNames.neptune': 'Netuno',
  'og.planetNames.pluto': 'Plutão',
  'og.planetNames.saturn': 'Saturno',
  'og.planetNames.sun': 'Sol',
  'og.planetNames.uranus': 'Urano',
  'og.planetNames.venus': 'Vênus',
  'og.astrofolio.alt': 'Astrofolio: a coleção de doze tokens oficiais do Zodíaco.',
  'og.terminal.alt': 'Terminal: contexto especializado de mercado e pesquisa revisada para os doze tokens oficiais do Zodíaco.',
  'og.wing.data': 'Astrofolio · Registry · Terminal',
  'og.wing.kicker': 'Zodiacs.org',
  'og.wing.subtitle': 'Registros oficiais e contexto público de mercado para os doze signos do Zodíaco.',
  'og.wing.title': 'Os Doze',
  'og.registryLot.kicker': 'O Registro',
  'og.registryLot.numberLine': 'Nº {number} / 12 · lote {lot} de XII',
  'og.registryLot.subtitle': 'Registro oficial · origem nativa na Solana · representação via bridge na Base',
  'og.rising.data': 'o ascendente muda de signo aproximadamente a cada duas horas',
  'og.rising.kicker': 'Signos ascendentes',
  'og.rising.subtitle': 'Como o mundo vê você primeiro — e o planeta que rege seu mapa.',
  'og.rising.title': '{sign}<br/>ascendente',
  'og.share.subtitle': 'Mapas astrais, guias dos signos e ferramentas de astrologia gratuitos.',
  'og.share.title': 'Explore as estrelas por trás da sua história.',
  'og.signGuide.kicker': 'Guia do signo',
  'og.signNames.aquarius': 'Aquário',
  'og.signNames.aries': 'Áries',
  'og.signNames.cancer': 'Câncer',
  'og.signNames.capricorn': 'Capricórnio',
  'og.signNames.gemini': 'Gêmeos',
  'og.signNames.leo': 'Leão',
  'og.signNames.libra': 'Libra',
  'og.signNames.pisces': 'Peixes',
  'og.signNames.sagittarius': 'Sagitário',
  'og.signNames.scorpio': 'Escorpião',
  'og.signNames.taurus': 'Touro',
  'og.signNames.virgo': 'Virgem',
  'og.thesis.alt': 'A crença é o ativo mais antigo — a tese do Registro do Zodiacs.org.',
  'og.thesis.footer': 'zodiacs.org — O Registro · Revisado em julho de 2026',
  'og.thesis.kicker': 'A Tese',
  'og.thesis.title': 'A crença é o ativo mais antigo.',
  'og.tools.ask.kicker': 'Assistente com fontes',
  'og.tools.ask.sub': 'O site, a astrologia ou o seu próprio mapa — respondido a partir das páginas deste site, com as fontes nomeadas.',
  'og.tools.ask.title': 'Pergunte ao Zodiacs',
  'og.tools.baby-zodiac.kicker': 'Calculadora gratuita',
  'og.tools.baby-zodiac.sub': 'O Sol quase certo da data prevista, as possíveis Luas da semana e o que depende da hora.',
  'og.tools.baby-zodiac.title': 'Qual será o signo do bebê?',
  'og.tools.birth-chart.kicker': 'Calculadora gratuita',
  'og.tools.birth-chart.sub': 'Sol, Lua, ascendente, casas e aspectos — calculados no seu dispositivo.',
  'og.tools.birth-chart.title': 'Seu mapa astral',
  'og.tools.birthday.kicker': 'Astrologia do aniversário',
  'og.tools.birthday.sub': 'Signo solar conferido ao longo de 91 anos, faixas de graus, decanatos e tabelas de cúspides.',
  'og.tools.birthday.title': 'Todas as datas, calculadas',
  'og.tools.compatibility.kicker': 'Compatibilidade',
  'og.tools.compatibility.sub': 'Sinastria do mapa inteiro — além de guias para todas as 78 combinações de signos.',
  'og.tools.compatibility.title': 'Dois mapas comparados',
  'og.tools.eclipses.kicker': 'O calendário',
  'og.tools.eclipses.sub': 'Todos os eclipses solares e lunares até 2028, com horários exatos do pico e signos.',
  'og.tools.eclipses.title': 'Eclipses com data',
  'og.tools.full-moon-calendar.kicker': 'O calendário',
  'og.tools.full-moon-calendar.sub': 'Instantes exatos até 2027, com o signo, o grau e o nome de cada Lua.',
  'og.tools.full-moon-calendar.title': 'Todas as luas cheias',
  'og.tools.horoscopes.kicker': 'Horóscopos mensais',
  'og.tools.horoscopes.sub': 'Baseados em fases reais da Lua, retrógrados e trânsitos importantes.',
  'og.tools.horoscopes.title': 'Todos os doze signos',
  'og.tools.how-to-read-a-birth-chart.kicker': 'Aprenda astrologia',
  'og.tools.how-to-read-a-birth-chart.sub': 'Trio principal, planetas casa por casa, aspectos atuantes e, por fim, o clima — em ordem.',
  'og.tools.how-to-read-a-birth-chart.title': 'Como ler um mapa astral',
  'og.tools.learn.kicker': 'Aprenda astrologia',
  'og.tools.learn.sub': 'Os signos, os planetas, as casas e os aspectos, em linguagem clara.',
  'og.tools.learn.title': 'Leia seu mapa',
  'og.tools.mercury-retrograde.kicker': 'O calendário',
  'og.tools.mercury-retrograde.sub': 'Todos os períodos até 2027, calculados a partir do movimento real do planeta.',
  'og.tools.mercury-retrograde.title': 'Mercúrio retrógrado',
  'og.tools.moon-phase.kicker': 'Calculadora gratuita',
  'og.tools.moon-phase.sub': 'A fase desta noite e a Lua de qualquer data importante para você.',
  'og.tools.moon-phase.title': 'A Lua, em qualquer noite',
  'og.tools.moon-sign.kicker': 'Calculadora gratuita',
  'og.tools.moon-sign.sub': 'Como você sente e o que acalma você — pela data, hora e local de nascimento.',
  'og.tools.moon-sign.title': 'Seu signo lunar',
  'og.tools.retrogrades.kicker': 'O calendário',
  'og.tools.retrogrades.sub': 'Todos os oito planetas, 2026–2027, calculados de estação a estação.',
  'og.tools.retrogrades.title': 'Todos os retrógrados',
  'og.tools.rising-sign.kicker': 'Calculadora gratuita',
  'og.tools.rising-sign.sub': 'Como as pessoas veem você primeiro — pela hora e pelo local de nascimento.',
  'og.tools.rising-sign.title': 'Seu ascendente',
  'og.tools.saturn-return.kicker': 'Calculadora gratuita',
  'og.tools.saturn-return.sub': 'As datas exatas, incluindo cada passagem e cada ciclo retrógrado.',
  'og.tools.saturn-return.title': 'Seu retorno de Saturno',
  'og.tools.today.kicker': 'Seu resumo diário',
  'og.tools.today.sub': 'O céu ao meio-dia comparado de forma privada com o último mapa salvo neste dispositivo.',
  'og.tools.today.title': 'Hoje, sobre seu mapa',
  'og.tools.tools.kicker': 'Ferramentas gratuitas',
  'og.tools.tools.sub': 'Mapa astral, compatibilidade, signo lunar e mais — calculados no seu dispositivo.',
  'og.tools.tools.title': 'Calculadoras, sem cadastro',
  'og.tools.transits.kicker': 'Rastreador gratuito',
  'og.tools.transits.sub': 'O céu atual em aspecto com seu mapa astral, a até 3° do ponto exato.',
  'og.tools.transits.title': 'Seus trânsitos, hoje',

  // WS2d — structured data
  'schema.applicationCategory': 'LifestyleApplication',
  'schema.breadcrumbHome': 'Zodiacs.org',
  'schema.breadcrumbLabels.about': 'Sobre',
  'schema.breadcrumbLabels.archive': 'Acervo',
  'schema.breadcrumbLabels.baby-zodiac': 'Zodíaco do bebê',
  'schema.breadcrumbLabels.birth-chart': 'Mapa astral',
  'schema.breadcrumbLabels.birthday': 'Astrologia do aniversário',
  'schema.breadcrumbLabels.compatibility': 'Compatibilidade',
  'schema.breadcrumbLabels.disclosure': 'Divulgações',
  'schema.breadcrumbLabels.eclipses': 'Eclipses',
  'schema.breadcrumbLabels.es': 'Español',
  'schema.breadcrumbLabels.feeds': 'Feeds',
  'schema.breadcrumbLabels.full-moon-calendar': 'Calendário da Lua cheia',
  'schema.breadcrumbLabels.horoscopes': 'Horóscopos',
  'schema.breadcrumbLabels.houses': 'Casas',
  'schema.breadcrumbLabels.learn': 'Aprenda astrologia',
  'schema.breadcrumbLabels.markets': 'Rota do Terminal para a plataforma',
  'schema.breadcrumbLabels.mercury-retrograde': 'Mercúrio retrógrado',
  'schema.breadcrumbLabels.methodology': 'Metodologia',
  'schema.breadcrumbLabels.moon-phase': 'Fase da Lua',
  'schema.breadcrumbLabels.moon-sign': 'Signo lunar',
  'schema.breadcrumbLabels.placements': 'Posicionamentos',
  'schema.breadcrumbLabels.planets': 'Planetas',
  'schema.breadcrumbLabels.privacy': 'Privacidade',
  'schema.breadcrumbLabels.profile': 'Perfil',
  'schema.breadcrumbLabels.registry': 'Registro Zodiacs',
  'schema.breadcrumbLabels.research': 'Pesquisa de mercados',
  'schema.breadcrumbLabels.retrogrades': 'Retrógrados',
  'schema.breadcrumbLabels.rising-sign': 'Ascendente',
  'schema.breadcrumbLabels.saturn-return': 'Retorno de Saturno',
  'schema.breadcrumbLabels.sdk': 'SDK',
  'schema.breadcrumbLabels.terms': 'Termos',
  'schema.breadcrumbLabels.astrofolio': 'Astrofolio',
  'schema.breadcrumbLabels.terminal': 'Terminal',
  'schema.breadcrumbLabels.thesis': 'A Tese',
  'schema.breadcrumbLabels.today': 'Hoje',
  'schema.breadcrumbLabels.tools': 'Ferramentas de astrologia',
  'schema.breadcrumbLabels.transits': 'Trânsitos',
  'schema.breadcrumbLabels.widgets': 'Widgets',
  'schema.browserRequirements': 'Requer um navegador moderno.',
  'schema.currency': 'USD',
  'schema.freePrice': '0',
  'schema.operatingSystem': 'Qualquer dispositivo com um navegador moderno',
  'schema.organizationAlternateName': 'Zodiacs.org',
  'schema.organizationName': 'Zodiacs',
  'schema.websiteDescription': 'Mapas astrais, signos lunares, compatibilidade, horóscopos e guias dos signos gratuitos — privados no seu navegador.',
  'schema.websiteName': 'Zodiacs.org',

  // WS3 — share cards and result sharing
  'compatibilityPrefill.clear': 'Limpar combinação de signos solares carregada',
  'compatibilityPrefill.help': 'Isso mantém visível o contexto dos signos solares enquanto você informa os dois mapas reais abaixo. Não inventa dados de nascimento.',
  'compatibilityPrefill.title': 'Combinação de {a} e {b} carregada',
  'shareCard.balanced': 'Equilibrado',
  'shareCard.approachAction': 'Compartilhar como chegar até mim',
  'shareCard.referenceTimeNote': 'Posições de referência · Hora de nascimento desconhecida',
  'shareCard.approachBirthTimeNote': 'A hora de nascimento acrescentaria meu Ascendente.',
  'shareCard.approachKicker': 'PRIMEIRO CONTATO · CONFIANÇA · ATRITO',
  'shareCard.approachMoonTimeNote': 'Minha Lua pode mudar de signo sem uma hora exata de nascimento.',
  'shareCard.approachTitle': 'Como chegar até mim',
  'shareCard.bigThreeAction': 'Compartilhar o trio principal',
  'shareCard.bigThreeTitle': 'Seu trio principal',
  'shareCard.compatibilityAction': 'Compartilhar esta compatibilidade',
  'shareCard.compatibilityBalance': 'Uma troca equilibrada entre fluidez e intensidade',
  'shareCard.compatibilityBusy': 'Criando o cartão de compatibilidade…',
  'shareCard.compatibilityCharge': 'Química que pede atenção',
  'shareCard.compatibilityError': 'Não foi possível criar este cartão no seu navegador.',
  'shareCard.moonSettledNote': 'A Lua ficou neste signo o dia todo, em todo lugar.',
  'shareCard.compatibilityFlow': 'Fluidez, com um atrito útil',
  'shareCard.compatibilitySaved': 'Cartão de compatibilidade salvo.',
  'shareCard.compatibilityTitle': 'Compatibilidade',
  'shareCard.dominant': 'Elemento dominante: {element} · {modality}',
  'shareCard.engineReceipt': 'Motor {version}',
  'shareCard.fullChartAction': 'Compartilhar o mapa completo',
  'shareCard.fullChartTitle': 'Um mapa astral',
  'shareCard.moon': 'Lua',
  'shareCard.moonDescriptor': 'Instinto e vida emocional',
  'shareCard.rising': 'Ascendente',
  'shareCard.risingDescriptor': 'Primeira impressão e horizonte do mapa',
  'shareCard.signatureAction': 'Compartilhar a assinatura do meu mapa',
  'shareCard.signatureKicker': 'O destaque do meu mapa',
  'shareCard.signatureTitle': 'A assinatura do meu mapa',
  'shareCard.sun': 'Sol',
  'shareCard.sunDescriptor': 'Identidade central e direção',
  'shareCard.tightestContacts': 'Contatos mais exatos',

  // WS4 — PWA, install prompt, and flag-off push scaffold
  'push.notification.body': 'Sua nota diária do céu está pronta.',
  'push.notification.title': 'Hoje no Zodiacs.org',
  'pwa.manifest.description': 'Mapas astrais, compatibilidade e trânsitos — gratuitos, exatos e mantidos no seu dispositivo.',
  'pwa.manifest.name': 'Zodiacs — astrologia calculada no dispositivo',
  'pwa.manifest.shortName': 'Zodiacs',
  'pwa.prompt.body': 'Instale o Zodiacs para voltar mais rápido às suas ferramentas privadas, calculadas no navegador.',
  'pwa.prompt.dismiss': 'Não, não perguntar novamente',
  'pwa.prompt.heading': 'Quer manter suas ferramentas por perto?',
  'pwa.prompt.icons': 'Os doze signos do zodíaco',
  'pwa.prompt.install': 'Instalar o Zodiacs',
  'pwa.prompt.ios': 'No iPhone ou iPad, toque em Compartilhar e depois em Adicionar à Tela de Início.',

  // WS5 — programmatic pages and Chinese zodiac
  'chineseZodiac.allAnimals': 'Todos os doze anos dos animais',
  'chineseZodiac.animalKicker': 'Guia do ano do animal',
  'chineseZodiac.animals.dog.association': 'Tradicionalmente associado à lealdade, à vigilância e à proteção.',
  'chineseZodiac.animals.dog.context': 'O Cão é o décimo primeiro. Como em todas as páginas deste guia, a associação descreve uma tradição interpretativa, não um diagnóstico de personalidade.',
  'chineseZodiac.animals.dog.name': 'Cão',
  'chineseZodiac.animals.dragon.association': 'Tradicionalmente associado ao poder auspicioso, à vitalidade e à autoridade.',
  'chineseZodiac.animals.dragon.context': 'O Dragão é o animal mítico da sequência. Ele tem um caráter cultural diferente do dragão hostil conhecido em grande parte das narrativas europeias.',
  'chineseZodiac.animals.dragon.name': 'Dragão',
  'chineseZodiac.animals.goat.association': 'Tradicionalmente associada ao cuidado, à harmonia e ao cultivo criativo.',
  'chineseZodiac.animals.goat.context': 'Em versões em inglês, aparecem Goat (cabra), Ram (carneiro) e Sheep (ovelha). O termo chinês original não impõe a mesma distinção entre espécies feita pelo inglês.',
  'chineseZodiac.animals.goat.name': 'Cabra',
  'chineseZodiac.animals.horse.association': 'Tradicionalmente associado ao esforço, à coragem, à resiliência e ao movimento.',
  'chineseZodiac.animals.horse.context': 'O Cavalo é o sétimo da sequência. O material do Smithsonian sobre o Cavalo de Fogo de 2026 destaca trabalho árduo, coragem e resiliência.',
  'chineseZodiac.animals.horse.name': 'Cavalo',
  'chineseZodiac.animals.monkey.association': 'Tradicionalmente associado à engenhosidade, à brincadeira e à adaptação rápida.',
  'chineseZodiac.animals.monkey.context': 'O Macaco é o nono. O folclore e as leituras populares de personalidade acrescentam camadas além do animal do calendário; essas camadas não são uniformes em todas as comunidades chinesas.',
  'chineseZodiac.animals.monkey.name': 'Macaco',
  'chineseZodiac.animals.ox.association': 'Tradicionalmente associado ao trabalho constante, à resistência e à responsabilidade prática.',
  'chineseZodiac.animals.ox.context': 'O boi e o búfalo-d’água podem ser tratados como a mesma categoria do zodíaco na arte chinesa. A imagem enfatiza o trabalho persistente, não a velocidade.',
  'chineseZodiac.animals.ox.name': 'Boi',
  'chineseZodiac.animals.pig.association': 'Tradicionalmente associado à fartura, à generosidade e à conclusão.',
  'chineseZodiac.animals.pig.context': 'O Porco encerra a sequência dos animais antes que ela volte ao Rato. Referências em inglês usam tanto Boar (javali) quanto Pig (porco).',
  'chineseZodiac.animals.pig.name': 'Porco',
  'chineseZodiac.animals.rabbit.association': 'Tradicionalmente associado à vigilância, à graça e ao movimento cuidadoso.',
  'chineseZodiac.animals.rabbit.context': 'Fontes em inglês podem usar Rabbit (coelho) ou Hare (lebre). Tradições regionais do zodíaco podem nomear outro animal, um dos motivos para este guia se limitar ao ciclo chinês.',
  'chineseZodiac.animals.rabbit.name': 'Coelho',
  'chineseZodiac.animals.rat.association': 'Tradicionalmente associado à atenção, à adaptabilidade e à capacidade de encontrar uma saída em circunstâncias limitadas.',
  'chineseZodiac.animals.rat.context': 'O Rato abre a sequência de doze anos. Resumos modernos de personalidade costumam chamá-lo de engenhoso; essa é uma associação cultural, não um traço medido.',
  'chineseZodiac.animals.rat.name': 'Rato',
  'chineseZodiac.animals.rooster.association': 'Tradicionalmente associado à diligência, à marcação do tempo e à dedicação ao trabalho.',
  'chineseZodiac.animals.rooster.context': 'O Met aponta o despertar cedo do galo como base para associações com diligência e trabalho, além de documentar seu longo uso como motivo auspicioso na arte.',
  'chineseZodiac.animals.rooster.name': 'Galo',
  'chineseZodiac.animals.snake.association': 'Tradicionalmente associada à percepção, à reserva e à transformação.',
  'chineseZodiac.animals.snake.context': 'A Serpente vem depois do Dragão no ciclo. Os traços interpretativos variam conforme a fonte, a família e a região; a posição no calendário é o fato estável.',
  'chineseZodiac.animals.snake.name': 'Serpente',
  'chineseZodiac.animals.tiger.association': 'Tradicionalmente associado à coragem, à força e à proteção.',
  'chineseZodiac.animals.tiger.context': 'O Tigre tem um caráter protetor e também arrojado na cultura visual chinesa. Listas curtas de traços de personalidade captam apenas um dos usos do símbolo.',
  'chineseZodiac.animals.tiger.name': 'Tigre',
  'chineseZodiac.associationLabel': 'Associação tradicional',
  'chineseZodiac.boundaryBody': 'O animal do ano não muda em 1º de janeiro. Se a data de nascimento cair em janeiro ou no início de fevereiro, confira a data do Ano-Novo Lunar daquele ano antes de escolher um animal. As datas também variam entre tradições asiáticas, e nem toda comunidade usa o mesmo zodíaco.',
  'chineseZodiac.boundaryTitle': 'O ano começa no Ano-Novo Lunar',
  'chineseZodiac.branchLabel': 'Ramo Terrestre',
  'chineseZodiac.chartLink': 'Calcule um mapa astral tropical ocidental',
  'chineseZodiac.historyBody': 'Os doze animais são associados aos doze Ramos Terrestres. Evidências históricas situam a associação entre animais e calendário na China já no século III a.C., firmemente estabelecida no século I d.C. Os ramos também se combinam com dez Troncos Celestiais em um ciclo de sessenta partes.',
  'chineseZodiac.historyTitle': 'O que o ciclo registra',
  'chineseZodiac.hubIntro': 'Uma introdução cuidadosa ao zodíaco chinês: a sequência dos animais, as tabelas de anos, o contexto histórico e o limite que não cai em 1º de janeiro.',
  'chineseZodiac.hubTitle': 'O ciclo de doze anos dos animais.',
  'chineseZodiac.iconRailNote': 'Os discos coloridos são a marca dos signos ocidentais do Zodiacs.org. Eles não substituem os animais do zodíaco chinês nem correspondem a eles.',
  'chineseZodiac.itemLink': 'Leia sobre o Ano do {animal}',
  'chineseZodiac.kicker': 'Zodíaco chinês',
  'chineseZodiac.learnLabel': 'Aprenda',
  'chineseZodiac.limitsBody': 'O animal do ano é uma camada do calendário. Uma leitura mais completa da astrologia chinesa também pode considerar o Tronco Celestial e o elemento, o mês, o dia e a hora. O animal do ano, sozinho, não determina uma personalidade nem prevê um resultado.',
  'chineseZodiac.limitsTitle': 'O que isso revela — e o que não revela',
  'chineseZodiac.metaAnimalDescription': 'Ano do {animal}: anos do ciclo, Ramo Terrestre {branch} ({pinyin}), associações tradicionais e limite do Ano-Novo Lunar.',
  'chineseZodiac.metaAnimalTitle': 'Ano do {animal} — Anos do zodíaco chinês | Zodiacs.org',
  'chineseZodiac.metaHubTitle': 'Zodíaco chinês — Os doze anos dos animais | Zodiacs.org',
  'chineseZodiac.next': 'Próximo animal',
  'chineseZodiac.numberLabel': 'Nº {number}',
  'chineseZodiac.positionValue': '{position} de 12',
  'chineseZodiac.previous': 'Animal anterior',
  'chineseZodiac.separateBody': 'A astrologia tropical ocidental posiciona os planetas em relação a doze setores da eclíptica e usa o momento exato do nascimento. As páginas do zodíaco chinês aqui partem de um ano do calendário lunissolar e de seu ramo animal. Os dois sistemas podem ser estudados lado a lado, mas um não se traduz no outro.',
  'chineseZodiac.separateTitle': 'Um sistema diferente da astrologia tropical ocidental',
  'chineseZodiac.sequenceLabel': 'Posição na sequência',
  'chineseZodiac.sequenceTitle': 'Os doze animais, em ordem',
  'chineseZodiac.siteName': 'Zodiacs.org',
  'chineseZodiac.sourceMet': 'The Met — o calendário animal de doze anos e sua história',
  'chineseZodiac.sourceMetBulletin': 'The Met Bulletin — animais, ramos e o ciclo de sessenta partes',
  'chineseZodiac.sourceMetHub': 'The Met — história do ciclo de doze animais do calendário',
  'chineseZodiac.sourceSmithsonian': 'Smithsonian — sequência do zodíaco chinês e contexto do Ano-Novo Lunar',
  'chineseZodiac.sourceSmithsonianHub': 'Smithsonian — Ano-Novo Lunar e sequência do zodíaco',
  'chineseZodiac.sourceTitle': 'Fontes museológicas e culturais',
  'chineseZodiac.westernLink': 'Leia como funcionam as datas do zodíaco tropical ocidental',
  'chineseZodiac.yearOf': 'Ano do {animal}',
  'chineseZodiac.yearsBoundary': 'Estes rótulos nomeiam o ano lunissolar que começa durante o ano gregoriano indicado. Nascimentos em janeiro e no início de fevereiro podem pertencer ao animal anterior.',
  'chineseZodiac.yearsLabel': 'Anos do ciclo',
  'chineseZodiac.yearsTitle': 'Anos recentes e próximos do ciclo',
  'programmatic.compatibilityPrefillCta': 'Abrir a calculadora com {a} e {b} carregados',

  // WS6 — widgets
  'widgets.accentLabel': 'Cor de destaque',
  'widgets.backlinkNote': 'O link “Com tecnologia do Zodiacs.org” faz parte de todos os widgets e não pode ser removido.',
  'widgets.changePlace': 'Alterar local de nascimento',
  'widgets.chartError': 'Não foi possível calcular o mapa neste navegador.',
  'widgets.chartIntro': 'Sol, Lua e ascendente — calculados aqui com privacidade.',
  'widgets.chartOption': 'Mini mapa astral',
  'widgets.chartPrivacy': 'Calculado neste dispositivo. Nada do que você informa aqui é enviado a uma API de mapas astrais.',
  'widgets.chartTitle': 'Mini mapa astral',
  'widgets.codeLabel': 'Código de incorporação',
  'widgets.computeAction': 'Descobrir o trio principal',
  'widgets.computing': 'Calculando…',
  'widgets.copiedAction': 'Copiado',
  'widgets.copyAction': 'Copiar código de incorporação',
  'widgets.darkOption': 'Escuro',
  'widgets.dateLabel': 'Data de nascimento',
  'widgets.generatorTitle': 'Crie um widget incorporado',
  'widgets.iframeOption': 'iframe em sandbox',
  'widgets.illumination': '{percent}% iluminada',
  'widgets.lightOption': 'Claro',
  'widgets.modeLabel': 'Modo de incorporação',
  'widgets.moon': 'Lua',
  'widgets.moonOption': 'Fase da Lua hoje',
  'widgets.moonSign': 'Lua em {sign}',
  'widgets.moonTitle': 'Fase da Lua hoje',
  'widgets.noPlaces': 'Nenhum lugar encontrado',
  'widgets.noRetrograde': 'Nenhum planeta retrógrado',
  'widgets.pageIntro': 'Três ferramentas privadas de astrologia. O iframe é principal; o script monta o mesmo documento isolado. Todo widget mantém o crédito do Zodiacs.org.',
  'widgets.pageKicker': 'Widgets',
  'widgets.pageMetaDescription': 'Incorpore a fase da Lua, o céu atual ou um mini mapa astral privado em qualquer site. Modos iframe em sandbox e script, grátis com o crédito do Zodiacs.org mantido.',
  'widgets.pageMetaTitle': 'Widgets gratuitos de astrologia — Lua, céu e mapa | Zodiacs.org',
  'widgets.pageTitle': 'O céu, no seu site.',
  'widgets.phaseNames.First Quarter': 'Quarto crescente',
  'widgets.phaseNames.Full Moon': 'Lua cheia',
  'widgets.phaseNames.Last Quarter': 'Quarto minguante',
  'widgets.phaseNames.New Moon': 'Lua nova',
  'widgets.phaseNames.Waning Crescent': 'Lua minguante',
  'widgets.phaseNames.Waning Gibbous': 'Gibosa minguante',
  'widgets.phaseNames.Waxing Crescent': 'Lua crescente',
  'widgets.phaseNames.Waxing Gibbous': 'Gibosa crescente',
  'widgets.placeError': 'Não foi possível carregar o índice de lugares offline.',
  'widgets.placeLabel': 'Local de nascimento',
  'widgets.placePlaceholder': 'Comece a digitar uma cidade…',
  'widgets.planetNames.Jupiter': 'Júpiter',
  'widgets.planetNames.Mars': 'Marte',
  'widgets.planetNames.Mercury': 'Mercúrio',
  'widgets.planetNames.Moon': 'Lua',
  'widgets.planetNames.Neptune': 'Netuno',
  'widgets.planetNames.Pluto': 'Plutão',
  'widgets.planetNames.Saturn': 'Saturno',
  'widgets.planetNames.Sun': 'Sol',
  'widgets.planetNames.Uranus': 'Urano',
  'widgets.planetNames.Venus': 'Vênus',
  'widgets.poweredBy': 'Com tecnologia do Zodiacs.org',
  'widgets.previewTitle': 'Prévia ao vivo',
  'widgets.privacyNote': "O mini mapa é calculado no próprio iframe: a data, a hora e o local de nascimento informados não são enviados a lugar algum, e o mapa nunca é enviado a um servidor. Ao digitar um lugar, porém, o navegador busca em zodiacs.org uma lista de cidades escolhida pela primeira letra digitada: essa solicitação revela apenas uma letra. Carregar o widget também gera uma solicitação a zodiacs.org, como qualquer recurso incorporado, de modo que o navegador revela seu endereço IP e a origem do seu site. São coisas distintas.",
  'widgets.requiresJavaScript': 'O cálculo exige JavaScript, mas o formulário continua privado e não envia nenhum dado de nascimento.',
  'widgets.retrograde': 'Retrógrados: {planets}',
  'widgets.retrogradeAbbreviation': 'Rx',
  'widgets.rising': 'Ascendente',
  'widgets.scriptOption': 'Inserção por script',
  'widgets.signNames.aquarius': 'Aquário',
  'widgets.signNames.aries': 'Áries',
  'widgets.signNames.cancer': 'Câncer',
  'widgets.signNames.capricorn': 'Capricórnio',
  'widgets.signNames.gemini': 'Gêmeos',
  'widgets.signNames.leo': 'Leão',
  'widgets.signNames.libra': 'Libra',
  'widgets.signNames.pisces': 'Peixes',
  'widgets.signNames.sagittarius': 'Sagitário',
  'widgets.signNames.scorpio': 'Escorpião',
  'widgets.signNames.taurus': 'Touro',
  'widgets.signNames.virgo': 'Virgem',
  'widgets.sizeNote': 'Os documentos são independentes e só carregam o cálculo mais pesado depois do envio de um mini mapa.',
  'widgets.skyOption': 'O céu hoje',
  'widgets.skyTitle': 'O céu hoje',
  'widgets.sun': 'Sol',
  'widgets.themeLabel': 'Tema',
  'widgets.timeLabel': 'Hora de nascimento',
  'widgets.widgetError': 'Escolha uma data, uma hora e um local de nascimento completos.',
  'widgets.widgetLabel': 'Widget',
  'widgets.widgetTitleChart': 'Mini mapa astral — Zodiacs.org',
  'widgets.widgetTitleMoon': 'Fase da Lua hoje — Zodiacs.org',
  'widgets.widgetTitleSky': 'O céu hoje — Zodiacs.org',

  // WS8 — wallet natal chart
  'walletChart.addressHelp': 'Formatos aceitos: chave pública Solana base58 de 32 bytes ou endereço Base 0x.',
  'walletChart.addressLabel': 'Endereço Solana ou Base',
  'walletChart.addressPlaceholder': 'Cole um endereço público',
  'walletChart.applicationCategory': 'EntertainmentApplication',
  'walletChart.base': 'Base',
  'walletChart.boundary': 'Cole um endereço. Não há conexão de carteira, assinatura de mensagem, aprovação, construção de transação nem custódia.',
  'walletChart.breadcrumbPage': 'Mapa astral da carteira',
  'walletChart.breadcrumbRegistry': 'Registro Zodiacs',
  'walletChart.calculate': 'Encontrar o mapa da carteira',
  'walletChart.calculating': 'Lendo o histórico público…',
  'walletChart.cardBorn': 'Hora pública do mapa · {time}',
  'walletChart.cardNoBirthplace': 'UTC · só planetas · sem local de nascimento',
  'walletChart.cardOwnerHighlight': 'Sinastria do titular · {ownerBody} {aspect} {walletBody} da carteira · {orb}°',
  'walletChart.cardSymbolic': 'Contexto simbólico · somente consulta · não é aconselhamento financeiro',
  'walletChart.cardTitle': 'Mapa astral da carteira',
  'walletChart.elementBalance': 'Equilíbrio dos elementos dos signos na carteira: {balance}.',
  'walletChart.entertainmentDisclosure': 'Apenas para entretenimento e contexto simbólico.',
  'walletChart.financialDisclosure': 'Isto não constitui aconselhamento financeiro. Nada aqui é solicitação, recomendação ou declaração de valor.',
  'walletChart.historyTooDeep': 'Este endereço excede o limite configurado para o histórico da Solana. É necessário um provedor de dados históricos com um limite maior de páginas; nenhum horário parcial é exibido.',
  'walletChart.intro': 'Uma carteira tem o horário de sua primeira transação registrada, mas não tem local de nascimento. Este instrumento associa esse horário público em UTC apenas a planetas em signos.',
  'walletChart.invalidResponse': 'O provedor de histórico retornou um resultado ilegível. Tente mais tarde.',
  'walletChart.kicker': 'Instrumento do Registro · somente consulta',
  'walletChart.metaDescription': 'Cole um endereço Solana ou Base para mapear o horário on-chain mais antigo disponível como mapa simbólico só de planetas. Sem conexão, assinatura ou transação.',
  'walletChart.metaTitle': 'Mapa da carteira — Registro em modo de consulta | Zodiacs.org',
  'walletChart.noJavaScript': 'JavaScript é necessário para o cálculo astronômico privado no navegador. A consulta do endereço e o cálculo do mapa não são executados sem uma ação sua.',
  'walletChart.notFound': 'Não encontrado no registro oficial do Zodiacs.org.',
  'walletChart.officialHoldingsIntro': 'Uma consulta de saldo somente para leitura encontrou ativos oficiais do Registro para estes signos:',
  'walletChart.officialHoldingsTitle': 'Contexto oficial do Registro',
  'walletChart.ownerCalculating': 'Calculando neste navegador…',
  'walletChart.ownerCancel': 'Limpar comparação privada',
  'walletChart.ownerIntro': 'Se quiser, calcule uma sinastria só de planetas com seu momento de nascimento. O local serve apenas para determinar o fuso horário histórico.',
  'walletChart.ownerMissing': 'Informe uma data de nascimento e escolha um local de nascimento antes de calcular.',
  'walletChart.ownerPlaceHelp': 'O local seleciona o fuso histórico nos dados locais de cidades do site; nenhuma coordenada entra no mapa.',
  'walletChart.ownerPrivacy': 'Sua data, hora e local de nascimento, suas posições planetárias e a sinastria ficam neste navegador. Nunca são enviados ao endpoint do histórico da carteira.',
  'walletChart.ownerStart': 'Comparar com seu mapa',
  'walletChart.ownerSubmit': 'Calcular sinastria privada',
  'walletChart.ownerTimeHelp': 'Se a hora for desconhecida, o motor usa o meio-dia local e não faz afirmações sobre ângulos que mudam rapidamente.',
  'walletChart.ownerTitle': 'Você × sua carteira',
  'walletChart.placementsIntro': 'Estes posicionamentos usam o instante retornado em UTC. Um ascendente e as casas exigiriam um local de nascimento, que uma carteira não tem.',
  'walletChart.placementsTitle': 'Planetas nos signos',
  'walletChart.privacyBody': 'O servidor recebe o endereço público colado e retorna um horário público. Os dados de nascimento opcionais do titular e todo o cálculo astronômico ficam neste dispositivo.',
  'walletChart.privacyTitle': 'O que atravessa o limite',
  'walletChart.readOnlyDisclosure': 'Somente para consulta por definição. Sem custódia, assinaturas, aprovações ou transações.',
  'walletChart.registryBack': 'Voltar ao Registro Zodiacs',
  'walletChart.resultChain': 'Rede',
  'walletChart.resultKicker': 'Comprovante do horário público',
  'walletChart.resultSource': 'Fonte do horário',
  'walletChart.resultTitle': '{address} corresponde a {time}.',
  'walletChart.retrograde': 'retrógrado',
  'walletChart.share': 'Compartilhar este mapa simbólico',
  'walletChart.shareComplete': 'Cartão para compartilhar pronto.',
  'walletChart.shareError': 'Não foi possível criar o cartão para compartilhar neste dispositivo.',
  'walletChart.sharing': 'Preparando o cartão privado…',
  'walletChart.solana': 'Solana',
  'walletChart.sourceBaseExplorer': 'Histórico da conta no explorador da Base',
  'walletChart.sourceBaseRpc': 'RPC de arquivo da Base · primeira atividade de saída',
  'walletChart.sourceBaseRpcCaveat': 'O RPC padrão da Base não indexa transferências de entrada anteriores. Este método alternativo identifica apenas a primeira transação de saída.',
  'walletChart.sourceSolana': 'Histórico paginado de assinaturas da Solana',
  'walletChart.supportedNetworks': 'Redes configuradas: {networks}.',
  'walletChart.synastryBalance': 'Fluidez e atrito aparecem de forma equilibrada nos contatos mais exatos.',
  'walletChart.synastryCharge': 'Os contatos mais exatos tendem mais ao atrito do que à fluidez.',
  'walletChart.synastryContact': '{ownerBody} do seu mapa forma {aspect} com {walletBody} da carteira (orbe de {orb}°).',
  'walletChart.synastryFlow': 'Os contatos mais exatos tendem mais à fluidez do que ao atrito.',
  'walletChart.synastryNoContact': 'Nenhum aspecto principal fica dentro dos orbes padrão do motor.',
  'walletChart.synastryTitle': 'Sinastria simbólica',
  'walletChart.title': 'Um mapa simbólico para um endereço público.',
  'walletChart.unavailable': 'O histórico público da blockchain está temporariamente indisponível. Nenhum status de identidade ou de verificação foi alterado.',
  'walletChart.utcOnly': 'Hora UTC · sem local de nascimento · sem casas nem ângulos',
});
