/**
 * Spanish (es-419) copy for the additive Trust, Growth Infrastructure & SDK
 * Expansion handoff. Only keys whose manifest marks ES as pending belong here.
 */
export const ES_ADDITIONS = Object.freeze({
  // WS1 — trust, disclosure, and archive receipts
  'archive.archivedReceipt': 'Copia archivada',
  'archive.entries.accidental-libra.receipts.mintAddress': 'Publicación de Portnoy que contiene la dirección de acuñación de Libra',
  'archive.entries.accidental-libra.receipts.wrongLibra': 'Portnoy: “Estoy comprando el libra equivocado”',
  'archive.entries.astrologers-arrive.receipts.primary': 'TikTokInvestors: “Llegaron los astrólogos”',
  'archive.entries.astrology-girlies.receipts.primary': 'iJaadee: convocatoria de la comunidad astrológica',
  'archive.entries.horoscopes-to-hodl.receipts.primary': 'Numinous Realm: “Horóscopos para HODL”',
  'archive.entries.oldest-meme.receipts.primary': 'Andrew Kang: “El meme más antiguo de la civilización humana”',
  'archive.entries.onboarding-wave.receipts.primary': 'wantonwallet: registro de incorporación de 1,200 billeteras o más',
  'archive.entries.origin.receipts.registry': 'Registro legible por máquinas publicado',
  'archive.entries.pure-belief.receipts.primary': 'CZ: “Solo un sistema de creencias puro”',
  'archive.entries.zodiac-iwo.receipts.primary': 'inversebrah: publicación con abreviaturas del zodiaco',
  'archive.pendingPrimary': 'Fuente primaria archivada pendiente',
  'archive.receiptsLabel': 'Comprobantes',
  'archive.verifiedRegistry': 'Coincide con el registro oficial',
  'disclosure.aboutLink': 'Leer la declaración del Registro',
  'disclosure.aboutNotice': 'Las certificaciones del operador y de interés económico del Registro, los doce comprobantes de origen fechados y la procedencia del establecimiento están publicados en la página de declaraciones.',
  'disclosure.adviceEvidence': '«Oficial» es solo una clasificación del Registro: significa que una dirección, un contrato, una acuñación o una representación coincide con la lista publicada por el Registro; no implica aprobación gubernamental, verificación de identidad, seguridad, valor, liquidez ni rendimiento futuro. Los avisos contextuales y los términos explican los riesgos de los activos digitales.',
  'disclosure.adviceLabel': 'Consejo financiero e invitación a operar',
  'disclosure.adviceStatement': 'Los registros, el contexto de mercado y Registry Collection no constituyen asesoramiento financiero ni una invitación a comprar, vender o mantener un activo. La Collection es una reflexión simbólica, no una puntuación de la billetera ni una señal de precio, y no requiere ninguna compra.',
  'disclosure.backRegistry': 'Volver al Registro de Zodiacs',
  'disclosure.economicEvidence': 'La certificación de tenencias es una declaración del propio operador, fechada el 2026-08-02 y sin verificación independiente; no enumera activos, billeteras, cantidades ni políticas de bloqueo, consolidación o venta, y las tenencias privadas no se infieren de ninguna billetera. La distribución de titulares se informa mediante instantáneas públicas. A 20 de julio de 2026, la participación de las diez mayores cuentas de token oscilaba entre el 23,0% y el 30,6% en los doce activos, con una mediana del 27,2%. Las cifras pueden cotejarse con las instantáneas publicadas y los registros públicos de la cadena.',
  'disclosure.economicLabel': 'Interés económico',
  'disclosure.economicSnapshotsLink': 'Instantáneas de distribución',
  'disclosure.economicStatement': 'El operador certifica (2026-08-02) que mantiene posiciones en uno o más de los doce activos del Registro y que no recibe compensación por referidos, comisiones de plataforma, liquidez ni mercados por ninguna operación realizada a través del sitio.',
  'disclosure.establishedLabel': 'Establecimiento del Registro',
  'disclosure.establishedPending': 'Procedencia del primer despliegue — pendiente',
  'disclosure.establishedPrefix': 'Est.',
  'disclosure.establishedProvenance': 'Primer comprobante de origen · 2024-07-05',
  'disclosure.evidenceHeading': 'Estado y pruebas',
  'disclosure.intro': 'Esta página separa los hechos respaldados por pruebas públicas de las declaraciones aportadas por el operador, Zodiacs LLC. Una certificación del operador se publica con fecha y etiquetada como certificación; nunca se presenta como verificada de forma independiente.',
  'disclosure.kicker': 'Declaración del Registro',
  'disclosure.linkLabel': 'Declaraciones',
  'disclosure.linkMethodology': 'Metodología',
  'disclosure.linkPrivacy': 'Privacidad',
  'disclosure.linkRegistry': 'Registro legible por máquinas',
  'disclosure.linkSdk': 'Enfoque del SDK',
  'disclosure.linkTerms': 'Términos',
  'disclosure.linkThesis': 'Tesis',
  'disclosure.metaDescription': 'Declaraciones claras sobre operador, interés económico, procedencia, separación, solo lectura, negociación integrada y consejo financiero del Registro de Zodiacs.org.',
  'disclosure.metaTitle': 'Declaraciones — Registro de Zodiacs.org',
  'disclosure.operatorEvidence': 'Basado en una actualización de dominio aportada por el operador y fechada el 2026-08-23; sin verificación independiente. Sustituye solo la afirmación del 2026-08-02 de que el dominio anterior y Astrofolio eran superficies de consumo separadas. La certificación sobre tenencias y ausencia de compensación conserva por separado su fecha del 2026-08-02.',
  'disclosure.operatorLabel': 'Relación del operador',
  'disclosure.operatorRequest': 'Qué significa «certificado por el operador»',
  'disclosure.operatorRequestBody': 'La fila sobre la relación con el operador resume su actualización de dominio fechada. La fila de interés económico conserva su certificación, fechada por separado. Ninguna cuenta con verificación independiente, por eso ambas llevan el distintivo de certificación y no el de verificado. Todas las demás filas enlazan pruebas que cualquiera puede comprobar.',
  'disclosure.operatorStatement': 'Actualización del operador (2026-08-23): el operador controla el dominio zodiacs.org, el repositorio, los despliegues, el contenido del Registro y la experiencia oficial de Astrofolio para consumidores en zodiacs.org/astrofolio. astrofolio.xyz redirige a esa página y no es una superficie de consumo separada. Esta actualización no establece quién controla el despliegue de los tokens ni sus autoridades administrativas, la tesorería, la liquidez o la actividad de mercado.',
  'disclosure.originEvidence': 'Los doce comprobantes llevan fecha del 5 de julio de 2024. Cada uno se localizó inspeccionando las instrucciones en un RPC de archivo y se contrastó con las páginas públicas de Solscan, indexadas de forma independiente; los nombres de los tokens nunca se usaron como prueba. Las representaciones en Base son puentes oficiales y se declaran por separado en la tabla del instrumento de la tesis.',
  'disclosure.originLabel': 'Origen',
  'disclosure.originSlot': 'Comprobante de origen de {sign} — {date}',
  'disclosure.originStatement': 'Cada registro canónico se acredita con su comprobante de origen: la transacción que creó la acuñación nativa del signo en Solana.',
  'disclosure.provenancePendingShort': 'Procedencia del despliegue pendiente',
  'disclosure.provenanceShort': 'Comprobantes de origen — 5 jul 2024',
  'disclosure.readOnlyEvidence': "Zodiacs.org no conecta billeteras, solicita firmas ni envía transacciones. Las consultas de direcciones públicas usan una dirección que pegas. Los enlaces de compra abren servicios independientes con sus propias condiciones y riesgos.",
  'disclosure.tradeLabel': 'Límite de transacciones del catálogo',
  'disclosure.tradeStatement': "Zodiacs.org no conecta billeteras, solicita firmas ni envía transacciones. Las consultas de direcciones públicas usan una dirección que pegas. Los enlaces de compra abren servicios independientes con sus propias condiciones y riesgos.",
  'disclosure.tradeEvidence': "Zodiacs.org no conecta billeteras, solicita firmas ni envía transacciones. Las consultas de direcciones públicas usan una dirección que pegas. Los enlaces de compra abren servicios independientes con sus propias condiciones y riesgos.",
  'disclosure.linkTradeExample': "Guía de direcciones públicas",
  'disclosure.readOnlyLabel': 'Condición de solo lectura',
  'disclosure.readOnlyStatement': "Zodiacs.org no conecta billeteras, solicita firmas ni envía transacciones. Las consultas de direcciones públicas usan una dirección que pegas. Los enlaces de compra abren servicios independientes con sus propias condiciones y riesgos.",
  'disclosure.scope': 'Estas declaraciones se aplican al ala del Registro. Las herramientas astrológicas siguen siendo gratuitas, se calculan en el navegador y se pueden usar sin el Registro.',
  'disclosure.separationEvidence': 'Las calculadoras realizan los cálculos en el navegador y no requieren ninguna interacción con el Registro. Aura mantiene el cálculo de la carta en el dispositivo y solo envía la dirección pública seleccionada a través de su consulta de tenencias.',
  'disclosure.separationLabel': 'Separación',
  'disclosure.separationStatement': 'Las herramientas astrológicas principales siguen siendo gratuitas, no contienen publicidad ni rastreadores entre sitios y pueden usarse sin el Registro. Registry Collection es un enlace opcional que lee en paralelo una carta guardada y el registro público de una billetera; el registro de la billetera no modifica el cálculo de la carta.',
  'disclosure.statementHeading': 'Declaración',
  'disclosure.statusAttested': 'Certificado por el operador — sin verificación independiente',
  'disclosure.statusPending': 'Pendiente de confirmación del operador',
  'disclosure.statusVerified': 'Verificado a partir de materiales publicados',
  'disclosure.tableLabel': 'Declaraciones del Registro y estado de las pruebas',
  'disclosure.title': 'Los hechos, incluidos los que siguen sin resolverse.',
  'registry.establishmentProvenanceLink': 'Procedencia ↗',
  'registry.ogLotAlt': '{sign} — Nº {number} de 12, lote {lot} de XII en el Registro oficial de Zodiacs.org.',
  'registry.verifierNotFoundInline': 'no se encontró en el registro oficial de Zodiacs.org',
  'registry.verifierNotFoundSentence': 'No se encontró en el registro oficial de Zodiacs.org.',

  // WS2b — shared footer
  footerDisclosure: 'Declaración',
  footerWidgets: 'Widgets',

  // WS2c — OG and social-card art
  'og.compatibility.data': 'Lo que funciona · lo que cuesta · lo que lo hace durar',
  'og.compatibility.kicker': 'Compatibilidad',
  'og.compatibility.title': '{a}<br/>y {b}',
  'og.disclosure.alt': 'Declaración del Registro — hechos verificados y confirmaciones pendientes del operador.',
  'og.disclosure.kicker': 'Declaración del Registro',
  'og.disclosure.subtitle': 'Declaraciones sobre operador, interés económico, procedencia, separación y solo lectura.',
  'og.disclosure.title': 'Los hechos, incluidos los que siguen sin resolverse.',
  'og.fallbackAlt': 'Zodiacs.org — cartas natales, guías de signos y herramientas astrológicas gratuitas.',
  'og.horoscope.kicker': 'Horóscopo',
  'og.horoscope.subtitle': 'Lecturas diarias, semanales, mensuales y anuales, con temas claros y un paso útil.',
  'og.pin.horoscope.kicker': 'Horóscopo',
  'og.pin.horoscope.subtitle': 'Lecturas diarias, semanales, mensuales, de amor, de trabajo y anuales para cada signo.',
  'og.pin.horoscope.title': '{sign}, tu pronóstico',
  'og.pin.howTo.kicker': 'Aprende astrología',
  'og.pin.howTo.steps.aspects': '3 · Los aspectos con más peso',
  'og.pin.howTo.steps.bigThree': '1 · Los tres grandes',
  'og.pin.howTo.steps.rooms': '2 · Planetas, casa por casa',
  'og.pin.howTo.steps.weather': '4 · El clima de la carta',
  'og.pin.howTo.title': 'Cómo leer una carta natal.',
  'og.pin.signGuide.kicker': 'Guía del signo',
  'og.placements.kicker': 'Posiciones',
  'og.placements.subtitle': 'Las doce posiciones de {planet}, leídas en detalle.',
  'og.placements.title': '{planet} en<br/>los signos',
  'og.planetNames.jupiter': 'Júpiter',
  'og.planetNames.mars': 'Marte',
  'og.planetNames.mercury': 'Mercurio',
  'og.planetNames.moon': 'Luna',
  'og.planetNames.neptune': 'Neptuno',
  'og.planetNames.pluto': 'Plutón',
  'og.planetNames.saturn': 'Saturno',
  'og.planetNames.sun': 'Sol',
  'og.planetNames.uranus': 'Urano',
  'og.planetNames.venus': 'Venus',
  'og.astrofolio.alt': 'Astrofolio: la colección de doce tokens oficiales del Zodiaco.',
  'og.terminal.alt': 'Terminal: contexto experto de mercado e investigación revisada para los doce tokens oficiales del Zodiaco.',
  'og.wing.data': 'Astrofolio · Registry · Terminal',
  'og.wing.kicker': 'Zodiacs.org',
  'og.wing.subtitle': 'Registros oficiales y contexto público de mercado para los doce signos del Zodiaco.',
  'og.wing.title': 'Los Doce',
  'og.registryLot.kicker': 'El Registro',
  'og.registryLot.numberLine': 'Nº {number} / 12 · Lote {lot} de XII',
  'og.registryLot.subtitle': 'Registro oficial · origen nativo en Solana · representación en Base mediante puente',
  'og.rising.data': 'el ascendente cambia de signo cada dos horas, aproximadamente',
  'og.rising.kicker': 'Signos ascendentes',
  'og.rising.subtitle': 'Cómo te ve el mundo al conocerte y el planeta que guía tu carta.',
  'og.rising.title': '{sign}<br/>ascendente',
  'og.share.subtitle': 'Cartas natales, guías de signos y herramientas astrológicas gratuitas.',
  'og.share.title': 'Toda tu carta, no solo tu signo.',
  'og.signGuide.kicker': 'Guía del signo',
  'og.signNames.aquarius': 'Acuario',
  'og.signNames.aries': 'Aries',
  'og.signNames.cancer': 'Cáncer',
  'og.signNames.capricorn': 'Capricornio',
  'og.signNames.gemini': 'Géminis',
  'og.signNames.leo': 'Leo',
  'og.signNames.libra': 'Libra',
  'og.signNames.pisces': 'Piscis',
  'og.signNames.sagittarius': 'Sagitario',
  'og.signNames.scorpio': 'Escorpio',
  'og.signNames.taurus': 'Tauro',
  'og.signNames.virgo': 'Virgo',
  'og.thesis.alt': 'La creencia es el activo más antiguo — la tesis del Registro de Zodiacs.org.',
  'og.thesis.footer': 'zodiacs.org — El Registro · Revisada en julio de 2026',
  'og.thesis.kicker': 'La Tesis',
  'og.thesis.title': 'La creencia es el activo más antiguo.',
  'og.tools.group-charts.kicker': 'Lectura de grupo gratis',
  'og.tools.group-charts.sub': 'De tres a ocho cartas, cada una con un papel: la chispa, el ancla, la conexión o la unión.',
  'og.tools.group-charts.title': '¿Quién es la chispa y quién la unión?',
  'og.tools.chart-twins.kicker': 'Directorio con fuentes',
  'og.tools.chart-twins.sub': 'Figuras públicas que comparten tus signos solar y lunar verificados.',
  'og.tools.chart-twins.title': 'Tus gemelos astrales',
  'og.tools.big-three.kicker': 'Sol · Luna · Ascendente',
  'og.tools.big-three.sub': 'Tres signos en segundos, con una tarjeta vertical creada en tu navegador.',
  'og.tools.big-three.title': 'Tus tres grandes',
  'og.tools.compatibility-private-invite.kicker': 'Compatibilidad',
  'og.tools.compatibility-private-invite.sub': 'Envía un enlace. Tu amigo agrega su carta y los dos ven cómo conectan.',
  'og.tools.compatibility-private-invite.title': 'Invita a un amigo a comparar',
  'og.tools.sky-calendar.kicker': 'El calendario',
  'og.tools.sky-calendar.sub': 'Lunas nuevas y llenas, picos de eclipses y retrógrados, de 2026 a 2030.',
  'og.tools.sky-calendar.title': 'El cielo, en tu calendario',
  'og.tools.chart-of-the-day.kicker': 'En las noticias',
  'og.tools.chart-of-the-day.sub': 'La carta de una figura pública, con datos de nacimiento con fuentes y sus límites.',
  'og.tools.chart-of-the-day.title': 'Carta del día',
  'og.tools.your-sky-wrapped.kicker': 'Tu año',
  'og.tools.your-sky-wrapped.sub': 'Los contactos de Júpiter y Saturno con tu carta este año, en una tarjeta.',
  'og.tools.your-sky-wrapped.title': 'Tu cielo, en retrospectiva',
  'og.tools.astrologer-kit.kicker': 'Para astrólogos',
  'og.tools.astrologer-kit.sub': 'Rueda, posiciones, aspectos y el comprobante del cálculo en un PDF.',
  'og.tools.astrologer-kit.title': 'Una carta lista para tu cliente',
  'og.tools.ask.kicker': 'Guía de astrología',
  'og.tools.ask.sub': 'Pregunta sobre este sitio, la astrología o tu propia carta.',
  'og.tools.ask.title': 'Guide',
  'og.tools.baby-zodiac.kicker': 'Calculadora gratuita',
  'og.tools.baby-zodiac.sub': 'El Sol casi seguro de la fecha probable, las Lunas posibles de esa semana y lo que depende de la hora.',
  'og.tools.baby-zodiac.title': '¿Qué signo será el bebé?',
  'og.tools.birth-chart.kicker': 'Calculadora gratuita',
  'og.tools.birth-chart.sub': 'Tu Sol, tu Luna, tu ascendente, las casas y los patrones que los conectan.',
  'og.tools.birth-chart.title': 'Tu carta natal',
  'og.tools.birthday.kicker': 'Astrología de cumpleaños',
  'og.tools.birthday.sub': 'Carácter, amor, trabajo, crecimiento y una respuesta exacta sobre la cúspide cuando el año importa.',
  'og.tools.birthday.title': 'Tu cumpleaños, leído de cerca',
  'og.tools.compatibility.kicker': 'Compatibilidad',
  'og.tools.compatibility.sub': 'Sinastría de la carta completa y guías para las 78 combinaciones de signos.',
  'og.tools.compatibility.title': 'Dos cartas, comparadas',
  'og.tools.eclipses.kicker': 'El calendario',
  'og.tools.eclipses.sub': 'Todos los eclipses solares y lunares hasta 2028, con horas exactas del máximo y sus signos.',
  'og.tools.eclipses.title': 'Eclipses con fecha',
  'og.tools.full-moon-calendar.kicker': 'El calendario',
  'og.tools.full-moon-calendar.sub': 'Instantes exactos hasta 2027, con el signo, el grado y el nombre de cada Luna.',
  'og.tools.full-moon-calendar.title': 'Todas las lunas llenas',
  'og.tools.horoscopes.kicker': 'Horóscopos',
  'og.tools.horoscopes.sub': 'Lecturas diarias, semanales, mensuales y anuales, con temas claros y un paso útil.',
  'og.tools.horoscopes.title': 'Los doce signos',
  'og.tools.how-to-read-a-birth-chart.kicker': 'Aprende astrología',
  'og.tools.how-to-read-a-birth-chart.sub': 'Los tres grandes, planetas casa por casa, los aspectos con más peso y luego el clima, en ese orden.',
  'og.tools.how-to-read-a-birth-chart.title': 'Cómo leer una carta natal',
  'og.tools.learn.kicker': 'Aprende astrología',
  'og.tools.learn.sub': 'Los signos, los planetas, las casas y los aspectos, explicados con claridad.',
  'og.tools.learn.title': 'Lee tu carta',
  'og.tools.mercury-retrograde.kicker': 'El calendario',
  'og.tools.mercury-retrograde.sub': 'Todos los periodos hasta 2027, calculados a partir del movimiento real del planeta.',
  'og.tools.mercury-retrograde.title': 'Mercurio retrógrado',
  'og.tools.moon-phase.kicker': 'Calculadora gratuita',
  'og.tools.moon-phase.sub': 'La fase de esta noche y la Luna de cualquier fecha importante para ti.',
  'og.tools.moon-phase.title': 'La Luna, cualquier noche',
  'og.tools.moon-sign.kicker': 'Calculadora gratuita',
  'og.tools.moon-sign.sub': 'Cómo sientes y qué te calma, según tu fecha, hora y lugar de nacimiento.',
  'og.tools.moon-sign.title': 'Tu signo lunar',
  'og.tools.retrogrades.kicker': 'El calendario',
  'og.tools.retrogrades.sub': 'Los ocho planetas, 2026–2027, calculados de estación a estación.',
  'og.tools.retrogrades.title': 'Todas las retrogradaciones',
  'og.tools.rising-sign.kicker': 'Calculadora gratuita',
  'og.tools.rising-sign.sub': 'Cómo te ven los demás al conocerte, según tu hora y lugar de nacimiento.',
  'og.tools.rising-sign.title': 'Tu ascendente',
  'og.tools.saturn-return.kicker': 'Calculadora gratuita',
  'og.tools.saturn-return.sub': 'Las fechas exactas, incluidas todas las pasadas y cada ciclo retrógrado.',
  'og.tools.saturn-return.title': 'Tu retorno de Saturno',
  'og.tools.today.kicker': 'Tu resumen diario',
  'og.tools.today.sub': 'Un foco diario personal, a partir de la última carta guardada en este dispositivo.',
  'og.tools.today.title': 'Hoy, sobre tu carta',
  'og.tools.tools.kicker': 'Herramientas de astrología gratis',
  'og.tools.tools.sub': 'Carta natal, compatibilidad, signo lunar y más, calculados en tu dispositivo.',
  'og.tools.tools.title': 'Calculadoras, sin crear cuenta',
  'og.tools.transits.kicker': 'Seguimiento gratuito',
  'og.tools.transits.sub': 'El cielo actual en aspecto con tu carta natal, a menos de 3° de exactitud.',
  'og.tools.transits.title': 'Tus tránsitos de hoy',

  // WS2d — structured data
  'schema.applicationCategory': 'LifestyleApplication',
  'schema.breadcrumbHome': 'Zodiacs.org',
  'schema.breadcrumbLabels.about': 'Acerca de',
  'schema.breadcrumbLabels.archive': 'Archivo',
  'schema.breadcrumbLabels.baby-zodiac': 'Zodiaco del bebé',
  'schema.breadcrumbLabels.birth-chart': 'Carta natal',
  'schema.breadcrumbLabels.birthday': 'Astrología de cumpleaños',
  'schema.breadcrumbLabels.compatibility': 'Compatibilidad',
  'schema.breadcrumbLabels.disclosure': 'Declaración',
  'schema.breadcrumbLabels.eclipses': 'Eclipses',
  'schema.breadcrumbLabels.es': 'Español',
  'schema.breadcrumbLabels.feeds': 'Canales',
  'schema.breadcrumbLabels.full-moon-calendar': 'Calendario de lunas llenas',
  'schema.breadcrumbLabels.horoscopes': 'Horóscopos',
  'schema.breadcrumbLabels.houses': 'Casas',
  'schema.breadcrumbLabels.learn': 'Aprende astrología',
  'schema.breadcrumbLabels.markets': 'Ruta de Terminal a la plataforma',
  'schema.breadcrumbLabels.mercury-retrograde': 'Mercurio retrógrado',
  'schema.breadcrumbLabels.methodology': 'Metodología',
  'schema.breadcrumbLabels.moon-phase': 'Fase lunar',
  'schema.breadcrumbLabels.moon-sign': 'Signo lunar',
  'schema.breadcrumbLabels.placements': 'Posiciones',
  'schema.breadcrumbLabels.planets': 'Planetas',
  'schema.breadcrumbLabels.privacy': 'Privacidad',
  'schema.breadcrumbLabels.profile': 'Perfil',
  'schema.breadcrumbLabels.registry': 'Registro de Zodiacs',
  'schema.breadcrumbLabels.research': 'Investigación de mercados',
  'schema.breadcrumbLabels.retrogrades': 'Retrógrados',
  'schema.breadcrumbLabels.rising-sign': 'Ascendente',
  'schema.breadcrumbLabels.saturn-return': 'Retorno de Saturno',
  'schema.breadcrumbLabels.sdk': 'SDK',
  'schema.breadcrumbLabels.terms': 'Términos',
  'schema.breadcrumbLabels.astrofolio': 'Astrofolio',
  'schema.breadcrumbLabels.terminal': 'Terminal',
  'schema.breadcrumbLabels.thesis': 'La Tesis',
  'schema.breadcrumbLabels.today': 'Hoy',
  'schema.breadcrumbLabels.tools': 'Herramientas astrológicas',
  'schema.breadcrumbLabels.transits': 'Tránsitos',
  'schema.breadcrumbLabels.widgets': 'Widgets',
  'schema.browserRequirements': 'Requiere un navegador web moderno.',
  'schema.currency': 'USD',
  'schema.freePrice': '0',
  'schema.operatingSystem': 'Cualquier dispositivo con un navegador web moderno',
  'schema.organizationAlternateName': 'Zodiacs.org',
  'schema.organizationName': 'Zodiacs',
  'schema.websiteDescription': 'Cartas natales, signos lunares, compatibilidad, horóscopos y guías de signos gratis, en privado desde tu navegador.',
  'schema.websiteName': 'Zodiacs.org',

  // WS4 — PWA manifest and default-off notification payload
  'push.notification.body': 'Hoy hay una fecha que importa en el cielo: abre tu lectura de hoy.',
  'push.notification.title': 'Aviso del cielo — Zodiacs.org',
  'pwa.manifest.description': 'Cartas natales, compatibilidad y tránsitos: gratis, privados y guardados en tu dispositivo.',
  'pwa.manifest.name': 'Zodiacs — astrología calculada en tu dispositivo',
  'pwa.manifest.shortName': 'Zodiacs',

  // WS5 — programmatic pages and Chinese zodiac
  'chineseZodiac.allAnimals': 'Los doce años animales',
  'chineseZodiac.animalKicker': 'Guía del año animal',
  'chineseZodiac.animals.dog.association': 'Asociado tradicionalmente con la lealtad, la vigilancia y la protección.',
  'chineseZodiac.animals.dog.context': 'El Perro ocupa el undécimo lugar. Como en todas las páginas de esta guía, la asociación describe una tradición interpretativa, no un diagnóstico de personalidad.',
  'chineseZodiac.animals.dog.name': 'Perro',
  'chineseZodiac.animals.dragon.association': 'Asociado tradicionalmente con el poder auspicioso, la vitalidad y la autoridad.',
  'chineseZodiac.animals.dragon.context': 'El Dragón es el animal mítico de la secuencia. Tiene un sentido cultural distinto del dragón adversario habitual en muchas narraciones europeas.',
  'chineseZodiac.animals.dragon.name': 'Dragón',
  'chineseZodiac.animals.goat.association': 'Asociada tradicionalmente con el cuidado, la armonía y el desarrollo creativo.',
  'chineseZodiac.animals.goat.context': 'En las traducciones al inglés aparecen Goat (cabra), Ram (carnero) y Sheep (oveja). El término chino original no impone la misma distinción entre especies que el inglés.',
  'chineseZodiac.animals.goat.name': 'Cabra',
  'chineseZodiac.animals.horse.association': 'Asociado tradicionalmente con el esfuerzo, la valentía, la resiliencia y el movimiento.',
  'chineseZodiac.animals.horse.context': 'El Caballo ocupa el séptimo lugar de la secuencia. El material del Smithsonian sobre el Caballo de Fuego de 2026 destaca el trabajo arduo, la valentía y la resiliencia.',
  'chineseZodiac.animals.horse.name': 'Caballo',
  'chineseZodiac.animals.monkey.association': 'Asociado tradicionalmente con el ingenio, el juego y la adaptación rápida.',
  'chineseZodiac.animals.monkey.context': 'El Mono ocupa el noveno lugar. El folclore y las lecturas populares de personalidad agregan capas más allá del animal calendárico; esas capas no son uniformes en todas las comunidades chinas.',
  'chineseZodiac.animals.monkey.name': 'Mono',
  'chineseZodiac.animals.ox.association': 'Asociado tradicionalmente con el trabajo constante, la resistencia y la responsabilidad práctica.',
  'chineseZodiac.animals.ox.context': 'El buey y el búfalo de agua pueden considerarse la misma categoría zodiacal en el arte chino. La imagen destaca el trabajo sostenido, no la velocidad.',
  'chineseZodiac.animals.ox.name': 'Buey',
  'chineseZodiac.animals.pig.association': 'Asociado tradicionalmente con la abundancia, la generosidad y la culminación.',
  'chineseZodiac.animals.pig.context': 'El Cerdo cierra la secuencia de animales antes de que vuelva a empezar con la Rata. En las referencias en inglés aparecen tanto Boar (jabalí) como Pig (cerdo).',
  'chineseZodiac.animals.pig.name': 'Cerdo',
  'chineseZodiac.animals.rabbit.association': 'Asociado tradicionalmente con la vigilancia, la gracia y el movimiento cuidadoso.',
  'chineseZodiac.animals.rabbit.context': 'Las fuentes en inglés pueden usar Rabbit (conejo) o Hare (liebre). Algunas tradiciones zodiacales regionales nombran a otro animal, por lo que esta guía se limita específicamente al ciclo chino.',
  'chineseZodiac.animals.rabbit.name': 'Conejo',
  'chineseZodiac.animals.rat.association': 'Asociada tradicionalmente con la atención, la adaptabilidad y la capacidad de abrirse paso en circunstancias limitadas.',
  'chineseZodiac.animals.rat.context': 'La Rata abre la secuencia de doce años. Los resúmenes modernos de personalidad suelen describirla como ingeniosa; esa es una asociación cultural, no un rasgo medido.',
  'chineseZodiac.animals.rat.name': 'Rata',
  'chineseZodiac.animals.rooster.association': 'Asociado tradicionalmente con la diligencia, el sentido del tiempo y la laboriosidad.',
  'chineseZodiac.animals.rooster.context': 'The Met señala que el despertar temprano del gallo da origen a sus asociaciones con la diligencia y el trabajo, y también documenta su largo uso como motivo artístico auspicioso.',
  'chineseZodiac.animals.rooster.name': 'Gallo',
  'chineseZodiac.animals.snake.association': 'Asociada tradicionalmente con la percepción, la reserva y la transformación.',
  'chineseZodiac.animals.snake.context': 'La Serpiente sigue al Dragón en el ciclo. Los rasgos interpretativos varían según la fuente, la familia y la región; la posición en el calendario es el dato estable.',
  'chineseZodiac.animals.snake.name': 'Serpiente',
  'chineseZodiac.animals.tiger.association': 'Asociado tradicionalmente con el valor, la fuerza y la protección.',
  'chineseZodiac.animals.tiger.context': 'El Tigre tiene un carácter tanto protector como audaz en la cultura visual china. Las listas breves de personalidad solo recogen uno de los usos del símbolo.',
  'chineseZodiac.animals.tiger.name': 'Tigre',
  'chineseZodiac.associationLabel': 'Asociación tradicional',
  'chineseZodiac.boundaryBody': 'Un año animal no cambia el 1 de enero. Si una fecha de nacimiento cae en enero o a principios de febrero, revisa la fecha del Año Nuevo Lunar de ese año calendario antes de elegir un animal. Las fechas también varían entre las tradiciones asiáticas, y no todas las comunidades usan el mismo zodiaco.',
  'chineseZodiac.boundaryTitle': 'El año comienza con el Año Nuevo Lunar',
  'chineseZodiac.branchLabel': 'Rama Terrestre',
  'chineseZodiac.chartLink': 'Calcular una carta natal tropical occidental',
  'chineseZodiac.historyBody': 'Los doce animales se emparejan con las doce Ramas Terrestres. Las pruebas históricas sitúan la asociación entre animales y calendario en China en el siglo III a. e. c., y muestran que ya estaba firmemente establecida en el siglo I. Las ramas también se combinan con diez Troncos Celestiales en un ciclo de sesenta combinaciones.',
  'chineseZodiac.historyTitle': 'Lo que registra el ciclo',
  'chineseZodiac.hubIntro': 'Una introducción cuidadosa al zodiaco chino: su secuencia de animales, las tablas de años, el marco histórico y el límite anual que no cae el 1 de enero.',
  'chineseZodiac.hubTitle': 'El ciclo animal de doce años.',
  'chineseZodiac.iconRailNote': 'Los discos de colores son la marca visual de los signos occidentales de Zodiacs.org. No sustituyen a los animales del zodiaco chino ni se corresponden con ellos.',
  'chineseZodiac.itemLink': 'Leer el Año del {animal}',
  'chineseZodiac.kicker': 'Zodiaco chino',
  'chineseZodiac.learnLabel': 'Aprende',
  'chineseZodiac.limitsBody': 'El animal anual es una capa del calendario. Una lectura más completa de la astrología china también puede considerar el Tronco Celestial y el elemento, el mes, el día y la hora. Un animal anual por sí solo no puede determinar una personalidad ni predecir un resultado.',
  'chineseZodiac.limitsTitle': 'Lo que esto te dice y lo que no',
  'chineseZodiac.metaAnimalDescription': 'Año del {animal}: años del ciclo, Rama Terrestre {branch} ({pinyin}), asociaciones tradicionales y límite del Año Nuevo Lunar.',
  'chineseZodiac.metaAnimalTitle': 'Año del {animal} — años del zodiaco chino | Zodiacs.org',
  'chineseZodiac.metaHubTitle': 'Zodiaco chino — los doce años animales | Zodiacs.org',
  'chineseZodiac.next': 'Animal siguiente',
  'chineseZodiac.numberLabel': 'Nº {number}',
  'chineseZodiac.positionValue': '{position} de 12',
  'chineseZodiac.previous': 'Animal anterior',
  'chineseZodiac.separateBody': 'La astrología tropical occidental sitúa los planetas frente a doce sectores de la eclíptica y usa un momento de nacimiento exacto. Estas páginas del zodiaco chino parten de un año del calendario lunisolar y su rama animal. Los dos sistemas pueden estudiarse uno junto al otro, pero ninguno se traduce en el otro.',
  'chineseZodiac.separateTitle': 'Un sistema distinto de la astrología tropical occidental',
  'chineseZodiac.sequenceLabel': 'Posición en la secuencia',
  'chineseZodiac.sequenceTitle': 'Los doce animales, en orden',
  'chineseZodiac.siteName': 'Zodiacs.org',
  'chineseZodiac.sourceMet': 'The Met — el calendario animal de doce años y su historia',
  'chineseZodiac.sourceMetBulletin': 'The Met Bulletin — animales, ramas y el ciclo de sesenta combinaciones',
  'chineseZodiac.sourceMetHub': 'The Met — historia del ciclo calendárico de doce animales',
  'chineseZodiac.sourceSmithsonian': 'Smithsonian — secuencia del zodiaco chino y contexto del Año Nuevo Lunar',
  'chineseZodiac.sourceSmithsonianHub': 'Smithsonian — Año Nuevo Lunar y secuencia del zodiaco',
  'chineseZodiac.sourceTitle': 'Fuentes museísticas y culturales',
  'chineseZodiac.westernLink': 'Leer cómo funcionan las fechas del zodiaco tropical occidental',
  'chineseZodiac.yearOf': 'Año del {animal}',
  'chineseZodiac.yearsBoundary': 'Estas etiquetas nombran el año lunisolar que comienza durante el año gregoriano indicado. Los nacimientos de enero y principios de febrero pueden pertenecer al animal anterior.',
  'chineseZodiac.yearsLabel': 'Años del ciclo',
  'chineseZodiac.yearsTitle': 'Años recientes y próximos del ciclo',
  'programmatic.compatibilityPrefillCta': 'Abrir la calculadora con {a} y {b} ya cargados',

  // WS6 — widgets
  'widgets.accentLabel': 'Color de acento',
  'widgets.backlinkNote': 'El enlace “Con tecnología de Zodiacs.org” forma parte de todos los widgets y no se puede quitar.',
  'widgets.changePlace': 'Cambiar lugar de nacimiento',
  'widgets.chartError': 'No se pudo calcular la carta en este navegador.',
  'widgets.chartIntro': 'Sol, Luna y ascendente, calculados aquí de forma privada.',
  'widgets.chartOption': 'Minicarta natal',
  'widgets.chartPrivacy': 'Se calcula en este dispositivo. Nada de lo que ingreses aquí se envía a una API de cartas astrales.',
  'widgets.chartTitle': 'Minicarta natal',
  'widgets.codeLabel': 'Código de inserción',
  'widgets.computeAction': 'Encontrar los tres grandes',
  'widgets.computing': 'Calculando…',
  'widgets.copiedAction': 'Copiado',
  'widgets.copyAction': 'Copiar código de inserción',
  'widgets.darkOption': 'Oscuro',
  'widgets.dateLabel': 'Fecha de nacimiento',
  'widgets.generatorTitle': 'Crear un widget',
  'widgets.iframeOption': 'iframe aislado',
  'widgets.illumination': '{percent}% iluminada',
  'widgets.lightOption': 'Claro',
  'widgets.modeLabel': 'Modo de inserción',
  'widgets.moon': 'Luna',
  'widgets.moonOption': 'Fase lunar de hoy',
  'widgets.moonSign': 'Luna en {sign}',
  'widgets.moonTitle': 'Fase lunar de hoy',
  'widgets.noPlaces': 'No se encontraron lugares',
  'widgets.noRetrograde': 'Ningún planeta retrógrado',
  'widgets.pageIntro': 'Tres widgets astrológicos pequeños y privados para tu sitio. El iframe es el modo principal; el modo script monta el mismo documento aislado. Cada widget conserva el crédito de Zodiacs.org.',
  'widgets.pageKicker': 'Widgets',
  'widgets.pageMetaDescription': 'Inserta una fase lunar, el cielo actual o una minicarta natal privada en cualquier sitio. Modos iframe aislado y script, gratis y con el crédito de Zodiacs.org.',
  'widgets.pageMetaTitle': 'Widgets astrológicos gratis — Luna, cielo y carta | Zodiacs.org',
  'widgets.pageTitle': 'El cielo, en tu sitio.',
  'widgets.phaseNames.First Quarter': 'Cuarto creciente',
  'widgets.phaseNames.Full Moon': 'Luna llena',
  'widgets.phaseNames.Last Quarter': 'Cuarto menguante',
  'widgets.phaseNames.New Moon': 'Luna nueva',
  'widgets.phaseNames.Waning Crescent': 'Luna menguante',
  'widgets.phaseNames.Waning Gibbous': 'Gibosa menguante',
  'widgets.phaseNames.Waxing Crescent': 'Luna creciente',
  'widgets.phaseNames.Waxing Gibbous': 'Gibosa creciente',
  'widgets.placeError': 'No se pudo cargar el índice de lugares sin conexión.',
  'widgets.placeLabel': 'Lugar de nacimiento',
  'widgets.placePlaceholder': 'Empieza a escribir una ciudad…',
  'widgets.planetNames.Jupiter': 'Júpiter',
  'widgets.planetNames.Mars': 'Marte',
  'widgets.planetNames.Mercury': 'Mercurio',
  'widgets.planetNames.Moon': 'Luna',
  'widgets.planetNames.Neptune': 'Neptuno',
  'widgets.planetNames.Pluto': 'Plutón',
  'widgets.planetNames.Saturn': 'Saturno',
  'widgets.planetNames.Sun': 'Sol',
  'widgets.planetNames.Uranus': 'Urano',
  'widgets.planetNames.Venus': 'Venus',
  'widgets.poweredBy': 'Con tecnología de Zodiacs.org',
  'widgets.previewTitle': 'Vista previa en vivo',
  'widgets.privacyNote': "La minicarta se calcula dentro de su iframe: la fecha, la hora y el lugar de nacimiento que ingresa la persona no se envían a ningún sitio, y la carta nunca se sube. Al escribir un lugar, se obtiene de zodiacs.org una lista de ciudades elegida según la primera letra escrita, por lo que esa solicitud revela una sola letra y nada más. Cargar el widget también genera una solicitud a zodiacs.org, como cualquier recurso incrustado, de modo que el navegador revela su dirección IP y el origen de tu sitio. Son cosas distintas.",
  'widgets.requiresJavaScript': 'El cálculo requiere JavaScript, pero el formulario sigue siendo privado y no envía ningún dato de nacimiento.',
  'widgets.retrograde': 'Retrógrados: {planets}',
  'widgets.retrogradeAbbreviation': 'Rx',
  'widgets.rising': 'Ascendente',
  'widgets.scriptOption': 'Montaje con script',
  'widgets.signNames.aquarius': 'Acuario',
  'widgets.signNames.aries': 'Aries',
  'widgets.signNames.cancer': 'Cáncer',
  'widgets.signNames.capricorn': 'Capricornio',
  'widgets.signNames.gemini': 'Géminis',
  'widgets.signNames.leo': 'Leo',
  'widgets.signNames.libra': 'Libra',
  'widgets.signNames.pisces': 'Piscis',
  'widgets.signNames.sagittarius': 'Sagitario',
  'widgets.signNames.scorpio': 'Escorpio',
  'widgets.signNames.taurus': 'Tauro',
  'widgets.signNames.virgo': 'Virgo',
  'widgets.sizeNote': 'Cada widget es un documento independiente; el cálculo más pesado se carga solo al enviar el formulario de la minicarta.',
  'widgets.skyOption': 'El cielo de hoy',
  'widgets.skyTitle': 'El cielo de hoy',
  'widgets.sun': 'Sol',
  'widgets.themeLabel': 'Tema',
  'widgets.timeLabel': 'Hora de nacimiento',
  'widgets.widgetError': 'Completa la fecha, la hora y el lugar de nacimiento.',
  'widgets.widgetLabel': 'Widget',
  'widgets.widgetTitleChart': 'Minicarta natal — Zodiacs.org',
  'widgets.widgetTitleMoon': 'Fase lunar de hoy — Zodiacs.org',
  'widgets.widgetTitleSky': 'El cielo de hoy — Zodiacs.org',

  // WS8 — wallet natal chart
  'walletChart.addressHelp': 'Formatos aceptados: clave pública base58 de Solana de 32 bytes o dirección 0x de Base.',
  'walletChart.addressLabel': 'Dirección de Solana o Base',
  'walletChart.addressPlaceholder': 'Pega una dirección pública',
  'walletChart.applicationCategory': 'EntertainmentApplication',
  'walletChart.base': 'Base',
  'walletChart.boundary': 'Pega una dirección. No hay conexión de billetera, firma de mensajes, aprobaciones, creación de transacciones ni custodia.',
  'walletChart.breadcrumbPage': 'Carta natal de la billetera',
  'walletChart.breadcrumbRegistry': 'Registro de Zodiacs',
  'walletChart.calculate': 'Calcular la carta de la billetera',
  'walletChart.calculating': 'Leyendo el historial público…',
  'walletChart.cardBorn': 'Hora de la carta pública · {time}',
  'walletChart.cardNoBirthplace': 'UTC · solo planetas · sin lugar de nacimiento',
  'walletChart.cardOwnerHighlight': 'Sinastría del titular · {ownerBody} {aspect} {walletBody} de la billetera · {orb}°',
  'walletChart.cardSymbolic': 'Contexto simbólico · solo lectura · no es consejo financiero',
  'walletChart.cardTitle': 'Carta natal de la billetera',
  'walletChart.elementBalance': 'Equilibrio de elementos en los signos en tenencia: {balance}.',
  'walletChart.entertainmentDisclosure': 'Solo para entretenimiento y contexto simbólico.',
  'walletChart.financialDisclosure': 'No es consejo financiero. Nada de esto constituye una invitación a operar, una recomendación ni una afirmación sobre el valor.',
  'walletChart.historyTooDeep': 'Esta dirección supera el límite configurado del historial de Solana. Se requiere un proveedor de archivo con un límite de páginas mayor; no se muestra ninguna marca temporal parcial.',
  'walletChart.intro': 'Una billetera tiene una primera hora de transacción registrada, pero no un lugar de nacimiento. Este instrumento relaciona esa marca temporal UTC pública únicamente con planetas en signos.',
  'walletChart.invalidResponse': 'El proveedor del historial devolvió un resultado ilegible. Inténtalo más tarde.',
  'walletChart.kicker': 'Instrumento del Registro · solo lectura',
  'walletChart.metaDescription': 'Pega una dirección de Solana o Base y convierte su primera marca temporal admitida en cadena en una carta simbólica de planetas. Sin conexión, firma ni transacción.',
  'walletChart.metaTitle': 'Carta natal de billetera — Registro de solo lectura | Zodiacs.org',
  'walletChart.noJavaScript': 'JavaScript es necesario para el cálculo astronómico privado en el navegador. La consulta de la dirección y el cálculo de la carta no se ejecutan sin que tú los inicies.',
  'walletChart.notFound': 'No se encontró en el registro oficial de Zodiacs.org.',
  'walletChart.officialHoldingsIntro': 'Una consulta de saldo de solo lectura encontró activos oficiales del Registro para estos signos:',
  'walletChart.officialHoldingsTitle': 'Contexto del Registro oficial',
  'walletChart.ownerCalculating': 'Calculando en este navegador…',
  'walletChart.ownerCancel': 'Borrar comparación privada',
  'walletChart.ownerIntro': 'Si quieres, calcula una sinastría solo con planetas respecto a tu momento de nacimiento. El lugar se usa únicamente para determinar la hora local histórica.',
  'walletChart.ownerMissing': 'Ingresa una fecha de nacimiento y elige un lugar de nacimiento antes de calcular.',
  'walletChart.ownerPlaceHelp': 'El lugar selecciona la zona horaria histórica a partir de los datos locales de ciudades del sitio; ninguna coordenada se incorpora a la carta.',
  'walletChart.ownerPrivacy': 'Tu fecha, hora y lugar de nacimiento, tus posiciones planetarias y la sinastría permanecen en este navegador. Nunca se envían al endpoint del historial de la billetera.',
  'walletChart.ownerStart': 'Comparar con tu carta',
  'walletChart.ownerSubmit': 'Calcular sinastría privada',
  'walletChart.ownerTimeHelp': 'Si no conoces la hora, el motor usa el mediodía local y omite cualquier afirmación sobre los ángulos de movimiento rápido.',
  'walletChart.ownerTitle': 'Tú × tu billetera',
  'walletChart.placementsIntro': 'Estas posiciones usan el instante UTC devuelto. Para calcular un ascendente y casas haría falta un lugar de nacimiento, que una billetera no tiene.',
  'walletChart.placementsTitle': 'Planetas en signos',
  'walletChart.privacyBody': 'El servidor recibe la dirección pública que pegaste y devuelve una marca temporal pública. Los datos de nacimiento opcionales del titular y todos los cálculos astronómicos permanecen en este dispositivo.',
  'walletChart.privacyTitle': 'Qué datos cruzan el límite',
  'walletChart.readOnlyDisclosure': 'Solo lectura por diseño. Sin custodia, firmas, aprobaciones ni transacciones.',
  'walletChart.registryBack': 'Volver al Registro de Zodiacs',
  'walletChart.resultChain': 'Red',
  'walletChart.resultKicker': 'Comprobante de marca temporal pública',
  'walletChart.resultSource': 'Fuente de la marca temporal',
  'walletChart.resultTitle': '{address} corresponde a {time}.',
  'walletChart.retrograde': 'retrógrado',
  'walletChart.share': 'Compartir esta carta simbólica',
  'walletChart.shareComplete': 'La tarjeta para compartir está lista.',
  'walletChart.shareError': 'No se pudo crear la tarjeta para compartir en este dispositivo.',
  'walletChart.sharing': 'Preparando la tarjeta privada…',
  'walletChart.solana': 'Solana',
  'walletChart.sourceBaseExplorer': 'Historial de la cuenta en el explorador de Base',
  'walletChart.sourceBaseRpc': 'RPC de archivo de Base · primera actividad saliente',
  'walletChart.sourceBaseRpcCaveat': 'El RPC estándar de Base no puede indexar transferencias entrantes anteriores. Esta alternativa solo identifica la primera transacción saliente.',
  'walletChart.sourceSolana': 'Historial paginado de firmas de Solana',
  'walletChart.supportedNetworks': 'Redes configuradas: {networks}.',
  'walletChart.synastryBalance': 'La fluidez y la fricción están representadas por igual en los contactos de orbe estrecho.',
  'walletChart.synastryCharge': 'Los contactos de orbe estrecho se inclinan más hacia la fricción que hacia la fluidez.',
  'walletChart.synastryContact': 'Tu {ownerBody} está en {aspect} con {walletBody} de la billetera (orbe de {orb}°).',
  'walletChart.synastryFlow': 'Los contactos de orbe estrecho se inclinan más hacia la fluidez que hacia la fricción.',
  'walletChart.synastryNoContact': 'Ningún aspecto mayor cae dentro de los orbes estándar del motor.',
  'walletChart.synastryTitle': 'Sinastría simbólica',
  'walletChart.title': 'Una carta simbólica para una dirección pública.',
  'walletChart.unavailable': 'El historial público de la cadena no está disponible temporalmente. No ha cambiado ningún estado de identidad ni de verificación.',
  'walletChart.utcOnly': 'Hora UTC · sin lugar de nacimiento · sin casas ni ángulos',
});
