/**
 * Italian copy for the additive Trust/Growth handoff.
 *
 * This flat sidecar intentionally contains only keys whose IT locale is
 * marked pending in i18n-additions.md. Shared wiring remains in the owning
 * domain catalogues.
 */
export const IT_ADDITIONS = Object.freeze({
  // WS1 — trust, disclosure, and archive receipts
  'archive.archivedReceipt': 'Copia archiviata',
  'archive.entries.accidental-libra.receipts.mintAddress': 'Post di Portnoy contenente l’indirizzo di mint di Libra',
  'archive.entries.accidental-libra.receipts.wrongLibra': 'Portnoy: “Sto comprando la Libra sbagliata”',
  'archive.entries.astrologers-arrive.receipts.primary': 'TikTokInvestors: “Gli astrologi sono arrivati”',
  'archive.entries.astrology-girlies.receipts.primary': 'iJaadee: chiamata della comunità astrologica',
  'archive.entries.horoscopes-to-hodl.receipts.primary': 'Numinous Realm: “Oroscopi da HODL”',
  'archive.entries.oldest-meme.receipts.primary': 'Andrew Kang: “Il meme più antico della civiltà umana”',
  'archive.entries.onboarding-wave.receipts.primary': 'wantonwallet: registro dell’ingresso di oltre 1.200 wallet',
  'archive.entries.origin.receipts.registry': 'Registro leggibile dalle macchine pubblicato',
  'archive.entries.pure-belief.receipts.primary': 'CZ: “Solo un puro sistema di credenze”',
  'archive.entries.zodiac-iwo.receipts.primary': 'inversebrah: post con abbreviazioni dello zodiaco',
  'archive.pendingPrimary': 'Copia archiviata della fonte primaria ancora in attesa',
  'archive.receiptsLabel': 'Riscontri',
  'archive.verifiedRegistry': 'Corrisponde alla scheda ufficiale',
  'disclosure.aboutLink': 'Leggi l’informativa del Registro',
  'disclosure.aboutNotice': 'Le attestazioni dell’operatore e dell’interesse economico del Registro, le dodici ricevute di origine datate e la provenienza dell’istituzione sono pubblicate nella pagina dell’informativa.',
  'disclosure.adviceEvidence': '“Ufficiale” è soltanto una classificazione del Registro: significa che un indirizzo, contratto, mint o rappresentazione corrisponde all’elenco pubblicato dal Registro, non che esistano approvazione governativa, verifica dell’identità, sicurezza, valore, liquidità o rendimenti futuri. Gli avvisi contestuali e i termini descrivono i rischi degli asset digitali.',
  'disclosure.adviceLabel': 'Consulenza finanziaria e sollecitazione',
  'disclosure.adviceStatement': 'Le voci del Registro, il contesto di mercato e Registry Collection non costituiscono consulenza finanziaria né una sollecitazione ad acquistare, vendere o detenere un asset. La Collection è una riflessione simbolica, non un punteggio del wallet né un segnale di prezzo, e non richiede alcun acquisto.',
  'disclosure.backRegistry': 'Torna al Registro Zodiacs',
  'disclosure.economicEvidence': 'L’attestazione sulle posizioni è una dichiarazione dell’operatore stesso, datata 2026-08-02 e senza verifica indipendente; non elenca asset, portafogli, importi né politiche di lock-up, maturazione o dismissione, e le posizioni private non vengono dedotte da alcun portafoglio. La distribuzione dei detentori è pubblicata tramite istantanee pubbliche. Al 20 luglio 2026 la quota dei dieci maggiori account di token andava dal 23,0% al 30,6% sui dodici asset, con una mediana del 27,2%. Le cifre sono verificabili nelle istantanee pubblicate e nei registri pubblici della catena.',
  'disclosure.economicLabel': 'Interesse economico',
  'disclosure.economicSnapshotsLink': 'Istantanee di distribuzione',
  'disclosure.economicStatement': 'L’operatore attesta (2026-08-02) di detenere posizioni in uno o più dei dodici asset del Registro e di non ricevere alcuna remunerazione da referral, commissioni di piattaforma, liquidità o marketplace per alcuna operazione effettuata tramite il sito.',
  'disclosure.establishedLabel': 'Istituzione del Registro',
  'disclosure.establishedPending': 'Provenienza del deploy più antico — in attesa',
  'disclosure.establishedPrefix': 'Fond.',
  'disclosure.establishedProvenance': 'Prima ricevuta di origine · 2024-07-05',
  'disclosure.evidenceHeading': 'Stato e prove',
  'disclosure.intro': 'Questa pagina separa i fatti sostenuti da prove pubbliche dalle dichiarazioni fornite dall’operatore, Zodiacs LLC. Un’attestazione dell’operatore è datata ed etichettata come tale; non viene mai presentata come verificata in modo indipendente.',
  'disclosure.kicker': 'Informativa del Registro',
  'disclosure.linkLabel': 'Informativa',
  'disclosure.linkMethodology': 'Metodologia',
  'disclosure.linkPrivacy': 'Privacy',
  'disclosure.linkRegistry': 'Registro leggibile dalle macchine',
  'disclosure.linkSdk': 'Assetto dell’SDK',
  'disclosure.linkTerms': 'Termini',
  'disclosure.linkThesis': 'Tesi',
  'disclosure.metaDescription': 'Informativa chiara su operatore, interessi economici, provenienza, separazione, sola lettura, negoziazione integrata e consulenza finanziaria per il Registro Zodiacs.org.',
  'disclosure.metaTitle': 'Informativa — Registro Zodiacs.org',
  'disclosure.operatorEvidence': 'Basato su un aggiornamento del dominio fornito dall’operatore e datato 2026-08-23; senza verifica indipendente. Sostituisce soltanto l’affermazione del 2026-08-02 secondo cui il precedente dominio e Astrofolio erano superfici consumer separate. L’attestazione sulle posizioni e sull’assenza di compensi conserva separatamente la data 2026-08-02.',
  'disclosure.operatorLabel': 'Rapporto con l’operatore',
  'disclosure.operatorRequest': 'Cosa significa «attestato dall’operatore»',
  'disclosure.operatorRequestBody': 'La riga sul rapporto con l’operatore riassume il suo aggiornamento del dominio, con data. La riga sull’interesse economico conserva l’attestazione dell’operatore, datata separatamente. Nessuna delle due è verificata in modo indipendente; entrambe portano quindi il contrassegno di attestazione e non quello di verificato. Tutte le altre righe rimandano a prove che chiunque può controllare.',
  'disclosure.operatorStatement': 'Aggiornamento dell’operatore (2026-08-23): l’operatore controlla il dominio zodiacs.org, il repository, i deploy, i contenuti del Registro e l’esperienza consumer ufficiale di Astrofolio su zodiacs.org/astrofolio. astrofolio.xyz reindirizza a quella pagina e non è una superficie consumer separata. Questo aggiornamento non stabilisce chi controlli il deployment o le autorità amministrative dei token, la tesoreria, la liquidità o l’attività di mercato.',
  'disclosure.originEvidence': 'Le dodici ricevute sono datate 5 luglio 2024. Ognuna è stata individuata ispezionando le istruzioni su un RPC di archivio e riscontrata con le pagine pubbliche di Solscan, indicizzate in modo indipendente; i nomi dei token non sono mai stati usati come prova. Le rappresentazioni su Base sono ponti ufficiali, dichiarati separatamente nella tabella dello strumento della tesi.',
  'disclosure.originLabel': 'Origine',
  'disclosure.originSlot': 'Ricevuta di origine di {sign} — {date}',
  'disclosure.originStatement': 'Ogni record canonico è provato dalla sua ricevuta di origine: la transazione che ha creato il mint nativo del segno su Solana.',
  'disclosure.provenancePendingShort': 'Provenienza del deploy in attesa',
  'disclosure.provenanceShort': 'Ricevute di origine — 5 lug 2024',
  'disclosure.readOnlyEvidence': "Zodiacs.org non collega wallet, richiede firme o invia transazioni. Le ricerche di indirizzi pubblici usano un indirizzo che incolli. I link di acquisto aprono servizi indipendenti con le proprie condizioni e i propri rischi.",
  'disclosure.tradeLabel': 'Limite delle transazioni nel catalogo',
  'disclosure.tradeStatement': "Zodiacs.org non collega wallet, richiede firme o invia transazioni. Le ricerche di indirizzi pubblici usano un indirizzo che incolli. I link di acquisto aprono servizi indipendenti con le proprie condizioni e i propri rischi.",
  'disclosure.tradeEvidence': "Zodiacs.org non collega wallet, richiede firme o invia transazioni. Le ricerche di indirizzi pubblici usano un indirizzo che incolli. I link di acquisto aprono servizi indipendenti con le proprie condizioni e i propri rischi.",
  'disclosure.linkTradeExample': "Guida agli indirizzi pubblici",
  'disclosure.readOnlyLabel': 'Assetto di sola lettura',
  'disclosure.readOnlyStatement': "Zodiacs.org non collega wallet, richiede firme o invia transazioni. Le ricerche di indirizzi pubblici usano un indirizzo che incolli. I link di acquisto aprono servizi indipendenti con le proprie condizioni e i propri rischi.",
  'disclosure.scope': 'Questa informativa riguarda l’Ala della collezione. Gli strumenti astrologici restano gratuiti, calcolati nel browser e utilizzabili senza il Registro.',
  'disclosure.separationEvidence': 'I calcolatori eseguono i calcoli nel browser e non richiedono interazioni con il Registro. Aura mantiene sul dispositivo il calcolo del tema e invia solo l’indirizzo pubblico selezionato tramite la propria consultazione degli asset.',
  'disclosure.separationLabel': 'Separazione',
  'disclosure.separationStatement': 'I principali strumenti astrologici restano gratuiti, non contengono pubblicità né sistemi di tracciamento tra siti e possono essere usati senza il Registro. Registry Collection è un collegamento facoltativo che legge affiancati un tema salvato e il registro pubblico di un wallet; il registro del wallet non modifica il calcolo del tema.',
  'disclosure.statementHeading': 'Dichiarazione',
  'disclosure.statusAttested': 'Attestato dall’operatore — senza verifica indipendente',
  'disclosure.statusPending': 'In attesa della conferma dell’operatore',
  'disclosure.statusVerified': 'Verificato dai materiali pubblicati',
  'disclosure.tableLabel': 'Informativa del Registro e stato delle prove',
  'disclosure.title': 'I fatti, compresi quelli ancora irrisolti.',
  'registry.establishmentProvenanceLink': 'Provenienza ↗',
  'registry.ogLotAlt': '{sign} — Nº {number} di 12, lotto {lot} di XII nel Registro ufficiale Zodiacs.org.',
  'registry.verifierNotFoundInline': 'non presente nel registro ufficiale Zodiacs.org',
  'registry.verifierNotFoundSentence': 'Non presente nel registro ufficiale Zodiacs.org.',

  // WS2b — email capture and shared footer
  'emailCaptureChangeSign': 'Cambia',
  'emailCaptureCopy': 'Una previsione settimanale per il tuo segno. Gratuita, puoi annullare l’iscrizione quando vuoi.',
  'emailCaptureEmailLabel': 'Indirizzo e-mail',
  'emailCaptureEmailPlaceholder': 'tu@esempio.it',
  'emailCaptureError': 'Non è stato possibile avviare l’iscrizione. Riprova.',
  'emailCaptureErrorTitle': 'Iscrizione non disponibile',
  'emailCaptureHoneypot': 'Lascia vuoto questo campo',
  'emailCaptureKicker': 'Previsione settimanale gratuita',
  'emailCaptureNoSign': 'Salta il segno',
  'emailCapturePersonalTitle': 'La tua settimana da {sign}.',
  'emailCapturePrivacy': 'Conserviamo solo il tuo indirizzo e-mail e il segno scelto — mai i tuoi dati di nascita.',
  'emailCaptureSignLegend': 'Il tuo segno solare (facoltativo)',
  'emailCaptureSubmit': 'Invia la mia settimana',
  'emailCaptureSubmitting': 'Iscrizione in corso…',
  'emailCaptureSuccess': 'Controlla la posta per confermare l’iscrizione.',
  'emailCaptureTitle': 'La settimana che ti aspetta.',
  'emailCaptureUsingSign': 'Segno solare usato: {sign}',
  'emailConfirmAction': 'Conferma l’iscrizione',
  'emailConfirmBody': 'Conferma questa iscrizione per iniziare a ricevere la previsione settimanale gratuita. Fino ad allora non sarà attiva alcuna iscrizione settimanale.',
  'emailConfirmedBody': 'La tua previsione settimanale gratuita è attiva. Ogni messaggio contiene un link per annullare l’iscrizione.',
  'emailConfirmedTitle': 'Iscrizione confermata.',
  'emailConfirmIgnore': 'Se non hai fatto tu questa richiesta, ignora l’e-mail. Non verrà attivata alcuna iscrizione.',
  'emailConfirmInvalidBody': 'Il link di conferma non è valido o è scaduto. Torna su Zodiacs.org per richiederne un altro.',
  'emailConfirmInvalidTitle': 'Questo link non è valido.',
  'emailConfirmMessage': 'Conferma di voler ricevere la previsione settimanale gratuita di Zodiacs.org:',
  'emailConfirmSubject': 'Conferma la tua previsione settimanale di Zodiacs.org',
  'emailConfirmTitle': 'Un’ultima verifica.',
  'emailPendingBody': 'Usa il link di conferma che ti abbiamo inviato prima che inizi la previsione settimanale.',
  'emailPendingTitle': 'Controlla la posta.',
  'emailReturnHome': 'Torna su Zodiacs.org',
  'footerDisclosure': 'Informativa',
  'footerWidgets': 'Widget',

  // WS2c — OG and social-card art
  'og.compatibility.data': 'Cosa funziona · cosa pesa · cosa lo fa durare',
  'og.compatibility.kicker': 'Compatibilità',
  'og.compatibility.title': '{a}<br/>e {b}',
  'og.disclosure.alt': 'Informativa del Registro — fatti verificati e conferme dell’operatore in attesa.',
  'og.disclosure.kicker': 'Informativa del Registro',
  'og.disclosure.subtitle': 'Informativa su operatore, interessi economici, provenienza, separazione e sola lettura.',
  'og.disclosure.title': 'I fatti, compresi quelli ancora irrisolti.',
  'og.fallbackAlt': 'Zodiacs.org — temi natali, guide ai segni e strumenti astrologici gratuiti.',
  'og.horoscope.kicker': 'Oroscopo mensile',
  'og.horoscope.subtitle': 'Oroscopi mensili basati su fasi lunari reali, retrogradi e transiti principali.',
  'og.pin.horoscope.kicker': 'Oroscopo mensile',
  'og.pin.horoscope.subtitle': 'Basato sul cielo reale: fasi lunari, retrogradi e transiti principali, ciascuno con la sua data.',
  'og.pin.horoscope.title': '{sign}, questo mese',
  'og.pin.howTo.kicker': 'Impara l’astrologia',
  'og.pin.howTo.steps.aspects': '3 · Gli aspetti attivi',
  'og.pin.howTo.steps.bigThree': '1 · I tre pilastri',
  'og.pin.howTo.steps.rooms': '2 · Pianeti, casa per casa',
  'og.pin.howTo.steps.weather': '4 · Il clima del tema',
  'og.pin.howTo.title': 'Come leggere un tema natale.',
  'og.pin.signGuide.kicker': 'Guida al segno',
  'og.placements.kicker': 'Posizioni',
  'og.placements.subtitle': 'Tutte e dodici le posizioni di {planet}, lette da vicino.',
  'og.placements.title': '{planet} nei<br/>segni',
  'og.planetNames.jupiter': 'Giove',
  'og.planetNames.mars': 'Marte',
  'og.planetNames.mercury': 'Mercurio',
  'og.planetNames.moon': 'Luna',
  'og.planetNames.neptune': 'Nettuno',
  'og.planetNames.pluto': 'Plutone',
  'og.planetNames.saturn': 'Saturno',
  'og.planetNames.sun': 'Sole',
  'og.planetNames.uranus': 'Urano',
  'og.planetNames.venus': 'Venere',
  'og.astrofolio.alt': 'Astrofolio: la collezione di dodici token ufficiali dello Zodiaco.',
  'og.terminal.alt': 'Terminal: contesto di mercato specialistico e ricerca revisionata per i dodici token ufficiali dello Zodiaco.',
  'og.wing.data': 'Astrofolio · Registry · Terminal',
  'og.wing.kicker': 'Zodiacs.org',
  'og.wing.subtitle': 'Schede ufficiali e contesto pubblico di mercato per i dodici segni zodiacali.',
  'og.wing.title': 'I Dodici',
  'og.registryLot.kicker': 'Il Registro',
  'og.registryLot.numberLine': 'Nº {number} / 12 · lotto {lot} di XII',
  'og.registryLot.subtitle': 'Scheda ufficiale · origine nativa Solana · rappresentazione su Base tramite bridge',
  'og.rising.data': 'l’ascendente cambia segno all’incirca ogni due ore',
  'og.rising.kicker': 'Ascendenti',
  'og.rising.subtitle': 'Il modo in cui il mondo ti incontra — e il pianeta che governa il tuo tema.',
  'og.rising.title': '{sign}<br/>ascendente',
  'og.share.subtitle': 'Temi natali, guide ai segni e strumenti astrologici gratuiti.',
  'og.share.title': 'Esplora le stelle dietro la tua storia.',
  'og.signGuide.kicker': 'Guida al segno',
  'og.signNames.aquarius': 'Acquario',
  'og.signNames.aries': 'Ariete',
  'og.signNames.cancer': 'Cancro',
  'og.signNames.capricorn': 'Capricorno',
  'og.signNames.gemini': 'Gemelli',
  'og.signNames.leo': 'Leone',
  'og.signNames.libra': 'Bilancia',
  'og.signNames.pisces': 'Pesci',
  'og.signNames.sagittarius': 'Sagittario',
  'og.signNames.scorpio': 'Scorpione',
  'og.signNames.taurus': 'Toro',
  'og.signNames.virgo': 'Vergine',
  'og.thesis.alt': 'La fede è l’asset più antico — la tesi del Registro Zodiacs.org.',
  'og.thesis.footer': 'zodiacs.org — Il Registro · Revisione luglio 2026',
  'og.thesis.kicker': 'La Tesi',
  'og.thesis.title': 'La fede è l’asset più antico.',
  'og.tools.ask.kicker': 'Assistente con fonti',
  'og.tools.ask.sub': 'Il sito, l’astrologia o il tuo tema — risposte tratte dalle pagine di questo sito, con le fonti indicate.',
  'og.tools.ask.title': 'Chiedi a Zodiacs',
  'og.tools.baby-zodiac.kicker': 'Calcolatore gratuito',
  'og.tools.baby-zodiac.sub': 'Il Sole quasi certo della data prevista, le possibili Lune della settimana e ciò che dipende dall’ora.',
  'og.tools.baby-zodiac.title': 'Di che segno sarà il bambino?',
  'og.tools.birth-chart.kicker': 'Calcolatore gratuito',
  'og.tools.birth-chart.sub': 'Sole, Luna, ascendente, case e aspetti — calcolati sul tuo dispositivo.',
  'og.tools.birth-chart.title': 'Il tuo tema natale',
  'og.tools.birthday.kicker': 'Astrologia del compleanno',
  'og.tools.birthday.sub': 'Segno solare verificato su 91 anni, intervalli di gradi, decani e tabelle delle cuspidi.',
  'og.tools.birthday.title': 'Tutte le date, calcolate',
  'og.tools.compatibility.kicker': 'Compatibilità',
  'og.tools.compatibility.sub': 'Sinastria dell’intero tema — più le guide a tutte le 78 combinazioni di segni.',
  'og.tools.compatibility.title': 'Due temi a confronto',
  'og.tools.eclipses.kicker': 'Il calendario',
  'og.tools.eclipses.sub': 'Tutte le eclissi solari e lunari fino al 2028, con ora esatta del picco e segno.',
  'og.tools.eclipses.title': 'Eclissi, con le date',
  'og.tools.full-moon-calendar.kicker': 'Il calendario',
  'og.tools.full-moon-calendar.sub': 'Istanti esatti fino al 2027, con segno, grado e nome di ogni Luna.',
  'og.tools.full-moon-calendar.title': 'Tutte le lune piene',
  'og.tools.horoscopes.kicker': 'Oroscopi mensili',
  'og.tools.horoscopes.sub': 'Basati su fasi lunari reali, retrogradi e transiti principali.',
  'og.tools.horoscopes.title': 'Tutti e dodici i segni',
  'og.tools.how-to-read-a-birth-chart.kicker': 'Impara l’astrologia',
  'og.tools.how-to-read-a-birth-chart.sub': 'Tre pilastri, pianeti casa per casa, aspetti attivi e infine il clima — in ordine.',
  'og.tools.how-to-read-a-birth-chart.title': 'Come leggere un tema natale',
  'og.tools.learn.kicker': 'Impara l’astrologia',
  'og.tools.learn.sub': 'I segni, i pianeti, le case e gli aspetti, spiegati con chiarezza.',
  'og.tools.learn.title': 'Leggi il tuo tema',
  'og.tools.mercury-retrograde.kicker': 'Il calendario',
  'og.tools.mercury-retrograde.sub': 'Tutti i periodi fino al 2027, calcolati dal moto reale del pianeta.',
  'og.tools.mercury-retrograde.title': 'Mercurio retrogrado',
  'og.tools.moon-phase.kicker': 'Calcolatore gratuito',
  'og.tools.moon-phase.sub': 'La fase di stasera e la Luna di qualsiasi data importante per te.',
  'og.tools.moon-phase.title': 'La Luna, in qualsiasi notte',
  'og.tools.moon-sign.kicker': 'Calcolatore gratuito',
  'og.tools.moon-sign.sub': 'Come vivi le emozioni e ciò che ti calma — da data, ora e luogo di nascita.',
  'og.tools.moon-sign.title': 'Il tuo segno lunare',
  'og.tools.retrogrades.kicker': 'Il calendario',
  'og.tools.retrogrades.sub': 'Tutti e otto i pianeti, 2026–2027, calcolati da stazione a stazione.',
  'og.tools.retrogrades.title': 'Tutti i retrogradi',
  'og.tools.rising-sign.kicker': 'Calcolatore gratuito',
  'og.tools.rising-sign.sub': 'Il modo in cui gli altri ti vedono per la prima volta — da ora e luogo di nascita.',
  'og.tools.rising-sign.title': 'Il tuo ascendente',
  'og.tools.saturn-return.kicker': 'Calcolatore gratuito',
  'og.tools.saturn-return.sub': 'Le date esatte, con ogni passaggio e ogni ciclo retrogrado.',
  'og.tools.saturn-return.title': 'Il tuo ritorno di Saturno',
  'og.tools.today.kicker': 'Il tuo riepilogo quotidiano',
  'og.tools.today.sub': 'Il cielo di mezzogiorno confrontato in modo riservato con l’ultimo tema salvato su questo dispositivo.',
  'og.tools.today.title': 'Oggi, rispetto al tuo tema',
  'og.tools.tools.kicker': 'Strumenti astrologici gratuiti',
  'og.tools.tools.sub': 'Tema natale, compatibilità, segno lunare e altro — calcolati sul tuo dispositivo.',
  'og.tools.tools.title': 'Calcolatori, senza iscrizione',
  'og.tools.transits.kicker': 'Tracciatore gratuito',
  'og.tools.transits.sub': 'Il cielo attuale in aspetto con il tuo tema natale, entro 3° dall’esatto.',
  'og.tools.transits.title': 'I tuoi transiti, oggi',

  // WS2d — structured data
  'schema.applicationCategory': 'LifestyleApplication',
  'schema.breadcrumbHome': 'Zodiacs.org',
  'schema.breadcrumbLabels.about': 'Il progetto',
  'schema.breadcrumbLabels.archive': 'Archivio',
  'schema.breadcrumbLabels.baby-zodiac': 'Zodiaco del bambino',
  'schema.breadcrumbLabels.birth-chart': 'Tema natale',
  'schema.breadcrumbLabels.birthday': 'Astrologia del compleanno',
  'schema.breadcrumbLabels.compatibility': 'Compatibilità',
  'schema.breadcrumbLabels.disclosure': 'Informativa',
  'schema.breadcrumbLabels.eclipses': 'Eclissi',
  'schema.breadcrumbLabels.es': 'Español',
  'schema.breadcrumbLabels.feeds': 'Feed',
  'schema.breadcrumbLabels.full-moon-calendar': 'Calendario della Luna piena',
  'schema.breadcrumbLabels.horoscopes': 'Oroscopi',
  'schema.breadcrumbLabels.houses': 'Case',
  'schema.breadcrumbLabels.learn': 'Capire l’astrologia',
  'schema.breadcrumbLabels.markets': 'Percorso da Terminal alla piattaforma',
  'schema.breadcrumbLabels.mercury-retrograde': 'Mercurio retrogrado',
  'schema.breadcrumbLabels.methodology': 'Metodologia',
  'schema.breadcrumbLabels.moon-phase': 'Fase lunare',
  'schema.breadcrumbLabels.moon-sign': 'Segno lunare',
  'schema.breadcrumbLabels.placements': 'Posizioni',
  'schema.breadcrumbLabels.planets': 'Pianeti',
  'schema.breadcrumbLabels.privacy': 'Privacy',
  'schema.breadcrumbLabels.profile': 'Profilo',
  'schema.breadcrumbLabels.registry': 'Registro Zodiacs',
  'schema.breadcrumbLabels.research': 'Ricerca sui mercati',
  'schema.breadcrumbLabels.retrogrades': 'Retrogradi',
  'schema.breadcrumbLabels.rising-sign': 'Ascendente',
  'schema.breadcrumbLabels.saturn-return': 'Ritorno di Saturno',
  'schema.breadcrumbLabels.sdk': 'SDK',
  'schema.breadcrumbLabels.terms': 'Termini',
  'schema.breadcrumbLabels.astrofolio': 'Astrofolio',
  'schema.breadcrumbLabels.terminal': 'Terminal',
  'schema.breadcrumbLabels.thesis': 'La Tesi',
  'schema.breadcrumbLabels.today': 'Oggi',
  'schema.breadcrumbLabels.tools': 'Strumenti astrologici',
  'schema.breadcrumbLabels.transits': 'Transiti',
  'schema.breadcrumbLabels.widgets': 'Widget',
  'schema.browserRequirements': 'Richiede un browser moderno.',
  'schema.currency': 'USD',
  'schema.freePrice': '0',
  'schema.operatingSystem': 'Qualsiasi dispositivo con un browser moderno',
  'schema.organizationAlternateName': 'Zodiacs.org',
  'schema.organizationName': 'Zodiacs',
  'schema.websiteDescription': 'Temi natali, segni lunari, compatibilità, oroscopi e guide ai segni gratuiti — in privato nel tuo browser.',
  'schema.websiteName': 'Zodiacs.org',

  // WS3 — share cards and result sharing
  'compatibilityPrefill.clear': 'Rimuovi l’abbinamento di segni solari caricato',
  'compatibilityPrefill.help': 'Mantiene visibile il contesto dei segni solari mentre inserisci i due temi reali qui sotto. Non inventa dati di nascita.',
  'compatibilityPrefill.title': 'Abbinamento {a} e {b} caricato',
  'shareCard.balanced': 'Equilibrato',
  'shareCard.approachAction': 'Condividi come avvicinarti a me',
  'shareCard.referenceTimeNote': 'Posizioni di riferimento · Ora di nascita sconosciuta',
  'shareCard.approachBirthTimeNote': 'L’ora di nascita aggiungerebbe il mio Ascendente.',
  'shareCard.approachKicker': 'PRIMO CONTATTO · FIDUCIA · ATTRITO',
  'shareCard.approachMoonTimeNote': 'La mia Luna può cambiare segno senza un’ora di nascita precisa.',
  'shareCard.approachTitle': 'Come avvicinarti a me',
  'shareCard.bigThreeAction': 'Condividi i tre pilastri',
  'shareCard.bigThreeTitle': 'I tuoi tre pilastri',
  'shareCard.compatibilityAction': 'Condividi questa compatibilità',
  'shareCard.compatibilityBalance': 'Uno scambio equilibrato fra armonia e intensità',
  'shareCard.compatibilityBusy': 'Creazione dell’immagine di compatibilità…',
  'shareCard.compatibilityCharge': 'Un’intesa che richiede attenzione',
  'shareCard.compatibilityError': 'Non è stato possibile creare questa immagine nel tuo browser.',
  'shareCard.compatibilityNoTimeNote': 'Per un tema senza ora di nascita, l’immagine usa il cielo delle 12:00 UTC di quella data e lascia fuori la Luna, quindi i suoi contatti possono differire da questa pagina.',
  'shareCard.moonSettledNote': 'La Luna è rimasta in questo segno per tutto quel giorno, ovunque.',
  'shareCard.compatibilityFlow': 'Fluidità, con un attrito utile',
  'shareCard.compatibilitySaved': 'Immagine di compatibilità salvata.',
  'shareCard.compatibilityTitle': 'Compatibilità',
  'shareCard.dominant': 'Elemento dominante: {element} · {modality}',
  'shareCard.engineReceipt': 'Motore {version}',
  'shareCard.fullChartAction': 'Condividi il tema completo',
  'shareCard.fullChartTitle': 'Un tema natale',
  'shareCard.moon': 'Luna',
  'shareCard.moonDescriptor': 'Istinto e vita emotiva',
  'shareCard.rising': 'Ascendente',
  'shareCard.risingDescriptor': 'Prima impressione e orizzonte del tema',
  'shareCard.signatureAction': 'Condividi la firma del mio tema',
  'shareCard.signatureKicker': 'Ciò che spicca nel mio tema',
  'shareCard.signatureTitle': 'La firma del mio tema',
  'shareCard.sun': 'Sole',
  'shareCard.sunDescriptor': 'Identità centrale e direzione',
  'shareCard.tightestContacts': 'Contatti più esatti',

  // WS4 — PWA, install prompt, and flag-off push scaffold
  'push.notification.body': 'La tua nota quotidiana sul cielo è pronta.',
  'push.notification.title': 'Oggi su Zodiacs.org',
  'pwa.manifest.description': 'Temi natali, compatibilità e transiti — gratuiti, esatti e conservati sul tuo dispositivo.',
  'pwa.manifest.name': 'Zodiacs — astrologia calcolata sul dispositivo',
  'pwa.manifest.shortName': 'Zodiacs',
  'pwa.prompt.body': 'Installa Zodiacs per tornare più rapidamente ai tuoi strumenti privati, calcolati nel browser.',
  'pwa.prompt.dismiss': 'No, non chiederlo più',
  'pwa.prompt.heading': 'Vuoi tenere gli strumenti a portata di mano?',
  'pwa.prompt.icons': 'I dodici segni zodiacali',
  'pwa.prompt.install': 'Installa Zodiacs',
  'pwa.prompt.ios': 'Su iPhone o iPad, tocca Condividi e poi Aggiungi alla schermata Home.',

  // WS5 — programmatic pages and Chinese zodiac
  'chineseZodiac.allAnimals': 'Tutti e dodici gli anni degli animali',
  'chineseZodiac.animalKicker': 'Guida all’anno dell’animale',
  'chineseZodiac.animals.dog.association': 'Tradizionalmente associato alla lealtà, alla vigilanza e alla protezione.',
  'chineseZodiac.animals.dog.context': 'Il Cane è l’undicesimo. Come in ogni pagina di questa guida, l’associazione descrive una tradizione interpretativa, non una diagnosi della personalità.',
  'chineseZodiac.animals.dog.name': 'Cane',
  'chineseZodiac.animals.dragon.association': 'Tradizionalmente associato al potere propizio, alla vitalità e all’autorità.',
  'chineseZodiac.animals.dragon.context': 'Il Drago è l’animale mitico della sequenza. Ha un significato culturale diverso dal drago ostile diffuso in gran parte della narrazione europea.',
  'chineseZodiac.animals.dragon.name': 'Drago',
  'chineseZodiac.animals.goat.association': 'Tradizionalmente associata alla cura, all’armonia e alla coltivazione creativa.',
  'chineseZodiac.animals.goat.context': 'Nelle versioni inglesi compaiono Goat (capra), Ram (ariete) e Sheep (pecora). Il termine cinese di base non impone la stessa distinzione di specie dell’inglese.',
  'chineseZodiac.animals.goat.name': 'Capra',
  'chineseZodiac.animals.horse.association': 'Tradizionalmente associato all’impegno, al coraggio, alla resilienza e al movimento.',
  'chineseZodiac.animals.horse.context': 'Il Cavallo è il settimo della sequenza. Il materiale dello Smithsonian sul Cavallo di Fuoco del 2026 mette in primo piano il duro lavoro, il coraggio e la resilienza.',
  'chineseZodiac.animals.horse.name': 'Cavallo',
  'chineseZodiac.animals.monkey.association': 'Tradizionalmente associata all’ingegno, al gioco e all’adattamento rapido.',
  'chineseZodiac.animals.monkey.context': 'La Scimmia è la nona. Il folclore e le letture popolari della personalità aggiungono livelli che vanno oltre l’animale del calendario; questi livelli non sono uniformi in tutte le comunità cinesi.',
  'chineseZodiac.animals.monkey.name': 'Scimmia',
  'chineseZodiac.animals.ox.association': 'Tradizionalmente associato al lavoro costante, alla resistenza e alla responsabilità pratica.',
  'chineseZodiac.animals.ox.context': 'Nell’arte cinese, il bue e il bufalo d’acqua possono essere trattati come la stessa categoria zodiacale. L’immagine sottolinea il lavoro costante più della velocità.',
  'chineseZodiac.animals.ox.name': 'Bue',
  'chineseZodiac.animals.pig.association': 'Tradizionalmente associato all’abbondanza, alla generosità e al compimento.',
  'chineseZodiac.animals.pig.context': 'Il Maiale chiude la sequenza degli animali prima del ritorno al Topo. I riferimenti in inglese usano sia Boar (cinghiale) sia Pig (maiale).',
  'chineseZodiac.animals.pig.name': 'Maiale',
  'chineseZodiac.animals.rabbit.association': 'Tradizionalmente associato alla vigilanza, alla grazia e al movimento attento.',
  'chineseZodiac.animals.rabbit.context': 'Le fonti inglesi possono usare Rabbit (coniglio) oppure Hare (lepre). Le tradizioni zodiacali regionali possono indicare un altro animale, uno dei motivi per cui questa guida resta specifica del ciclo cinese.',
  'chineseZodiac.animals.rabbit.name': 'Coniglio',
  'chineseZodiac.animals.rat.association': 'Tradizionalmente associato all’attenzione, all’adattabilità e alla capacità di trovare una via d’uscita in situazioni con pochi margini.',
  'chineseZodiac.animals.rat.context': 'Il Topo apre la sequenza di dodici anni. I moderni riepiloghi della personalità spesso lo definiscono ingegnoso; è un’associazione culturale, non un tratto misurato.',
  'chineseZodiac.animals.rat.name': 'Topo',
  'chineseZodiac.animals.rooster.association': 'Tradizionalmente associato alla diligenza, alla scansione del tempo e all’operosità.',
  'chineseZodiac.animals.rooster.context': 'Il Met indica il risveglio mattutino del gallo come base delle associazioni con la diligenza e l’operosità, documentando anche il suo lungo uso come motivo artistico propizio.',
  'chineseZodiac.animals.rooster.name': 'Gallo',
  'chineseZodiac.animals.snake.association': 'Tradizionalmente associato alla percezione, alla riservatezza e alla trasformazione.',
  'chineseZodiac.animals.snake.context': 'Il Serpente segue il Drago nel ciclo. I tratti interpretativi variano secondo la fonte, la famiglia e la regione; la posizione nel calendario è il dato stabile.',
  'chineseZodiac.animals.snake.name': 'Serpente',
  'chineseZodiac.animals.tiger.association': 'Tradizionalmente associata al coraggio, alla forza e alla protezione.',
  'chineseZodiac.animals.tiger.context': 'Nella cultura visiva cinese la Tigre ha un carattere protettivo oltre che audace. I brevi elenchi di tratti della personalità colgono solo uno degli usi del simbolo.',
  'chineseZodiac.animals.tiger.name': 'Tigre',
  'chineseZodiac.associationLabel': 'Associazione tradizionale',
  'chineseZodiac.boundaryBody': 'L’animale dell’anno non cambia il 1º gennaio. Se la data di nascita cade a gennaio o all’inizio di febbraio, controlla la data del Capodanno lunare di quell’anno prima di scegliere un animale. Le date variano anche fra le tradizioni asiatiche e non tutte le comunità usano lo stesso zodiaco.',
  'chineseZodiac.boundaryTitle': 'L’anno inizia con il Capodanno lunare',
  'chineseZodiac.branchLabel': 'Ramo Terrestre',
  'chineseZodiac.chartLink': 'Calcola un tema natale tropicale occidentale',
  'chineseZodiac.historyBody': 'I dodici animali sono abbinati ai dodici Rami Terrestri. Le prove storiche collocano in Cina l’associazione fra animali e calendario già nel III secolo a.C., saldamente affermata nel I secolo d.C. I rami si combinano anche con dieci Tronchi Celesti in un ciclo di sessanta parti.',
  'chineseZodiac.historyTitle': 'Che cosa registra il ciclo',
  'chineseZodiac.hubIntro': 'Un’introduzione attenta allo zodiaco cinese: la sequenza degli animali, le tabelle degli anni, il quadro storico e il confine che non cade il 1º gennaio.',
  'chineseZodiac.hubTitle': 'Il ciclo di dodici anni degli animali.',
  'chineseZodiac.iconRailNote': 'I dischi colorati sono il simbolo dei segni occidentali di Zodiacs.org. Non sostituiscono gli animali dello zodiaco cinese e non rappresentano corrispondenze con essi.',
  'chineseZodiac.itemLink': 'Leggi l’Anno del {animal}',
  'chineseZodiac.kicker': 'Zodiaco cinese',
  'chineseZodiac.learnLabel': 'Capire',
  'chineseZodiac.limitsBody': 'L’animale annuale è uno strato del calendario. Una lettura più completa dell’astrologia cinese può considerare anche il Tronco Celeste e l’elemento, il mese, il giorno e l’ora. Il solo animale dell’anno non può determinare una personalità o prevedere un esito.',
  'chineseZodiac.limitsTitle': 'Che cosa dice — e non dice — di te',
  'chineseZodiac.metaAnimalDescription': 'Anno del {animal}: anni del ciclo, Ramo Terrestre {branch} ({pinyin}), associazioni tradizionali e confine del Capodanno lunare.',
  'chineseZodiac.metaAnimalTitle': 'Anno del {animal} — Anni dello zodiaco cinese | Zodiacs.org',
  'chineseZodiac.metaHubTitle': 'Zodiaco cinese — I dodici anni degli animali | Zodiacs.org',
  'chineseZodiac.next': 'Animale successivo',
  'chineseZodiac.numberLabel': 'Nº {number}',
  'chineseZodiac.positionValue': '{position} di 12',
  'chineseZodiac.previous': 'Animale precedente',
  'chineseZodiac.separateBody': 'L’astrologia tropicale occidentale colloca i pianeti rispetto a dodici settori dell’eclittica e usa il momento esatto della nascita. Queste pagine sullo zodiaco cinese partono invece dall’anno del calendario lunisolare e dal suo ramo animale. I due sistemi possono essere studiati fianco a fianco, ma uno non si traduce nell’altro.',
  'chineseZodiac.separateTitle': 'Un sistema distinto dall’astrologia tropicale occidentale',
  'chineseZodiac.sequenceLabel': 'Posizione nella sequenza',
  'chineseZodiac.sequenceTitle': 'I dodici animali, in ordine',
  'chineseZodiac.siteName': 'Zodiacs.org',
  'chineseZodiac.sourceMet': 'The Met — il calendario animale di dodici anni e la sua storia',
  'chineseZodiac.sourceMetBulletin': 'The Met Bulletin — animali, rami e ciclo di sessanta parti',
  'chineseZodiac.sourceMetHub': 'The Met — storia del ciclo dei dodici animali nel calendario',
  'chineseZodiac.sourceSmithsonian': 'Smithsonian — sequenza dello zodiaco cinese e contesto del Capodanno lunare',
  'chineseZodiac.sourceSmithsonianHub': 'Smithsonian — Capodanno lunare e sequenza dello zodiaco',
  'chineseZodiac.sourceTitle': 'Fonti museali e culturali',
  'chineseZodiac.westernLink': 'Leggi come funzionano le date dello zodiaco tropicale occidentale',
  'chineseZodiac.yearOf': 'Anno del {animal}',
  'chineseZodiac.yearsBoundary': 'Queste etichette indicano l’anno lunisolare che inizia durante l’anno gregoriano elencato. Le nascite di gennaio e dei primi di febbraio possono appartenere all’animale precedente.',
  'chineseZodiac.yearsLabel': 'Anni del ciclo',
  'chineseZodiac.yearsTitle': 'Anni recenti e prossimi del ciclo',
  'programmatic.compatibilityPrefillCta': 'Apri il calcolatore con {a} e {b} già caricati',

  // WS6 — widgets
  'widgets.accentLabel': 'Colore in evidenza',
  'widgets.backlinkNote': 'Il link “Offerto da Zodiacs.org” fa parte di ogni widget e non può essere rimosso.',
  'widgets.changePlace': 'Cambia luogo di nascita',
  'widgets.chartError': 'Non è stato possibile calcolare il tema in questo browser.',
  'widgets.chartIntro': 'Sole, Luna e ascendente — calcolati qui in modo riservato.',
  'widgets.chartOption': 'Mini tema natale',
  'widgets.chartPrivacy': 'Calcolato su questo dispositivo. Nulla di ciò che inserisci viene inviato a un’API per i temi.',
  'widgets.chartTitle': 'Mini tema natale',
  'widgets.codeLabel': 'Codice di incorporamento',
  'widgets.computeAction': 'Trova i tre pilastri',
  'widgets.computing': 'Calcolo in corso…',
  'widgets.copiedAction': 'Copiato',
  'widgets.copyAction': 'Copia il codice di incorporamento',
  'widgets.darkOption': 'Scuro',
  'widgets.dateLabel': 'Data di nascita',
  'widgets.generatorTitle': 'Crea un widget incorporato',
  'widgets.iframeOption': 'iframe in sandbox',
  'widgets.illumination': 'Illuminata al {percent}%',
  'widgets.lightOption': 'Chiaro',
  'widgets.modeLabel': 'Modalità di incorporamento',
  'widgets.moon': 'Luna',
  'widgets.moonOption': 'Fase lunare di oggi',
  'widgets.moonSign': 'Luna in {sign}',
  'widgets.moonTitle': 'Fase lunare di oggi',
  'widgets.noPlaces': 'Nessun luogo trovato',
  'widgets.noRetrograde': 'Nessun pianeta retrogrado',
  'widgets.pageIntro': 'Tre strumenti astrologici privati. L’iframe è principale; lo script monta lo stesso documento isolato. Ogni widget mantiene il credito Zodiacs.org.',
  'widgets.pageKicker': 'Widget',
  'widgets.pageMetaDescription': 'Incorpora fase lunare, cielo attuale o mini tema natale privato in qualsiasi sito. Modalità iframe in sandbox e script, gratis con il credito Zodiacs.org.',
  'widgets.pageMetaTitle': 'Widget astrologici gratuiti — Luna, cielo e tema | Zodiacs.org',
  'widgets.pageTitle': 'Il cielo, sul tuo sito.',
  'widgets.phaseNames.First Quarter': 'Primo quarto',
  'widgets.phaseNames.Full Moon': 'Luna piena',
  'widgets.phaseNames.Last Quarter': 'Ultimo quarto',
  'widgets.phaseNames.New Moon': 'Luna nuova',
  'widgets.phaseNames.Waning Crescent': 'Falce calante',
  'widgets.phaseNames.Waning Gibbous': 'Gibbosa calante',
  'widgets.phaseNames.Waxing Crescent': 'Falce crescente',
  'widgets.phaseNames.Waxing Gibbous': 'Gibbosa crescente',
  'widgets.placeError': 'Non è stato possibile caricare l’indice dei luoghi offline.',
  'widgets.placeLabel': 'Luogo di nascita',
  'widgets.placePlaceholder': 'Inizia a digitare una città…',
  'widgets.planetNames.Jupiter': 'Giove',
  'widgets.planetNames.Mars': 'Marte',
  'widgets.planetNames.Mercury': 'Mercurio',
  'widgets.planetNames.Moon': 'Luna',
  'widgets.planetNames.Neptune': 'Nettuno',
  'widgets.planetNames.Pluto': 'Plutone',
  'widgets.planetNames.Saturn': 'Saturno',
  'widgets.planetNames.Sun': 'Sole',
  'widgets.planetNames.Uranus': 'Urano',
  'widgets.planetNames.Venus': 'Venere',
  'widgets.poweredBy': 'Offerto da Zodiacs.org',
  'widgets.previewTitle': 'Anteprima dal vivo',
  'widgets.privacyNote': "Il mini tema viene calcolato nel suo iframe: la data, l’ora e il luogo di nascita inseriti non vengono inviati da nessuna parte e il tema non viene mai caricato su un server. Digitando un luogo si scarica però da zodiacs.org un elenco di città, scelto in base alla prima lettera digitata: quella richiesta rivela quindi una sola lettera e niente di più. Anche caricare il widget genera una richiesta a zodiacs.org, come qualsiasi risorsa incorporata: il browser rivela così il proprio indirizzo IP e l’origine del tuo sito. Sono cose distinte.",
  'widgets.requiresJavaScript': 'Il calcolo richiede JavaScript, ma il modulo resta privato e non invia alcun dato di nascita.',
  'widgets.retrograde': 'Retrogradi: {planets}',
  'widgets.retrogradeAbbreviation': 'Rx',
  'widgets.rising': 'Ascendente',
  'widgets.scriptOption': 'Montaggio tramite script',
  'widgets.signNames.aquarius': 'Acquario',
  'widgets.signNames.aries': 'Ariete',
  'widgets.signNames.cancer': 'Cancro',
  'widgets.signNames.capricorn': 'Capricorno',
  'widgets.signNames.gemini': 'Gemelli',
  'widgets.signNames.leo': 'Leone',
  'widgets.signNames.libra': 'Bilancia',
  'widgets.signNames.pisces': 'Pesci',
  'widgets.signNames.sagittarius': 'Sagittario',
  'widgets.signNames.scorpio': 'Scorpione',
  'widgets.signNames.taurus': 'Toro',
  'widgets.signNames.virgo': 'Vergine',
  'widgets.sizeNote': 'I documenti sono autonomi e caricano il calcolo più pesante solo dopo l’invio del mini tema.',
  'widgets.skyOption': 'Il cielo di oggi',
  'widgets.skyTitle': 'Il cielo di oggi',
  'widgets.sun': 'Sole',
  'widgets.themeLabel': 'Tema',
  'widgets.timeLabel': 'Ora di nascita',
  'widgets.widgetError': 'Scegli data, ora e luogo di nascita completi.',
  'widgets.widgetLabel': 'Widget',
  'widgets.widgetTitleChart': 'Mini tema natale — Zodiacs.org',
  'widgets.widgetTitleMoon': 'Fase lunare di oggi — Zodiacs.org',
  'widgets.widgetTitleSky': 'Il cielo di oggi — Zodiacs.org',

  // WS8 — wallet natal chart
  'walletChart.addressHelp': 'Formati accettati: chiave pubblica Solana base58 da 32 byte oppure indirizzo Base 0x.',
  'walletChart.addressLabel': 'Indirizzo Solana o Base',
  'walletChart.addressPlaceholder': 'Incolla un indirizzo pubblico',
  'walletChart.applicationCategory': 'EntertainmentApplication',
  'walletChart.base': 'Base',
  'walletChart.boundary': 'Incolla un indirizzo. Non avvengono connessioni al wallet, firme di messaggi, approvazioni, costruzione di transazioni o custodia.',
  'walletChart.breadcrumbPage': 'Tema natale del wallet',
  'walletChart.breadcrumbRegistry': 'Registro Zodiacs',
  'walletChart.calculate': 'Trova il tema del wallet',
  'walletChart.calculating': 'Lettura della cronologia pubblica…',
  'walletChart.cardBorn': 'Ora pubblica del tema · {time}',
  'walletChart.cardNoBirthplace': 'UTC · solo pianeti · nessun luogo di nascita',
  'walletChart.cardOwnerHighlight': 'Sinastria del titolare · {ownerBody} {aspect} {walletBody} del wallet · {orb}°',
  'walletChart.cardSymbolic': 'Contesto simbolico · sola lettura · non è consulenza finanziaria',
  'walletChart.cardTitle': 'Tema natale del wallet',
  'walletChart.elementBalance': 'Equilibrio degli elementi dei segni nel wallet: {balance}.',
  'walletChart.entertainmentDisclosure': 'Solo per intrattenimento e contesto simbolico.',
  'walletChart.financialDisclosure': 'Non è una consulenza finanziaria. Nulla qui costituisce una sollecitazione, una raccomandazione o una dichiarazione di valore.',
  'walletChart.historyTooDeep': 'Questo indirizzo supera il limite configurato per la cronologia Solana. Serve un provider di dati storici con un limite di pagine più alto; non viene mostrato alcun timestamp parziale.',
  'walletChart.intro': 'Un wallet ha l’ora della prima transazione registrata, ma non un luogo di nascita. Questo strumento associa il timestamp UTC pubblico solo ai pianeti nei segni.',
  'walletChart.invalidResponse': 'Il provider della cronologia ha restituito un risultato illeggibile. Riprova più tardi.',
  'walletChart.kicker': 'Strumento del Registro · sola lettura',
  'walletChart.metaDescription': 'Incolla un indirizzo Solana o Base: il primo timestamp on-chain disponibile diventa un tema simbolico con soli pianeti. Nessuna connessione, firma o transazione.',
  'walletChart.metaTitle': 'Tema del wallet — Registro in sola lettura | Zodiacs.org',
  'walletChart.noJavaScript': 'JavaScript è necessario per il calcolo astronomico privato nel browser. La ricerca dell’indirizzo e il calcolo del tema non vengono eseguiti senza una tua azione.',
  'walletChart.notFound': 'Non presente nel registro ufficiale Zodiacs.org.',
  'walletChart.officialHoldingsIntro': 'Un controllo del saldo in sola lettura ha trovato asset ufficiali del Registro per questi segni:',
  'walletChart.officialHoldingsTitle': 'Contesto ufficiale del Registro',
  'walletChart.ownerCalculating': 'Calcolo in questo browser…',
  'walletChart.ownerCancel': 'Rimuovi il confronto privato',
  'walletChart.ownerIntro': 'Se vuoi, calcola una sinastria con soli pianeti rispetto al tuo momento di nascita. Il luogo serve unicamente a ricavare l’ora locale storica.',
  'walletChart.ownerMissing': 'Inserisci una data di nascita e scegli un luogo di nascita prima di calcolare.',
  'walletChart.ownerPlaceHelp': 'Il luogo seleziona il fuso storico dai dati locali sulle città del sito; nessuna coordinata entra nel tema.',
  'walletChart.ownerPrivacy': 'Data, ora e luogo di nascita, posizioni planetarie e sinastria restano nel tuo browser. Non vengono mai inviati all’endpoint della cronologia del wallet.',
  'walletChart.ownerStart': 'Confronta con il tuo tema',
  'walletChart.ownerSubmit': 'Calcola la sinastria privata',
  'walletChart.ownerTimeHelp': 'Se l’ora non è nota, il motore usa il mezzogiorno locale e non fa affermazioni sugli angoli che cambiano rapidamente.',
  'walletChart.ownerTitle': 'Tu × il tuo wallet',
  'walletChart.placementsIntro': 'Queste posizioni usano l’istante UTC restituito. Ascendente e case richiederebbero un luogo di nascita, che un wallet non ha.',
  'walletChart.placementsTitle': 'Pianeti nei segni',
  'walletChart.privacyBody': 'Il server riceve l’indirizzo pubblico incollato e restituisce un timestamp pubblico. I dati di nascita facoltativi del titolare e l’intero calcolo astronomico restano su questo dispositivo.',
  'walletChart.privacyTitle': 'Che cosa attraversa il confine',
  'walletChart.readOnlyDisclosure': 'Sola lettura per scelta. Nessuna custodia, firma, approvazione o transazione.',
  'walletChart.registryBack': 'Torna al Registro Zodiacs',
  'walletChart.resultChain': 'Rete',
  'walletChart.resultKicker': 'Riscontro del timestamp pubblico',
  'walletChart.resultSource': 'Fonte del timestamp',
  'walletChart.resultTitle': '{address} corrisponde a {time}.',
  'walletChart.retrograde': 'retrogrado',
  'walletChart.share': 'Condividi questo tema simbolico',
  'walletChart.shareComplete': 'Immagine da condividere pronta.',
  'walletChart.shareError': 'Non è stato possibile creare l’immagine da condividere su questo dispositivo.',
  'walletChart.sharing': 'Preparazione dell’immagine privata…',
  'walletChart.solana': 'Solana',
  'walletChart.sourceBaseExplorer': 'Cronologia dell’account nell’esploratore Base',
  'walletChart.sourceBaseRpc': 'RPC archivistico Base · prima attività in uscita',
  'walletChart.sourceBaseRpcCaveat': 'L’RPC Base standard non può indicizzare i trasferimenti in entrata precedenti. Questo metodo alternativo identifica soltanto la prima transazione in uscita.',
  'walletChart.sourceSolana': 'Cronologia paginata delle firme Solana',
  'walletChart.supportedNetworks': 'Reti configurate: {networks}.',
  'walletChart.synastryBalance': 'Fluidità e attrito sono rappresentati in egual misura nei contatti più esatti.',
  'walletChart.synastryCharge': 'I contatti più esatti tendono più all’attrito che alla fluidità.',
  'walletChart.synastryContact': '{ownerBody} del tuo tema è in {aspect} con {walletBody} del wallet (orbe di {orb}°).',
  'walletChart.synastryFlow': 'I contatti più esatti tendono più alla fluidità che all’attrito.',
  'walletChart.synastryNoContact': 'Nessun aspetto principale rientra negli orbi standard del motore.',
  'walletChart.synastryTitle': 'Sinastria simbolica',
  'walletChart.title': 'Un tema simbolico per un indirizzo pubblico.',
  'walletChart.unavailable': 'La cronologia pubblica della blockchain è temporaneamente indisponibile. Nessuno stato di identità o verifica è cambiato.',
  'walletChart.utcOnly': 'Ora UTC · nessun luogo di nascita · niente case o angoli',
});
