/** French copy for every FR-pending key in i18n-additions.md. */
export const FR_ADDITIONS = Object.freeze({
  // WS1 — trust, disclosure, and archive receipts
  'archive.archivedReceipt': 'Copie archivée',
  'archive.entries.accidental-libra.receipts.mintAddress': 'Publication de Portnoy contenant l’adresse de création de Libra',
  'archive.entries.accidental-libra.receipts.wrongLibra': 'Portnoy : « J’achète le mauvais libra »',
  'archive.entries.astrologers-arrive.receipts.primary': 'TikTokInvestors : « Les astrologues sont arrivés »',
  'archive.entries.astrology-girlies.receipts.primary': 'iJaadee : appel à la communauté astrologique',
  'archive.entries.horoscopes-to-hodl.receipts.primary': 'Numinous Realm : « Horoscopes to HODL »',
  'archive.entries.oldest-meme.receipts.primary': 'Andrew Kang : « Le plus ancien mème de la civilisation humaine »',
  'archive.entries.onboarding-wave.receipts.primary': 'wantonwallet : trace de l’arrivée de plus de 1 200 portefeuilles',
  'archive.entries.origin.receipts.registry': 'Registre lisible par machine publié',
  'archive.entries.pure-belief.receipts.primary': 'CZ : « Juste un pur système de croyances »',
  'archive.entries.zodiac-iwo.receipts.primary': 'inversebrah : publication en notation abrégée du zodiaque',
  'archive.pendingPrimary': 'Archivage de la source primaire en attente',
  'archive.receiptsLabel': 'Pièces justificatives',
  'archive.verifiedRegistry': 'Correspond à la notice officielle',
  'disclosure.aboutLink': 'Lire les déclarations du Registre',
  'disclosure.aboutNotice': 'Les attestations de l’opérateur et d’intérêts économiques du Registre, les douze pièces d’origine datées et la provenance de la création sont publiées sur la page des déclarations.',
  'disclosure.adviceEvidence': '« Officiel » est uniquement une classification du Registre : cela signifie qu’une adresse, un contrat, un jeton créé ou une représentation correspond à la liste publiée par le Registre — et non une approbation gouvernementale, une vérification d’identité, une garantie de sécurité, de valeur, de liquidité ou de performance future. Les avertissements contextuels et les conditions exposent les risques liés aux actifs numériques.',
  'disclosure.adviceLabel': 'Conseil financier et sollicitation',
  'disclosure.adviceStatement': 'Les entrées du Registre, le contexte de marché et Registry Collection ne constituent ni un conseil financier ni une sollicitation à acheter, vendre ou détenir un actif. La Collection est une réflexion symbolique, pas une note attribuée au portefeuille ni un signal de prix, et aucun achat n’est requis.',
  'disclosure.backRegistry': 'Retour au Registre Zodiacs',
  'disclosure.economicEvidence': 'L’attestation de détention est la déclaration de l’opérateur lui-même, datée du 2026-08-02 et sans vérification indépendante ; elle n’énumère ni actifs, ni portefeuilles, ni montants, ni politique de blocage, d’acquisition progressive ou de cession, et les avoirs privés ne sont déduits d’aucun portefeuille. La répartition des détenteurs est publiée via des instantanés publics. Au 20 juillet 2026, la part des dix premiers comptes de jetons allait de 23,0 % à 30,6 % selon les douze actifs, avec une médiane de 27,2 %. Ces chiffres peuvent être vérifiés dans les instantanés publiés et les registres publics de la chaîne.',
  'disclosure.economicLabel': 'Intérêt économique',
  'disclosure.economicSnapshotsLink': 'Instantanés de répartition',
  'disclosure.economicStatement': 'L’opérateur atteste (2026-08-02) détenir des positions dans un ou plusieurs des douze actifs du Registre et ne percevoir aucune rémunération de parrainage, de frais de plateforme, de liquidité ou de place de marché pour une opération effectuée par l’intermédiaire du site.',
  'disclosure.establishedLabel': 'Création du Registre',
  'disclosure.establishedPending': 'Provenance du premier déploiement — en attente',
  'disclosure.establishedPrefix': 'Créé en',
  'disclosure.establishedProvenance': 'Première pièce d’origine · 2024-07-05',
  'disclosure.evidenceHeading': 'État et preuves',
  'disclosure.intro': 'Cette page sépare les faits étayés par des preuves publiques des déclarations fournies par l’opérateur, Zodiacs LLC. Une attestation de l’opérateur est datée et signalée comme telle ; elle n’est jamais présentée comme vérifiée de façon indépendante.',
  'disclosure.kicker': 'Déclarations du Registre',
  'disclosure.linkLabel': 'Déclarations',
  'disclosure.linkMethodology': 'Méthodologie',
  'disclosure.linkPrivacy': 'Confidentialité',
  'disclosure.linkRegistry': 'Registre lisible par machine',
  'disclosure.linkSdk': 'Position du SDK',
  'disclosure.linkTerms': 'Conditions',
  'disclosure.linkThesis': 'Thèse',
  'disclosure.metaDescription': 'Déclarations claires sur l’opérateur, les intérêts économiques, la provenance, la séparation, la lecture seule, la négociation intégrée et l’absence de conseil financier du Registre Zodiacs.org.',
  'disclosure.metaTitle': 'Déclarations — Registre Zodiacs.org',
  'disclosure.operatorEvidence': 'Fondé sur une mise à jour de domaine fournie par l’opérateur et datée du 2026-08-23 ; sans vérification indépendante. Elle remplace uniquement l’affirmation du 2026-08-02 selon laquelle l’ancien domaine et Astrofolio étaient des surfaces grand public distinctes. L’attestation de détention et d’absence de rémunération conserve séparément sa date du 2026-08-02.',
  'disclosure.operatorLabel': 'Relation avec l’opérateur',
  'disclosure.operatorRequest': 'Ce que signifie « attesté par l’opérateur »',
  'disclosure.operatorRequestBody': 'La ligne sur la relation avec l’opérateur résume sa mise à jour de domaine datée. La ligne sur les intérêts économiques conserve son attestation, datée séparément. Aucune n’est vérifiée de manière indépendante ; toutes deux portent donc la pastille d’attestation plutôt que celle de vérifié. Toutes les autres lignes renvoient à des preuves que chacun peut contrôler.',
  'disclosure.operatorStatement': 'Mise à jour de l’opérateur (2026-08-23) : l’opérateur contrôle le domaine zodiacs.org, le dépôt, les déploiements, le contenu du Registre et l’expérience grand public officielle Astrofolio à l’adresse zodiacs.org/astrofolio. astrofolio.xyz redirige vers cette page et n’est pas une surface grand public distincte. Cette mise à jour n’établit pas qui contrôle le déploiement ou les autorités administratives des jetons, la trésorerie, la liquidité ou l’activité de marché.',
  'disclosure.originEvidence': 'Les douze pièces sont datées du 5 juillet 2024. Chacune a été localisée par inspection des instructions sur un RPC d’archive et recoupée avec les pages publiques de Solscan, indexées indépendamment ; les noms des jetons n’ont jamais servi de preuve. Les représentations sur Base sont des ponts officiels, déclarés séparément dans le tableau de l’instrument de la thèse.',
  'disclosure.originLabel': 'Origine',
  'disclosure.originSlot': 'Pièce d’origine de {sign} — {date}',
  'disclosure.originStatement': 'Chaque enregistrement canonique est étayé par sa pièce d’origine : la transaction qui a créé le jeton natif du signe sur Solana.',
  'disclosure.provenancePendingShort': 'Provenance du déploiement en attente',
  'disclosure.provenanceShort': 'Pièces d’origine — 5 juil. 2024',
  'disclosure.readOnlyEvidence': "Zodiacs.org ne connecte pas de portefeuilles, ne demande pas de signatures et ne soumet pas de transactions. Les consultations d’adresses publiques utilisent une adresse que vous collez. Les liens d’achat ouvrent des services indépendants avec leurs propres conditions et risques.",
  'disclosure.tradeLabel': 'Limite de transaction du catalogue',
  'disclosure.tradeStatement': "Zodiacs.org ne connecte pas de portefeuilles, ne demande pas de signatures et ne soumet pas de transactions. Les consultations d’adresses publiques utilisent une adresse que vous collez. Les liens d’achat ouvrent des services indépendants avec leurs propres conditions et risques.",
  'disclosure.tradeEvidence': "Zodiacs.org ne connecte pas de portefeuilles, ne demande pas de signatures et ne soumet pas de transactions. Les consultations d’adresses publiques utilisent une adresse que vous collez. Les liens d’achat ouvrent des services indépendants avec leurs propres conditions et risques.",
  'disclosure.linkTradeExample': "Guide des adresses publiques",
  'disclosure.readOnlyLabel': 'Fonctionnement en lecture seule',
  'disclosure.readOnlyStatement': "Zodiacs.org ne connecte pas de portefeuilles, ne demande pas de signatures et ne soumet pas de transactions. Les consultations d’adresses publiques utilisent une adresse que vous collez. Les liens d’achat ouvrent des services indépendants avec leurs propres conditions et risques.",
  'disclosure.scope': 'Ces déclarations s’appliquent à l’Aile des collections. Les outils astrologiques restent gratuits, calculés dans le navigateur et utilisables sans le Registre.',
  'disclosure.separationEvidence': 'Les calculateurs effectuent leurs calculs dans le navigateur sans interaction avec le Registre. Aura conserve le calcul du thème sur l’appareil et transmet uniquement l’adresse publique sélectionnée à son service de consultation des actifs.',
  'disclosure.separationLabel': 'Séparation',
  'disclosure.separationStatement': 'Les principaux outils astrologiques restent gratuits, ne contiennent ni publicité ni traqueur intersite et peuvent être utilisés sans le Registre. Registry Collection est un lien facultatif qui lit côte à côte un thème enregistré et le registre public d’un portefeuille ; le registre du portefeuille ne modifie pas le calcul du thème.',
  'disclosure.statementHeading': 'Déclaration',
  'disclosure.statusAttested': 'Attesté par l’opérateur — sans vérification indépendante',
  'disclosure.statusPending': 'Confirmation de l’opérateur en attente',
  'disclosure.statusVerified': 'Vérifié à partir des éléments publiés',
  'disclosure.tableLabel': 'Déclarations du Registre et état des preuves',
  'disclosure.title': 'Les faits, y compris ceux qui restent à résoudre.',
  'registry.establishmentProvenanceLink': 'Provenance ↗',
  'registry.ogLotAlt': '{sign} — Nº {number} sur 12, lot {lot} sur XII dans le Registre officiel Zodiacs.org.',
  'registry.verifierNotFoundInline': 'introuvable dans le registre officiel Zodiacs.org',
  'registry.verifierNotFoundSentence': 'Introuvable dans le registre officiel Zodiacs.org.',

  // WS2b — email capture and shared footer
  'emailCaptureChangeSign': 'Changer',
  'emailCaptureCopy': 'Une prévision hebdomadaire pour ton signe. Gratuite, avec désabonnement à tout moment.',
  'emailCaptureEmailLabel': 'Adresse e-mail',
  'emailCaptureEmailPlaceholder': 'toi@exemple.com',
  'emailCaptureError': 'Impossible de démarrer l’abonnement. Réessaie.',
  'emailCaptureErrorTitle': 'Abonnement indisponible',
  'emailCaptureHoneypot': 'Laisse ce champ vide',
  'emailCaptureKicker': 'Prévision hebdomadaire gratuite',
  'emailCaptureNoSign': 'Passer le signe',
  'emailCapturePersonalTitle': 'Ta semaine de {sign} à venir.',
  'emailCapturePrivacy': 'Nous conservons ton e-mail uniquement avec le signe choisi — jamais tes données de naissance.',
  'emailCaptureSignLegend': 'Ton signe solaire (facultatif)',
  'emailCaptureSubmit': 'Envoie-moi ma semaine',
  'emailCaptureSubmitting': 'Inscription…',
  'emailCaptureSuccess': 'Consulte ta messagerie pour confirmer ton abonnement.',
  'emailCaptureTitle': 'Ta semaine à venir.',
  'emailCaptureUsingSign': 'Signe solaire utilisé : {sign}',
  'emailConfirmAction': 'Confirmer l’abonnement',
  'emailConfirmBody': 'Confirme cet abonnement pour commencer à recevoir la prévision hebdomadaire gratuite. D’ici là, aucun abonnement hebdomadaire n’est actif.',
  'emailConfirmedBody': 'Ta prévision hebdomadaire gratuite est activée. Chaque message contient un lien de désabonnement.',
  'emailConfirmedTitle': 'Abonnement confirmé.',
  'emailConfirmIgnore': 'Si tu n’as pas fait cette demande, ignore cet e-mail. Aucun abonnement ne sera activé.',
  'emailConfirmInvalidBody': 'Le lien de confirmation est invalide ou a expiré. Retourne sur Zodiacs.org pour en demander un autre.',
  'emailConfirmInvalidTitle': 'Ce lien n’est pas valide.',
  'emailConfirmMessage': 'Confirme que tu souhaites recevoir la prévision hebdomadaire gratuite de Zodiacs.org :',
  'emailConfirmSubject': 'Confirme ta prévision hebdomadaire Zodiacs.org',
  'emailConfirmTitle': 'Une dernière vérification.',
  'emailPendingBody': 'Utilise le lien de confirmation que nous t’avons envoyé avant le début de ta prévision hebdomadaire.',
  'emailPendingTitle': 'Consulte ta messagerie.',
  'emailReturnHome': 'Retourner sur Zodiacs.org',
  'footerDisclosure': 'Déclarations',
  'footerWidgets': 'Widgets',

  // WS2c — OG and social-card art
  'og.compatibility.data': 'Ce qui marche · ce qui coince · ce qui fait durer',
  'og.compatibility.kicker': 'Compatibilité',
  'og.compatibility.title': '{a}<br/>et {b}',
  'og.disclosure.alt': 'Déclarations du Registre — faits vérifiés et confirmations de l’opérateur en attente.',
  'og.disclosure.kicker': 'Déclarations du Registre',
  'og.disclosure.subtitle': 'Déclarations sur l’opérateur, les intérêts économiques, la provenance, la séparation et la lecture seule.',
  'og.disclosure.title': 'Les faits, y compris ceux qui restent à résoudre.',
  'og.fallbackAlt': 'Zodiacs.org — thèmes astraux, guides des signes et outils astrologiques gratuits.',
  'og.horoscope.kicker': 'Horoscope',
  'og.horoscope.subtitle': 'Du quotidien à l’annuel : des lectures aux thèmes clairs, avec un geste utile.',
  'og.pin.horoscope.kicker': 'Horoscope',
  'og.pin.horoscope.subtitle': 'Lectures quotidiennes, hebdomadaires, mensuelles, amour, carrière et annuelles pour chaque signe.',
  'og.pin.horoscope.title': '{sign}, ta prévision',
  'og.pin.howTo.kicker': 'Comprendre l’astrologie',
  'og.pin.howTo.steps.aspects': '3 · Les aspects à l’œuvre',
  'og.pin.howTo.steps.bigThree': '1 · Les trois piliers',
  'og.pin.howTo.steps.rooms': '2 · Les planètes, maison par maison',
  'og.pin.howTo.steps.weather': '4 · Le climat du thème',
  'og.pin.howTo.title': 'Comment lire un thème astral.',
  'og.pin.signGuide.kicker': 'Guide du signe',
  'og.placements.kicker': 'Placements',
  'og.placements.subtitle': 'Les douze placements de {planet}, examinés de près.',
  'og.placements.title': '{planet} dans<br/>les signes',
  'og.planetNames.jupiter': 'Jupiter',
  'og.planetNames.mars': 'Mars',
  'og.planetNames.mercury': 'Mercure',
  'og.planetNames.moon': 'Lune',
  'og.planetNames.neptune': 'Neptune',
  'og.planetNames.pluto': 'Pluton',
  'og.planetNames.saturn': 'Saturne',
  'og.planetNames.sun': 'Soleil',
  'og.planetNames.uranus': 'Uranus',
  'og.planetNames.venus': 'Vénus',
  'og.astrofolio.alt': 'Astrofolio : la collection de douze jetons officiels du Zodiaque.',
  'og.terminal.alt': 'Terminal : contexte de marché expert et recherche relue pour les douze jetons officiels du Zodiaque.',
  'og.wing.data': 'Astrofolio · Registry · Terminal',
  'og.wing.kicker': 'Zodiacs.org',
  'og.wing.subtitle': 'Notices officielles et contexte public de marché pour les douze signes du Zodiaque.',
  'og.wing.title': 'Les Douze',
  'og.registryLot.kicker': 'Le Registre',
  'og.registryLot.numberLine': 'Nº {number} / 12 · Lot {lot} sur XII',
  'og.registryLot.subtitle': 'Notice officielle · origine native Solana · représentation transférée sur Base',
  'og.rising.data': 'l’ascendant change de signe environ toutes les deux heures',
  'og.rising.kicker': 'Les ascendants',
  'og.rising.subtitle': 'La première impression que tu donnes — et la planète qui gouverne ton thème.',
  'og.rising.title': '{sign}<br/>ascendant',
  'og.share.subtitle': 'Thèmes astraux, guides des signes et outils astrologiques gratuits.',
  'og.share.title': 'Ton thème complet, pas seulement ton signe.',
  'og.signGuide.kicker': 'Guide du signe',
  'og.signNames.aquarius': 'Verseau',
  'og.signNames.aries': 'Bélier',
  'og.signNames.cancer': 'Cancer',
  'og.signNames.capricorn': 'Capricorne',
  'og.signNames.gemini': 'Gémeaux',
  'og.signNames.leo': 'Lion',
  'og.signNames.libra': 'Balance',
  'og.signNames.pisces': 'Poissons',
  'og.signNames.sagittarius': 'Sagittaire',
  'og.signNames.scorpio': 'Scorpion',
  'og.signNames.taurus': 'Taureau',
  'og.signNames.virgo': 'Vierge',
  'og.thesis.alt': 'La croyance est le plus ancien actif — la thèse du Registre Zodiacs.org.',
  'og.thesis.footer': 'zodiacs.org — Le Registre · Révisé en juillet 2026',
  'og.thesis.kicker': 'La Thèse',
  'og.thesis.title': 'La croyance est le plus ancien actif.',
  'og.tools.group-charts.kicker': 'Lecture de groupe gratuite',
  'og.tools.group-charts.sub': 'De trois à huit thèmes, chacun avec un rôle : l’étincelle, l’ancre, le lien ou la cohésion.',
  'og.tools.group-charts.title': 'Qui est l’étincelle, et qui fait la cohésion ?',
  'og.tools.chart-twins.kicker': 'Répertoire documenté',
  'og.tools.chart-twins.sub': 'Des personnalités publiques qui partagent tes signes solaire et lunaire vérifiés.',
  'og.tools.chart-twins.title': 'Tes jumeaux astrologiques',
  'og.tools.big-three.kicker': 'Soleil · Lune · Ascendant',
  'og.tools.big-three.sub': 'Trois signes en quelques secondes, avec une carte verticale créée dans ton navigateur.',
  'og.tools.big-three.title': 'Tes trois signes',
  'og.tools.compatibility-private-invite.kicker': 'Compatibilité',
  'og.tools.compatibility-private-invite.sub': 'Envoie un lien. Ton ami ajoute son thème et vous voyez comment ils se répondent.',
  'og.tools.compatibility-private-invite.title': 'Invite un ami à comparer',
  'og.tools.sky-calendar.kicker': 'Le calendrier',
  'og.tools.sky-calendar.sub': 'Nouvelles et pleines lunes, pics d’éclipses et rétrogradations, de 2026 à 2030.',
  'og.tools.sky-calendar.title': 'Le ciel dans ton calendrier',
  'og.tools.chart-of-the-day.kicker': 'Dans l’actualité',
  'og.tools.chart-of-the-day.sub': 'Le thème d’une personnalité publique, avec des données de naissance documentées et leurs limites.',
  'og.tools.chart-of-the-day.title': 'Thème du jour',
  'og.tools.your-sky-wrapped.kicker': 'Ton année',
  'og.tools.your-sky-wrapped.sub': 'Les contacts de Jupiter et Saturne avec ton thème cette année, sur une image.',
  'og.tools.your-sky-wrapped.title': 'Ton ciel, en rétrospective',
  'og.tools.astrologer-kit.kicker': 'Pour les astrologues',
  'og.tools.astrologer-kit.sub': 'Roue, positions, aspects et relevé du calcul dans un PDF.',
  'og.tools.astrologer-kit.title': 'Un thème prêt pour le client',
  'og.tools.ask.kicker': 'Guide d’astrologie',
  'og.tools.ask.sub': 'Pose tes questions sur ce site, l’astrologie ou ton propre thème.',
  'og.tools.ask.title': 'Guide',
  'og.tools.baby-zodiac.kicker': 'Calculateur gratuit',
  'og.tools.baby-zodiac.sub': 'Le Soleil presque certain du terme, les Lunes possibles de la semaine et ce qui dépend encore de l’heure.',
  'og.tools.baby-zodiac.title': 'Quel sera le signe du bébé ?',
  'og.tools.birth-chart.kicker': 'Calculateur gratuit',
  'og.tools.birth-chart.sub': 'Soleil, Lune, ascendant, maisons et aspects — calculés sur ton appareil.',
  'og.tools.birth-chart.title': 'Ton thème astral',
  'og.tools.birthday.kicker': 'Astrologie des anniversaires',
  'og.tools.birthday.sub': 'Caractère, amour, travail, évolution, et une réponse exacte sur la cuspide quand l’année compte.',
  'og.tools.birthday.title': 'Ta date de naissance, lue de près',
  'og.tools.compatibility.kicker': 'Compatibilité',
  'og.tools.compatibility.sub': 'Synastrie des thèmes complets — avec les guides des 78 paires de signes.',
  'og.tools.compatibility.title': 'Deux thèmes, comparés',
  'og.tools.eclipses.kicker': 'Le calendrier',
  'og.tools.eclipses.sub': 'Chaque éclipse solaire et lunaire jusqu’en 2028, avec l’heure exacte du maximum et le signe.',
  'og.tools.eclipses.title': 'Les éclipses, datées',
  'og.tools.full-moon-calendar.kicker': 'Le calendrier',
  'og.tools.full-moon-calendar.sub': 'Instants exacts jusqu’en 2027, avec le signe, le degré et le nom de chaque pleine lune.',
  'og.tools.full-moon-calendar.title': 'Toutes les pleines lunes',
  'og.tools.horoscopes.kicker': 'Horoscopes',
  'og.tools.horoscopes.sub': 'Du quotidien à l’annuel : des lectures aux thèmes clairs, avec un geste utile.',
  'og.tools.horoscopes.title': 'Les douze signes',
  'og.tools.how-to-read-a-birth-chart.kicker': 'Comprendre l’astrologie',
  'og.tools.how-to-read-a-birth-chart.sub': 'Les trois piliers, les planètes maison par maison, les aspects à l’œuvre, puis le climat — dans cet ordre.',
  'og.tools.how-to-read-a-birth-chart.title': 'Comment lire un thème astral',
  'og.tools.learn.kicker': 'Comprendre l’astrologie',
  'og.tools.learn.sub': 'Les signes, les planètes, les maisons et les aspects, en termes simples.',
  'og.tools.learn.title': 'Lire ton thème',
  'og.tools.mercury-retrograde.kicker': 'Le calendrier',
  'og.tools.mercury-retrograde.sub': 'Toutes les périodes jusqu’en 2027, calculées d’après le mouvement réel de la planète.',
  'og.tools.mercury-retrograde.title': 'Mercure rétrograde',
  'og.tools.moon-phase.kicker': 'Calculateur gratuit',
  'og.tools.moon-phase.sub': 'La phase de ce soir et la Lune de toute date qui compte pour toi.',
  'og.tools.moon-phase.title': 'La Lune, n’importe quel soir',
  'og.tools.moon-sign.kicker': 'Calculateur gratuit',
  'og.tools.moon-sign.sub': 'Ta manière de ressentir et ce qui t’apaise — d’après ta date, ton heure et ton lieu de naissance.',
  'og.tools.moon-sign.title': 'Ton signe lunaire',
  'og.tools.retrogrades.kicker': 'Le calendrier',
  'og.tools.retrogrades.sub': 'Les huit planètes, avec chaque période de station jusqu’en 2027.',
  'og.tools.retrogrades.title': 'Toutes les rétrogrades',
  'og.tools.rising-sign.kicker': 'Calculateur gratuit',
  'og.tools.rising-sign.sub': 'La première impression que tu donnes — d’après ton heure et ton lieu de naissance.',
  'og.tools.rising-sign.title': 'Ton ascendant',
  'og.tools.saturn-return.kicker': 'Calculateur gratuit',
  'og.tools.saturn-return.sub': 'Les dates exactes, avec chaque passage et chaque boucle rétrograde.',
  'og.tools.saturn-return.title': 'Ton retour de Saturne',
  'og.tools.today.kicker': 'Ton résumé quotidien',
  'og.tools.today.sub': 'Un point quotidien personnel, tiré du dernier thème enregistré sur cet appareil.',
  'og.tools.today.title': 'Aujourd’hui, pour ton thème',
  'og.tools.tools.kicker': 'Outils astrologiques gratuits',
  'og.tools.tools.sub': 'Thème astral, compatibilité, signe lunaire et plus — calculés sur ton appareil.',
  'og.tools.tools.title': 'Calculateurs, sans inscription',
  'og.tools.transits.kicker': 'Suivi gratuit',
  'og.tools.transits.sub': 'Les aspects entre le ciel actuel et ton thème astral, à moins de 3° du point exact.',
  'og.tools.transits.title': 'Tes transits, aujourd’hui',

  // WS2d — structured data
  'schema.applicationCategory': 'LifestyleApplication',
  'schema.breadcrumbHome': 'Zodiacs.org',
  'schema.breadcrumbLabels.about': 'À propos',
  'schema.breadcrumbLabels.archive': 'Archives',
  'schema.breadcrumbLabels.baby-zodiac': 'Zodiaque du bébé',
  'schema.breadcrumbLabels.birth-chart': 'Thème astral',
  'schema.breadcrumbLabels.birthday': 'Astrologie des anniversaires',
  'schema.breadcrumbLabels.compatibility': 'Compatibilité',
  'schema.breadcrumbLabels.disclosure': 'Déclarations',
  'schema.breadcrumbLabels.eclipses': 'Éclipses',
  'schema.breadcrumbLabels.es': 'Español',
  'schema.breadcrumbLabels.feeds': 'Flux',
  'schema.breadcrumbLabels.full-moon-calendar': 'Calendrier des pleines lunes',
  'schema.breadcrumbLabels.horoscopes': 'Horoscopes',
  'schema.breadcrumbLabels.houses': 'Maisons',
  'schema.breadcrumbLabels.learn': 'Comprendre l’astrologie',
  'schema.breadcrumbLabels.markets': 'Parcours de Terminal vers la plateforme',
  'schema.breadcrumbLabels.mercury-retrograde': 'Mercure rétrograde',
  'schema.breadcrumbLabels.methodology': 'Méthodologie',
  'schema.breadcrumbLabels.moon-phase': 'Phase de la Lune',
  'schema.breadcrumbLabels.moon-sign': 'Signe lunaire',
  'schema.breadcrumbLabels.placements': 'Placements',
  'schema.breadcrumbLabels.planets': 'Planètes',
  'schema.breadcrumbLabels.privacy': 'Confidentialité',
  'schema.breadcrumbLabels.profile': 'Profil',
  'schema.breadcrumbLabels.registry': 'Registre Zodiacs',
  'schema.breadcrumbLabels.research': 'Recherche sur les marchés',
  'schema.breadcrumbLabels.retrogrades': 'Rétrogrades',
  'schema.breadcrumbLabels.rising-sign': 'Ascendant',
  'schema.breadcrumbLabels.saturn-return': 'Retour de Saturne',
  'schema.breadcrumbLabels.sdk': 'SDK',
  'schema.breadcrumbLabels.terms': 'Conditions',
  'schema.breadcrumbLabels.astrofolio': 'Astrofolio',
  'schema.breadcrumbLabels.terminal': 'Terminal',
  'schema.breadcrumbLabels.thesis': 'La Thèse',
  'schema.breadcrumbLabels.today': 'Aujourd’hui',
  'schema.breadcrumbLabels.tools': 'Outils astrologiques',
  'schema.breadcrumbLabels.transits': 'Transits',
  'schema.breadcrumbLabels.widgets': 'Widgets',
  'schema.browserRequirements': 'Nécessite un navigateur web moderne.',
  'schema.currency': 'USD',
  'schema.freePrice': '0',
  'schema.operatingSystem': 'Tout appareil doté d’un navigateur web moderne',
  'schema.organizationAlternateName': 'Zodiacs.org',
  'schema.organizationName': 'Zodiacs',
  'schema.websiteDescription': 'Thèmes astraux, signes lunaires, compatibilité, horoscopes et guides des signes gratuits — en toute confidentialité dans ton navigateur.',
  'schema.websiteName': 'Zodiacs.org',

  // WS3 — share cards and result sharing
  'compatibilityPrefill.clear': 'Effacer la paire de signes solaires chargée',
  'compatibilityPrefill.help': 'Le contexte des signes solaires reste visible pendant que tu saisis les deux véritables thèmes ci-dessous. Aucune donnée de naissance n’est inventée.',
  'compatibilityPrefill.title': 'Paire {a} et {b} chargée',
  'shareCard.balanced': 'Équilibré',
  'shareCard.approachAction': 'Partager comment m’aborder',
  'shareCard.referenceTimeNote': 'Positions de référence · Heure de naissance inconnue',
  'shareCard.approachBirthTimeNote': 'L’heure de naissance ajouterait mon Ascendant.',
  'shareCard.approachKicker': 'PREMIER CONTACT · CONFIANCE · TENSION',
  'shareCard.approachMoonTimeNote': 'Ma Lune peut changer de signe sans heure de naissance précise.',
  'shareCard.approachTitle': 'Comment m’aborder',
  'shareCard.bigThreeAction': 'Partager les trois piliers',
  'shareCard.bigThreeTitle': 'Tes trois piliers',
  'shareCard.compatibilityAction': 'Partager cette compatibilité',
  'shareCard.compatibilityBalance': 'Un équilibre entre fluidité et tension',
  'shareCard.compatibilityBusy': 'Création de la carte de compatibilité…',
  'shareCard.compatibilityCharge': 'Une alchimie qui demande de l’attention',
  'shareCard.compatibilityError': 'Impossible de créer cette carte dans ton navigateur.',
  'shareCard.compatibilityNoTimeNote': 'Pour un thème sans heure de naissance, l’image utilise le ciel de 12:00 UTC à cette date et laisse de côté la Lune : ses contacts peuvent donc différer de cette page.',
  'shareCard.moonSettledNote': 'La Lune est restée dans ce signe toute la journée, partout.',
  'shareCard.compatibilityFlow': 'De la fluidité, avec une tension utile',
  'shareCard.compatibilitySaved': 'Carte de compatibilité enregistrée.',
  'shareCard.compatibilityTitle': 'Compatibilité',
  'shareCard.dominant': 'Dominance : {element} · {modality}',
  'shareCard.engineReceipt': 'Moteur {version}',
  'shareCard.fullChartAction': 'Partager le thème complet',
  'shareCard.fullChartTitle': 'Un thème astral',
  'shareCard.moon': 'Lune',
  'shareCard.moonDescriptor': 'Instinct et vie émotionnelle',
  'shareCard.rising': 'Ascendant',
  'shareCard.risingDescriptor': 'Première impression et horizon du thème',
  'shareCard.signatureAction': 'Partager la signature de mon thème',
  'shareCard.signatureKicker': 'Ce qui ressort de mon thème',
  'shareCard.signatureTitle': 'La signature de mon thème',
  'shareCard.sun': 'Soleil',
  'shareCard.sunDescriptor': 'Identité profonde et direction',
  'shareCard.tightestContacts': 'Contacts les plus serrés',

  // WS4 — PWA, install prompt, and flag-off push scaffold
  'push.notification.body': 'Une date qui compte dans le ciel aujourd’hui — ouvre ta lecture du jour.',
  'push.notification.title': 'Alerte du ciel — Zodiacs.org',
  'pwa.manifest.description': 'Thèmes astraux, compatibilité et transits — gratuits, précis et conservés sur ton appareil.',
  'pwa.manifest.name': 'Zodiacs — astrologie calculée sur ton appareil',
  'pwa.manifest.shortName': 'Zodiacs',
  'pwa.prompt.body': 'Installe Zodiacs pour retrouver plus vite tes thèmes, l’astrologie du jour et tes outils enregistrés.',
  'pwa.prompt.dismiss': 'Non, ne plus me le demander',
  'pwa.prompt.heading': 'Garder tes outils à portée de main ?',
  'pwa.prompt.icons': 'Les douze signes du zodiaque',
  'pwa.prompt.install': 'Installer Zodiacs',
  'pwa.prompt.ios': 'Sur iPhone ou iPad, touche Partager, puis Sur l’écran d’accueil.',

  // WS5 — programmatic pages and Chinese zodiac
  'chineseZodiac.allAnimals': 'Les années des douze animaux',
  'chineseZodiac.animalKicker': 'Guide d’une année du zodiaque',
  'chineseZodiac.animals.dog.association': 'Association traditionnelle : loyauté, vigilance et protection.',
  'chineseZodiac.animals.dog.context': 'Le Chien occupe la onzième place. Comme sur chaque page de ce guide, cette association décrit une tradition d’interprétation, et non un diagnostic de personnalité.',
  'chineseZodiac.animals.dog.name': 'Chien',
  'chineseZodiac.animals.dragon.association': 'Association traditionnelle : puissance de bon augure, vitalité et autorité.',
  'chineseZodiac.animals.dragon.context': 'Le Dragon est l’animal mythique de la séquence. Son registre culturel diffère de celui du dragon hostile courant dans de nombreux récits européens.',
  'chineseZodiac.animals.dragon.name': 'Dragon',
  'chineseZodiac.animals.goat.association': 'Association traditionnelle : soin, harmonie et culture créatrice.',
  'chineseZodiac.animals.goat.context': 'Goat, Ram et Sheep apparaissent tous dans les traductions anglaises. Le terme chinois sous-jacent n’impose pas la même distinction d’espèce que l’anglais.',
  'chineseZodiac.animals.goat.name': 'Chèvre',
  'chineseZodiac.animals.horse.association': 'Association traditionnelle : effort, courage, résilience et mouvement.',
  'chineseZodiac.animals.horse.context': 'Le Cheval est septième dans la séquence. Les ressources du Smithsonian consacrées au Cheval de Feu de 2026 mettent en avant le travail, le courage et la résilience.',
  'chineseZodiac.animals.horse.name': 'Cheval',
  'chineseZodiac.animals.monkey.association': 'Association traditionnelle : ingéniosité, jeu et adaptation rapide.',
  'chineseZodiac.animals.monkey.context': 'Le Singe est neuvième. Le folklore et les lectures populaires de la personnalité ajoutent des couches au-delà de l’animal calendaire ; elles ne sont pas uniformes dans toutes les communautés chinoises.',
  'chineseZodiac.animals.monkey.name': 'Singe',
  'chineseZodiac.animals.ox.association': 'Association traditionnelle : travail régulier, endurance et sens pratique des responsabilités.',
  'chineseZodiac.animals.ox.context': 'Dans l’art chinois, le Bœuf et le buffle d’eau peuvent relever de la même catégorie zodiacale. L’image met l’accent sur l’effort soutenu plutôt que sur la vitesse.',
  'chineseZodiac.animals.ox.name': 'Bœuf',
  'chineseZodiac.animals.pig.association': 'Association traditionnelle : abondance, générosité et accomplissement.',
  'chineseZodiac.animals.pig.context': 'Le Cochon clôt la séquence des animaux avant le retour au Rat. Boar et Pig figurent tous deux dans les références en anglais.',
  'chineseZodiac.animals.pig.name': 'Cochon',
  'chineseZodiac.animals.rabbit.association': 'Association traditionnelle : vigilance, grâce et mouvement mesuré.',
  'chineseZodiac.animals.rabbit.context': 'Les sources anglophones peuvent parler de Rabbit ou de Hare, soit le Lapin ou le Lièvre. Certaines traditions zodiacales régionales nomment un autre animal ; c’est notamment pour cela que ce guide reste propre au cycle chinois.',
  'chineseZodiac.animals.rabbit.name': 'Lapin',
  'chineseZodiac.animals.rat.association': 'Association traditionnelle : vigilance, faculté d’adaptation et aptitude à trouver une voie malgré les contraintes.',
  'chineseZodiac.animals.rat.context': 'Le Rat ouvre la séquence de douze ans. Les résumés modernes de personnalité le décrivent souvent comme débrouillard ; il s’agit d’une association culturelle, et non d’un trait mesuré.',
  'chineseZodiac.animals.rat.name': 'Rat',
  'chineseZodiac.animals.rooster.association': 'Association traditionnelle : diligence, mesure du temps et ardeur au travail.',
  'chineseZodiac.animals.rooster.context': 'The Met présente le lever matinal du coq comme l’origine de ses associations avec la diligence et le travail, tout en retraçant son long emploi comme motif artistique de bon augure.',
  'chineseZodiac.animals.rooster.name': 'Coq',
  'chineseZodiac.animals.snake.association': 'Association traditionnelle : perception, réserve et transformation.',
  'chineseZodiac.animals.snake.context': 'Le Serpent suit le Dragon dans le cycle. Les traits interprétatifs varient selon les sources, les familles et les régions ; sa place dans le calendrier est le fait stable.',
  'chineseZodiac.animals.snake.name': 'Serpent',
  'chineseZodiac.animals.tiger.association': 'Association traditionnelle : courage, force et protection.',
  'chineseZodiac.animals.tiger.context': 'Dans la culture visuelle chinoise, le Tigre relève autant de la protection que de l’audace. Les courtes listes de traits de personnalité ne rendent compte que d’un usage du symbole.',
  'chineseZodiac.animals.tiger.name': 'Tigre',
  'chineseZodiac.associationLabel': 'Association traditionnelle',
  'chineseZodiac.boundaryBody': 'Une année animale ne change pas le 1er janvier. Si une date de naissance tombe en janvier ou au début de février, vérifie la date du Nouvel An lunaire de cette année civile avant de choisir un animal. Les dates varient aussi selon les traditions asiatiques, et toutes les communautés n’emploient pas le même zodiaque.',
  'chineseZodiac.boundaryTitle': 'L’année commence au Nouvel An lunaire',
  'chineseZodiac.branchLabel': 'Branche terrestre',
  'chineseZodiac.chartLink': 'Calculer un thème astral tropical occidental',
  'chineseZodiac.historyBody': 'Les douze animaux sont associés aux douze Branches terrestres. Les traces historiques situent en Chine l’association entre animaux et calendrier dès le IIIe siècle av. J.-C., et elle est bien établie au Ier siècle de notre ère. Les branches se combinent aussi avec dix Tiges célestes pour former un cycle sexagésimal.',
  'chineseZodiac.historyTitle': 'Ce que consigne le cycle',
  'chineseZodiac.hubIntro': 'Une introduction rigoureuse au zodiaque chinois : la séquence de ses animaux, les tableaux d’années, le cadre historique et la limite qui ne tombe pas le 1er janvier.',
  'chineseZodiac.hubTitle': 'Le cycle des animaux sur douze ans.',
  'chineseZodiac.iconRailNote': 'Les disques colorés sont la marque des signes occidentaux de Zodiacs.org. Ils ne remplacent pas les animaux du zodiaque chinois et ne leur correspondent pas.',
  'chineseZodiac.itemLink': 'Lire l’année du zodiaque : {animal}',
  'chineseZodiac.kicker': 'Zodiaque chinois',
  'chineseZodiac.learnLabel': 'Comprendre',
  'chineseZodiac.limitsBody': 'L’animal annuel n’est qu’une couche du calendrier. Une lecture plus complète de l’astrologie chinoise peut aussi prendre en compte la Tige céleste et l’élément, le mois, le jour et l’heure. L’animal d’une année ne suffit ni à déterminer une personnalité ni à prédire un résultat.',
  'chineseZodiac.limitsTitle': 'Ce que cela indique — et n’indique pas',
  'chineseZodiac.metaAnimalDescription': '{animal} dans le zodiaque chinois : années du cycle, Branche terrestre {branch} ({pinyin}), associations traditionnelles et limite du Nouvel An lunaire.',
  'chineseZodiac.metaAnimalTitle': '{animal} — Années du zodiaque chinois | Zodiacs.org',
  'chineseZodiac.metaHubTitle': 'Zodiaque chinois — Les douze années animales | Zodiacs.org',
  'chineseZodiac.next': 'Animal suivant',
  'chineseZodiac.numberLabel': 'Nº {number}',
  'chineseZodiac.positionValue': '{position} sur 12',
  'chineseZodiac.previous': 'Animal précédent',
  'chineseZodiac.separateBody': 'L’astrologie tropicale occidentale situe les planètes dans douze secteurs de l’écliptique et utilise un instant de naissance précis. Ces pages sur le zodiaque chinois partent d’une année du calendrier luni-solaire et de sa branche animale. Les deux systèmes peuvent être étudiés côte à côte, mais l’un ne se convertit pas en l’autre.',
  'chineseZodiac.separateTitle': 'Un système distinct de l’astrologie tropicale occidentale',
  'chineseZodiac.sequenceLabel': 'Position dans la séquence',
  'chineseZodiac.sequenceTitle': 'Les douze animaux, dans l’ordre',
  'chineseZodiac.siteName': 'Zodiacs.org',
  'chineseZodiac.sourceMet': 'The Met — le calendrier des animaux sur douze ans et son histoire',
  'chineseZodiac.sourceMetBulletin': 'The Met Bulletin — animaux, branches et cycle sexagésimal',
  'chineseZodiac.sourceMetHub': 'The Met — histoire du cycle calendaire des douze animaux',
  'chineseZodiac.sourceSmithsonian': 'Smithsonian — séquence du zodiaque chinois et contexte du Nouvel An lunaire',
  'chineseZodiac.sourceSmithsonianHub': 'Smithsonian — Nouvel An lunaire et séquence zodiacale',
  'chineseZodiac.sourceTitle': 'Sources muséales et culturelles',
  'chineseZodiac.westernLink': 'Comprendre le fonctionnement des dates du zodiaque tropical occidental',
  'chineseZodiac.yearOf': 'Année du zodiaque : {animal}',
  'chineseZodiac.yearsBoundary': 'Ces libellés désignent l’année luni-solaire qui commence au cours de l’année grégorienne indiquée. Les naissances de janvier et du début de février peuvent relever de l’animal précédent.',
  'chineseZodiac.yearsLabel': 'Années du cycle',
  'chineseZodiac.yearsTitle': 'Années récentes et à venir du cycle',
  'programmatic.compatibilityPrefillCta': 'Ouvrir le calculateur avec {a} et {b} déjà chargés',

  // WS6 — widgets
  'widgets.accentLabel': 'Couleur d’accent',
  'widgets.backlinkNote': 'Le lien « Propulsé par Zodiacs.org » fait partie de chaque widget et ne peut pas être retiré.',
  'widgets.changePlace': 'Changer le lieu de naissance',
  'widgets.chartError': 'Impossible de calculer le thème dans ce navigateur.',
  'widgets.chartIntro': 'Soleil, Lune et ascendant — calculés ici en toute confidentialité.',
  'widgets.chartOption': 'Mini-thème astral',
  'widgets.chartPrivacy': 'Calculé sur cet appareil. Rien de ce qui est saisi ici n’est envoyé à une API de calcul astrologique.',
  'widgets.chartTitle': 'Mini-thème astral',
  'widgets.codeLabel': 'Code d’intégration',
  'widgets.computeAction': 'Trouver les trois piliers',
  'widgets.computing': 'Calcul en cours…',
  'widgets.copiedAction': 'Copié',
  'widgets.copyAction': 'Copier le code d’intégration',
  'widgets.darkOption': 'Sombre',
  'widgets.dateLabel': 'Date de naissance',
  'widgets.generatorTitle': 'Créer une intégration',
  'widgets.iframeOption': 'Iframe isolée',
  'widgets.illumination': '{percent} % éclairée',
  'widgets.lightOption': 'Clair',
  'widgets.modeLabel': 'Mode d’intégration',
  'widgets.moon': 'Lune',
  'widgets.moonOption': 'Phase de la Lune aujourd’hui',
  'widgets.moonSign': 'Lune en {sign}',
  'widgets.moonTitle': 'Phase de la Lune aujourd’hui',
  'widgets.noPlaces': 'Aucun lieu trouvé',
  'widgets.noRetrograde': 'Aucune planète rétrograde',
  'widgets.pageIntro': 'Trois outils astrologiques privés pour ton site. L’iframe est prioritaire ; le script monte le même document isolé. La mention Zodiacs.org reste.',
  'widgets.pageKicker': 'Widgets',
  'widgets.pageMetaDescription': 'Intègre une phase lunaire, le ciel actuel ou un mini-thème privé sur tout site. Iframe isolée ou script : les deux modes sont gratuits et gardent la mention Zodiacs.org.',
  'widgets.pageMetaTitle': 'Widgets gratuits — Lune, ciel et thème astral | Zodiacs.org',
  'widgets.pageTitle': 'Le ciel, sur ton site.',
  'widgets.phaseNames.First Quarter': 'Premier quartier',
  'widgets.phaseNames.Full Moon': 'Pleine Lune',
  'widgets.phaseNames.Last Quarter': 'Dernier quartier',
  'widgets.phaseNames.New Moon': 'Nouvelle Lune',
  'widgets.phaseNames.Waning Crescent': 'Dernier croissant',
  'widgets.phaseNames.Waning Gibbous': 'Lune gibbeuse décroissante',
  'widgets.phaseNames.Waxing Crescent': 'Premier croissant',
  'widgets.phaseNames.Waxing Gibbous': 'Lune gibbeuse croissante',
  'widgets.placeError': 'Impossible de charger l’index local des lieux.',
  'widgets.placeLabel': 'Lieu de naissance',
  'widgets.placePlaceholder': 'Commence à saisir une ville…',
  'widgets.planetNames.Jupiter': 'Jupiter',
  'widgets.planetNames.Mars': 'Mars',
  'widgets.planetNames.Mercury': 'Mercure',
  'widgets.planetNames.Moon': 'Lune',
  'widgets.planetNames.Neptune': 'Neptune',
  'widgets.planetNames.Pluto': 'Pluton',
  'widgets.planetNames.Saturn': 'Saturne',
  'widgets.planetNames.Sun': 'Soleil',
  'widgets.planetNames.Uranus': 'Uranus',
  'widgets.planetNames.Venus': 'Vénus',
  'widgets.poweredBy': 'Propulsé par Zodiacs.org',
  'widgets.previewTitle': 'Aperçu en direct',
  'widgets.privacyNote': "Le mini-thème est calculé dans son iframe : la date, l’heure et le lieu de naissance saisis ne sont envoyés nulle part, et le thème n’est jamais téléversé. Saisir un lieu déclenche toutefois le chargement d’une liste de villes depuis zodiacs.org, choisie selon la première lettre saisie : cette requête ne révèle donc qu’une lettre. Le chargement du widget est aussi une requête vers zodiacs.org, comme pour toute ressource intégrée : le navigateur révèle alors son adresse IP et l’origine de votre site. Ce sont des choses distinctes.",
  'widgets.requiresJavaScript': 'JavaScript est nécessaire au calcul, mais le formulaire reste privé et n’envoie aucune donnée de naissance.',
  'widgets.retrograde': 'Rétrogrades : {planets}',
  'widgets.retrogradeAbbreviation': 'Rx',
  'widgets.rising': 'Ascendant',
  'widgets.scriptOption': 'Intégration par script',
  'widgets.signNames.aquarius': 'Verseau',
  'widgets.signNames.aries': 'Bélier',
  'widgets.signNames.cancer': 'Cancer',
  'widgets.signNames.capricorn': 'Capricorne',
  'widgets.signNames.gemini': 'Gémeaux',
  'widgets.signNames.leo': 'Lion',
  'widgets.signNames.libra': 'Balance',
  'widgets.signNames.pisces': 'Poissons',
  'widgets.signNames.sagittarius': 'Sagittaire',
  'widgets.signNames.scorpio': 'Scorpion',
  'widgets.signNames.taurus': 'Taureau',
  'widgets.signNames.virgo': 'Vierge',
  'widgets.sizeNote': 'Les documents sont autonomes et ne chargent les modules de calcul plus lourds qu’après l’envoi d’un mini-thème.',
  'widgets.skyOption': 'Le ciel aujourd’hui',
  'widgets.skyTitle': 'Le ciel aujourd’hui',
  'widgets.sun': 'Soleil',
  'widgets.themeLabel': 'Thème visuel',
  'widgets.timeLabel': 'Heure de naissance',
  'widgets.widgetError': 'Choisis une date, une heure et un lieu de naissance complets.',
  'widgets.widgetLabel': 'Widget',
  'widgets.widgetTitleChart': 'Mini-thème astral — Zodiacs.org',
  'widgets.widgetTitleMoon': 'Phase de la Lune aujourd’hui — Zodiacs.org',
  'widgets.widgetTitleSky': 'Le ciel aujourd’hui — Zodiacs.org',

  // WS8 — wallet natal chart
  'walletChart.addressHelp': 'Formats acceptés : clé publique Solana base58 de 32 octets ou adresse Base 0x.',
  'walletChart.addressLabel': 'Adresse Solana ou Base',
  'walletChart.addressPlaceholder': 'Colle une adresse publique',
  'walletChart.applicationCategory': 'EntertainmentApplication',
  'walletChart.base': 'Base',
  'walletChart.boundary': 'Colle une adresse. Il n’y a aucune connexion au portefeuille, signature de message, autorisation, construction de transaction ou garde d’actifs.',
  'walletChart.breadcrumbPage': 'Thème natal de portefeuille',
  'walletChart.breadcrumbRegistry': 'Registre Zodiacs',
  'walletChart.calculate': 'Trouver le thème du portefeuille',
  'walletChart.calculating': 'Lecture de l’historique public…',
  'walletChart.cardBorn': 'Heure publique du thème · {time}',
  'walletChart.cardNoBirthplace': 'UTC · planètes seulement · aucun lieu de naissance',
  'walletChart.cardOwnerHighlight': 'Synastrie du propriétaire · {ownerBody} {aspect} {walletBody} du portefeuille · {orb}°',
  'walletChart.cardSymbolic': 'Contexte symbolique · lecture seule · aucun conseil financier',
  'walletChart.cardTitle': 'Thème natal de portefeuille',
  'walletChart.elementBalance': 'Équilibre des éléments parmi les signes détenus : {balance}.',
  'walletChart.entertainmentDisclosure': 'Uniquement à des fins de divertissement et de contexte symbolique.',
  'walletChart.financialDisclosure': 'Pas un conseil financier. Rien ici ne constitue une sollicitation, une recommandation ni une déclaration de valeur.',
  'walletChart.historyTooDeep': 'Cette adresse dépasse la limite configurée pour l’historique Solana. Il faut un fournisseur d’archives avec un budget de pages plus élevé ; aucun horodatage partiel n’est affiché.',
  'walletChart.intro': 'Un portefeuille possède une première heure de transaction enregistrée, mais aucun lieu de naissance. Cet instrument associe cet horodatage UTC public aux seules planètes dans les signes.',
  'walletChart.invalidResponse': 'Le fournisseur d’historique a renvoyé un résultat illisible. Réessaie plus tard.',
  'walletChart.kicker': 'Instrument du Registre · lecture seule',
  'walletChart.metaDescription': 'Colle une adresse Solana ou Base : son premier horodatage compatible sur la chaîne donne un thème symbolique des planètes. Sans connexion, signature ni transaction.',
  'walletChart.metaTitle': 'Thème natal d’adresse — Registre en lecture seule | Zodiacs.org',
  'walletChart.noJavaScript': 'JavaScript est nécessaire au calcul astronomique privé dans le navigateur. La recherche d’adresse et le calcul du thème ne s’exécutent pas sans ton action.',
  'walletChart.notFound': 'Introuvable dans le registre officiel Zodiacs.org.',
  'walletChart.officialHoldingsIntro': 'Une vérification des soldes en lecture seule a trouvé des actifs officiels du Registre pour ces signes :',
  'walletChart.officialHoldingsTitle': 'Contexte du Registre officiel',
  'walletChart.ownerCalculating': 'Calcul dans ce navigateur…',
  'walletChart.ownerCancel': 'Effacer la comparaison privée',
  'walletChart.ownerIntro': 'Tu peux calculer une synastrie limitée aux planètes avec ton instant de naissance. Le lieu sert uniquement à retrouver le fuseau horaire local historique.',
  'walletChart.ownerMissing': 'Saisis une date de naissance et choisis un lieu de naissance avant de lancer le calcul.',
  'walletChart.ownerPlaceHelp': 'Le lieu sélectionne le fuseau horaire historique dans les données locales des villes du site ; aucune coordonnée n’entre dans le thème.',
  'walletChart.ownerPrivacy': 'Ta date, ton heure et ton lieu de naissance, tes positions planétaires et ta synastrie restent dans ce navigateur. Ils ne sont jamais envoyés au point de terminaison de l’historique du portefeuille.',
  'walletChart.ownerStart': 'Comparer avec ton thème',
  'walletChart.ownerSubmit': 'Calculer la synastrie privée',
  'walletChart.ownerTimeHelp': 'Si l’heure est inconnue, le moteur utilise midi en heure locale et ne formule aucune conclusion sur les angles qui se déplacent rapidement.',
  'walletChart.ownerTitle': 'Toi × ton portefeuille',
  'walletChart.placementsIntro': 'Ces placements utilisent l’instant UTC renvoyé. Un ascendant et des maisons exigeraient un lieu de naissance, ce qu’un portefeuille n’a pas.',
  'walletChart.placementsTitle': 'Planètes dans les signes',
  'walletChart.privacyBody': 'Le serveur reçoit l’adresse publique collée et renvoie un horodatage public. Les données de naissance facultatives du propriétaire et tous les calculs astronomiques restent sur cet appareil.',
  'walletChart.privacyTitle': 'Ce qui quitte ton appareil',
  'walletChart.readOnlyDisclosure': 'Lecture seule par conception. Aucune garde d’actifs, signature, autorisation ou transaction.',
  'walletChart.registryBack': 'Retour au Registre Zodiacs',
  'walletChart.resultChain': 'Réseau',
  'walletChart.resultKicker': 'Reçu d’horodatage public',
  'walletChart.resultSource': 'Source de l’horodatage',
  'walletChart.resultTitle': '{address} correspond à {time}.',
  'walletChart.retrograde': 'rétrograde',
  'walletChart.share': 'Partager ce thème symbolique',
  'walletChart.shareComplete': 'Carte de partage prête.',
  'walletChart.shareError': 'Impossible de créer la carte de partage sur cet appareil.',
  'walletChart.sharing': 'Préparation de la carte privée…',
  'walletChart.solana': 'Solana',
  'walletChart.sourceBaseExplorer': 'Historique du compte dans l’explorateur Base',
  'walletChart.sourceBaseRpc': 'RPC d’archive Base · première activité sortante',
  'walletChart.sourceBaseRpcCaveat': 'Le RPC Base standard ne peut pas indexer les transferts entrants antérieurs. Cette solution de repli repère uniquement la première transaction sortante.',
  'walletChart.sourceSolana': 'Historique paginé des signatures Solana',
  'walletChart.supportedNetworks': 'Réseaux configurés : {networks}.',
  'walletChart.synastryBalance': 'Fluidité et tension sont représentées à parts égales dans les contacts serrés.',
  'walletChart.synastryCharge': 'Les contacts serrés penchent davantage vers la tension que vers la fluidité.',
  'walletChart.synastryContact': 'Ton thème : {ownerBody} · {aspect} · portefeuille : {walletBody} ({orb}° d’orbe).',
  'walletChart.synastryFlow': 'Les contacts serrés penchent davantage vers la fluidité que vers la tension.',
  'walletChart.synastryNoContact': 'Aucun aspect majeur ne se situe dans les orbes standard du moteur.',
  'walletChart.synastryTitle': 'Synastrie symbolique',
  'walletChart.title': 'Un thème symbolique pour une adresse publique.',
  'walletChart.unavailable': 'L’historique public de la chaîne est temporairement indisponible. Aucun statut d’identité ou de vérification n’a changé.',
  'walletChart.utcOnly': 'Heure UTC · aucun lieu de naissance · aucune maison ni aucun angle',
});
