import type { ReleasedLocale as Locale } from '../lib/i18n/core';

const COPY = {
  es: {
    metaTitle: 'Astrología del cumpleaños del {date} | Zodiacs.org',
    metaDescriptionSign: '{date}: signo solar {sign}, grados del Sol, decanato y datos de 1940–2030 calculados año por año.',
    metaDescriptionCusp: '{date}: límite entre {a} y {b}, con una tabla de 1940–2030 que muestra el signo y la hora exacta del cambio.',
    imageAlt: 'Astrología del cumpleaños del {date} — Zodiacs.org',
    kicker: 'Cumpleaños',
    bornOn: 'Nacer el {date}',
    sunSign: 'Signo solar',
    everyYear: 'todos los años, {from}–{to}',
    or: 'o',
    boundaryHere: 'el límite {a}–{b} cae en esta fecha',
    rangeSummary: 'día completo en {a}: {wholeA} años · día completo en {b}: {wholeB} · cambio durante el día: {split}',
    inYear: 'En {year}',
    allDay: '{sign} todo el día',
    untilThen: '{before} hasta las {time} UTC; después, {after}',
    sunDegrees: 'Grados del Sol',
    noonUtc: 'mediodía UTC, {from}–{to}',
    decan: 'Decanato',
    thisYear: 'Este año',
    sunMoon: '{date}, {year}: Sol {sun} · Luna en {moon} al mediodía UTC',
    decanSingle: '{ordinal} decanato de {sign} — regente tradicional {ruler}',
    decanSplit: 'entre el {lo} y el {hi} decanato de {sign} — la línea de {degree}° cae dentro del intervalo de esta fecha (regentes {rulerLo} / {rulerHi})',
    decanCusp: 'último decanato de {a} o primero de {b} — el ingreso lo decide',
    tableSummary: 'Tabla año por año, {from}–{to}',
    timeNote: 'Las horas están en tiempo universal; convierte tu hora de nacimiento antes de consultar tu año.',
    factsHeading: 'Lo que muestra esta fecha',
    factIntroSign: 'En todos los años de {from} a {to}, el Sol está en {sign} el {date}. El intervalo calculado al mediodía UTC va de {lo} a {hi}.',
    factIntroCusp: 'El {date} cae en el límite entre {a} y {b}. La tabla distingue los años de un solo signo de aquellos en los que el Sol cambia de signo durante el día.',
    factDegrees: 'El calendario se desplaza ligeramente respecto del Sol y se reajusta en los años bisiestos. Por eso el grado exacto depende del año y de la hora de nacimiento.',
    factMethod: 'Estos son datos astronómicos de la fecha, no una descripción de personalidad. Una carta natal añade la Luna, el ascendente, las casas y los aspectos de tu momento exacto.',
    faqHeading: 'La fecha, con respuestas',
    qSign: '¿Qué signo zodiacal corresponde al {date}?',
    qDecan: '¿Qué decanato corresponde al {date}?',
    qDegree: '¿En qué grado está el Sol el {date}?',
    aSign: '{sign}. Entre {from} y {to}, el Sol permanece en {sign} durante todo ese día.',
    aCusp: '{a} o {b}. Consulta tu año en la tabla; si el cambio ocurre ese día, tu hora de nacimiento en UTC decide el signo.',
    aDecanSingle: 'El {ordinal} decanato de {sign}, cuyo regente tradicional es {ruler}.',
    aDecanSplit: 'La fecha cruza la línea de {degree}°: según el año y la hora, el Sol cae en el {lo} o el {hi} decanato de {sign}.',
    aDecanCusp: 'El último decanato de {a} o el primero de {b}. El momento exacto del ingreso decide cuál.',
    aDegree: 'Entre {lo} y {hi} al mediodía UTC, según el año. Para conocer el grado exacto hacen falta la fecha, el año y la hora de nacimiento.',
    ctaTitle: 'La fecha te da el Sol. Para el resto hace falta una carta.',
    ctaBody: 'Luna, ascendente, casas y aspectos, calculados gratis en tu dispositivo a partir de tu momento exacto de nacimiento.',
    ctaAction: 'Calcula gratis tu carta natal',
    navAria: 'Fechas cercanas y lectura adicional',
    calendar: 'El calendario',
    allBirthdaysEnglish: 'Todos los cumpleaños (en inglés)',
    deeperInto: 'Más sobre {signs}',
    and: ' y ',
    guide: 'Guía de {sign}',
    share: 'Nacer el {date}: los datos astronómicos de esa fecha',
    ordinals: ['primer', 'segundo', 'tercer'],
  },
  pt: {
    metaTitle: 'Astrologia do aniversário de {date} | Zodiacs.org',
    metaDescriptionSign: '{date}: signo solar {sign}, graus do Sol, decanato e dados de 1940–2030 calculados ano a ano.',
    metaDescriptionCusp: '{date}: limite entre {a} e {b}, com uma tabela de 1940–2030 que mostra o signo e a hora exata da mudança.',
    imageAlt: 'Astrologia do aniversário de {date} — Zodiacs.org',
    kicker: 'Aniversários',
    bornOn: 'Nascer em {date}',
    sunSign: 'Signo solar',
    everyYear: 'todos os anos, {from}–{to}',
    or: 'ou',
    boundaryHere: 'o limite {a}–{b} cai nesta data',
    rangeSummary: 'dia inteiro em {a}: {wholeA} anos · dia inteiro em {b}: {wholeB} · mudança durante o dia: {split}',
    inYear: 'Em {year}',
    allDay: '{sign} o dia inteiro',
    untilThen: '{before} até as {time} UTC; depois, {after}',
    sunDegrees: 'Graus do Sol',
    noonUtc: 'meio-dia UTC, {from}–{to}',
    decan: 'Decanato',
    thisYear: 'Este ano',
    sunMoon: '{date}, {year}: Sol {sun} · Lua em {moon} ao meio-dia UTC',
    decanSingle: '{ordinal} decanato de {sign} — regente tradicional {ruler}',
    decanSplit: 'entre os decanatos {lo} e {hi} de {sign} — a linha de {degree}° cai dentro do intervalo desta data (regentes {rulerLo} / {rulerHi})',
    decanCusp: 'último decanato de {a} ou primeiro de {b} — o ingresso decide',
    tableSummary: 'Tabela ano a ano, {from}–{to}',
    timeNote: 'Os horários estão em tempo universal; converta sua hora de nascimento antes de consultar o seu ano.',
    factsHeading: 'O que esta data mostra',
    factIntroSign: 'Em todos os anos de {from} a {to}, o Sol está em {sign} no dia {date}. O intervalo calculado ao meio-dia UTC vai de {lo} a {hi}.',
    factIntroCusp: '{date} cai no limite entre {a} e {b}. A tabela separa os anos de um único signo daqueles em que o Sol muda de signo durante o dia.',
    factDegrees: 'O calendário se desloca um pouco em relação ao Sol e se reajusta nos anos bissextos. Por isso, o grau exato depende do ano e da hora de nascimento.',
    factMethod: 'Estes são dados astronômicos da data, não uma descrição de personalidade. Um mapa natal acrescenta a Lua, o ascendente, as casas e os aspectos do seu momento exato.',
    faqHeading: 'A data, com respostas',
    qSign: 'Qual é o signo de quem nasce em {date}?',
    qDecan: 'Qual é o decanato de {date}?',
    qDegree: 'Em que grau está o Sol em {date}?',
    aSign: '{sign}. Entre {from} e {to}, o Sol permanece em {sign} durante todo esse dia.',
    aCusp: '{a} ou {b}. Consulte o seu ano na tabela; se a mudança acontecer nesse dia, sua hora de nascimento em UTC decide o signo.',
    aDecanSingle: 'O {ordinal} decanato de {sign}, cujo regente tradicional é {ruler}.',
    aDecanSplit: 'A data cruza a linha de {degree}°: conforme o ano e a hora, o Sol cai no {lo} ou no {hi} decanato de {sign}.',
    aDecanCusp: 'O último decanato de {a} ou o primeiro de {b}. O momento exato do ingresso decide qual.',
    aDegree: 'Entre {lo} e {hi} ao meio-dia UTC, conforme o ano. Para saber o grau exato, são necessários a data, o ano e a hora de nascimento.',
    ctaTitle: 'A data mostra o Sol. O restante pede um mapa.',
    ctaBody: 'Lua, ascendente, casas e aspectos, calculados grátis no seu dispositivo a partir do momento exato do seu nascimento.',
    ctaAction: 'Calcule grátis o seu mapa natal',
    navAria: 'Datas próximas e leitura adicional',
    calendar: 'O calendário',
    allBirthdaysEnglish: 'Todos os aniversários (em inglês)',
    deeperInto: 'Mais sobre {signs}',
    and: ' e ',
    guide: 'Guia de {sign}',
    share: 'Nascer em {date}: os dados astronômicos dessa data',
    ordinals: ['primeiro', 'segundo', 'terceiro'],
  },
  fr: {
    metaTitle: 'Astrologie d’anniversaire du {date} | Zodiacs.org',
    metaDescriptionSign: '{date} : signe solaire {sign}, degrés du Soleil, décan et données 1940–2030 calculées année par année.',
    metaDescriptionCusp: '{date} : frontière entre {a} et {b}, avec un tableau 1940–2030 indiquant le signe et l’heure exacte du changement.',
    imageAlt: 'Astrologie d’anniversaire du {date} — Zodiacs.org',
    kicker: 'Anniversaires',
    bornOn: 'Naître le {date}',
    sunSign: 'Signe solaire',
    everyYear: 'chaque année, {from}–{to}',
    or: 'ou',
    boundaryHere: 'la frontière {a}–{b} tombe à cette date',
    rangeSummary: 'journée entière en {a} : {wholeA} ans · journée entière en {b} : {wholeB} · changement en cours de journée : {split}',
    inYear: 'En {year}',
    allDay: '{sign} toute la journée',
    untilThen: '{before} jusqu’à {time} UTC, puis {after}',
    sunDegrees: 'Degrés du Soleil',
    noonUtc: 'midi UTC, {from}–{to}',
    decan: 'Décan',
    thisYear: 'Cette année',
    sunMoon: '{date} {year} : Soleil {sun} · Lune en {moon} à midi UTC',
    decanSingle: '{ordinal} décan du signe {sign} — maître traditionnel : {ruler}',
    decanSplit: 'décans {lo}–{hi} du signe {sign} — la ligne des {degree}° traverse l’intervalle de cette date (maîtres {rulerLo} / {rulerHi})',
    decanCusp: 'dernier décan du signe {a} ou premier décan du signe {b} — l’ingrès tranche',
    tableSummary: 'Tableau année par année, {from}–{to}',
    timeNote: 'Les heures sont données en temps universel ; convertis ton heure de naissance avant de consulter ton année.',
    factsHeading: 'Ce que montre cette date',
    factIntroSign: 'Pour chaque année de {from} à {to}, le Soleil est en {sign} le {date}. L’intervalle calculé à midi UTC va de {lo} à {hi}.',
    factIntroCusp: 'Le {date} tombe sur la frontière entre {a} et {b}. Le tableau distingue les années d’un seul signe de celles où le Soleil change de signe en cours de journée.',
    factDegrees: 'Le calendrier se décale légèrement par rapport au Soleil et se recale lors des années bissextiles. Le degré exact dépend donc de l’année et de l’heure de naissance.',
    factMethod: 'Il s’agit de données astronomiques sur la date, pas d’un diagnostic de personnalité. Un thème astral ajoute la Lune, l’ascendant, les maisons et les aspects de ton moment exact.',
    faqHeading: 'Questions sur cette date',
    qSign: 'Quel signe correspond au {date} ?',
    qDecan: 'Quel décan correspond au {date} ?',
    qDegree: 'À quel degré se trouve le Soleil le {date} ?',
    aSign: '{sign}. Entre {from} et {to}, le Soleil reste en {sign} pendant toute cette date.',
    aCusp: '{a} ou {b}. Consulte ton année dans le tableau ; si le changement a lieu ce jour-là, ton heure de naissance en UTC détermine le signe.',
    aDecanSingle: 'Le {ordinal} décan du signe {sign}, dont le maître traditionnel est {ruler}.',
    aDecanSplit: 'La date traverse la ligne des {degree}° : selon l’année et l’heure, le Soleil tombe dans le {lo} ou le {hi} décan du signe {sign}.',
    aDecanCusp: 'Le dernier décan du signe {a} ou le premier décan du signe {b}. L’instant exact de l’ingrès détermine lequel.',
    aDegree: 'Entre {lo} et {hi} à midi UTC selon l’année. Pour connaître le degré exact, il faut la date, l’année et l’heure de naissance.',
    ctaTitle: 'La date donne le Soleil. Pour le reste, il faut un thème astral.',
    ctaBody: 'Lune, ascendant, maisons et aspects, calculés gratuitement sur ton appareil à partir de ton moment de naissance exact.',
    ctaAction: 'Calcule gratuitement ton thème astral',
    navAria: 'Dates voisines et lecture complémentaire',
    calendar: 'Le calendrier',
    allBirthdaysEnglish: 'Tous les anniversaires (en anglais)',
    deeperInto: 'À approfondir : {signs}',
    and: ' et ',
    guide: 'Guide du signe {sign}',
    share: 'Naître le {date} : les données astronomiques de cette date',
    ordinals: ['premier', 'deuxième', 'troisième'],
  },
  it: {
    metaTitle: 'Astrologia del compleanno del {date} | Zodiacs.org',
    metaDescriptionSign: '{date}: segno solare {sign}, gradi del Sole, decano e dati 1940–2030 calcolati anno per anno.',
    metaDescriptionCusp: '{date}: confine tra {a} e {b}, con una tabella 1940–2030 che mostra il segno e l’ora esatta del passaggio.',
    imageAlt: 'Astrologia del compleanno del {date} — Zodiacs.org',
    kicker: 'Compleanni',
    bornOn: 'Nascere il {date}',
    sunSign: 'Segno solare',
    everyYear: 'ogni anno, {from}–{to}',
    or: 'oppure',
    boundaryHere: 'il confine {a}–{b} cade in questa data',
    rangeSummary: 'giornata intera in {a}: {wholeA} anni · giornata intera in {b}: {wholeB} · passaggio durante il giorno: {split}',
    inYear: 'Nel {year}',
    allDay: '{sign} tutto il giorno',
    untilThen: '{before} fino alle {time} UTC, poi {after}',
    sunDegrees: 'Gradi del Sole',
    noonUtc: 'mezzogiorno UTC, {from}–{to}',
    decan: 'Decano',
    thisYear: 'Quest’anno',
    sunMoon: '{date} {year}: Sole {sun} · Luna in {moon} a mezzogiorno UTC',
    decanSingle: '{ordinal} decano di {sign} — governatore tradizionale {ruler}',
    decanSplit: '{lo}º–{hi}º decano di {sign} — la linea dei {degree}° cade nell’intervallo di questa data (governatori {rulerLo} / {rulerHi})',
    decanCusp: 'ultimo decano di {a} o primo di {b} — decide l’ingresso',
    tableSummary: 'Tabella anno per anno, {from}–{to}',
    timeNote: 'Gli orari sono in tempo universale; converti la tua ora di nascita prima di consultare il tuo anno.',
    factsHeading: 'Che cosa mostra questa data',
    factIntroSign: 'In ogni anno dal {from} al {to}, il Sole è in {sign} il {date}. L’intervallo calcolato a mezzogiorno UTC va da {lo} a {hi}.',
    factIntroCusp: 'Il {date} cade sul confine tra {a} e {b}. La tabella distingue gli anni con un solo segno da quelli in cui il Sole cambia segno durante la giornata.',
    factDegrees: 'Il calendario slitta leggermente rispetto al Sole e si riallinea negli anni bisestili. Per questo il grado esatto dipende dall’anno e dall’ora di nascita.',
    factMethod: 'Questi sono dati astronomici sulla data, non una diagnosi della personalità. Un tema natale aggiunge Luna, ascendente, case e aspetti del tuo momento esatto.',
    faqHeading: 'La data, con le risposte',
    qSign: 'Qual è il segno zodiacale del {date}?',
    qDecan: 'Qual è il decano del {date}?',
    qDegree: 'A quale grado si trova il Sole il {date}?',
    aSign: '{sign}. Tra il {from} e il {to}, il Sole rimane in {sign} per tutta questa data.',
    aCusp: '{a} oppure {b}. Cerca il tuo anno nella tabella; se il passaggio avviene quel giorno, decide la tua ora di nascita in UTC.',
    aDecanSingle: 'Il {ordinal} decano di {sign}, il cui governatore tradizionale è {ruler}.',
    aDecanSplit: 'La data attraversa la linea dei {degree}°: a seconda dell’anno e dell’ora, il Sole cade nel {lo}º o nel {hi}º decano di {sign}.',
    aDecanCusp: 'L’ultimo decano di {a} o il primo di {b}. Decide il momento esatto dell’ingresso.',
    aDegree: 'Tra {lo} e {hi} a mezzogiorno UTC, a seconda dell’anno. Per il grado esatto servono data, anno e ora di nascita.',
    ctaTitle: 'La data dà il Sole. Per il resto serve un tema.',
    ctaBody: 'Luna, ascendente, case e aspetti, calcolati gratis sul tuo dispositivo dal momento esatto della nascita.',
    ctaAction: 'Calcola gratis il tuo tema natale',
    navAria: 'Date vicine e letture di approfondimento',
    calendar: 'Il calendario',
    allBirthdaysEnglish: 'Tutti i compleanni (in inglese)',
    deeperInto: 'Approfondisci {signs}',
    and: ' e ',
    guide: 'Guida di {sign}',
    share: 'Nascere il {date}: i dati astronomici di questa data',
    ordinals: ['primo', 'secondo', 'terzo'],
  },
} as const satisfies Record<Exclude<Locale, 'en'>, Record<string, string | readonly string[]>>;

export type BirthdayLocale = keyof typeof COPY;
type BirthdayCopy = (typeof COPY)[BirthdayLocale];
export type BirthdayCopyKey = Exclude<keyof BirthdayCopy, 'ordinals'>;

export function birthdayText(
  locale: BirthdayLocale,
  key: BirthdayCopyKey,
  values: Record<string, string | number> = {},
): string {
  const template = COPY[locale][key] as string;
  return template.replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g, (token, name: string) => (
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : token
  ));
}

export function birthdayOrdinal(locale: BirthdayLocale, ordinal: 1 | 2 | 3): string {
  return COPY[locale].ordinals[ordinal - 1];
}
