// Generated by scripts/build-compute-handler.mjs. Do not edit.
// Declarations for the bundle beside this file; the source is src/lib/compute-api/handler.ts.
export { createComputeApiHandler } from '../../src/lib/compute-api/handler.js';
