// Generated by scripts/build-compute-local-time.mjs. Do not edit.
// Each call owns its resolver caches; a completed request must dispose them.
import type { LocalTimeModule } from '../../src/lib/compute-api/local-time.js';
export declare function createLocalTimeModule(): LocalTimeModule & { dispose(): void };
