// Generated by scripts/build-compute-local-time.mjs. Do not edit.
// Declarations for the bundle beside this file; the source is src/lib/time/localToUtc.ts.
export declare function prepareLocalTime(date: string, timeZone: string): Promise<void>;
export declare function resolveLocalToUtc(
  date: string,
  time: string,
  timeZone: string,
  options?: { longitude?: number },
): {
  utc: Date;
  offsetMinutes: number;
  flags: ('dst-gap' | 'dst-fold' | 'lmt')[];
  localMeanTime?: { longitude: number; zoneOffsetMinutes: number };
};
export declare function loadZoneHistory(
  name: string,
): Promise<{ readonly t: readonly number[]; readonly o: readonly (number | null)[] } | null>;
export declare function canonicalZoneName(name: string): Promise<string | null>;
