// Generated by scripts/build-time-basis.mjs. Do not edit.
// Declarations for the bundle beside this file: the engine's own time basis and frame of date.
import type { DeltaT } from '@zodiacs/engine/deltat';
import type { TimeScale, TimeScaleName } from '@zodiacs/engine';

/** An instant's UT1 and TT, days since 2000-01-01T12:00 on each scale, with the record a chart carries. */
export interface TimeBasis {
  /** The UTC instant, ms; where the civil instant is read as UT1, that instant. */
  utcMs: number;
  ut1Days: number;
  ttDays: number;
  deltaT: DeltaT;
  timeScale: TimeScale;
}

/** UT1 and TT for an instant (ms) on `scale`; a pin is a caller's ΔT (TT − UT1) in seconds. */
export declare function timeBasis(ms: number, scale?: TimeScaleName, pin?: number): TimeBasis;

/**
 * The time between two samples taken `days` apart on an input's scale, in days:
 * `days` where both lie in one piece of the time basis, else the TT between them.
 */
export declare function elapsedDays(before: TimeBasis, after: TimeBasis, days: number): number;

/** The span astronomy-engine tabulates, as the root entry exports it: TT days from J2000.0, inclusive. */
export declare const EPHEMERIS_SPAN: Readonly<{
  timeScale: 'TT';
  daysFromJ2000: Readonly<{ from: number; to: number }>;
  fromTT: string;
  toTT: string;
}>;

/** The nutation and obliquity at a TT instant (days from J2000.0), IAU 2000B. */
export interface Tilt {
  /** Nutation in longitude, arcseconds. */
  dpsi: number;
  /** Nutation in obliquity, arcseconds. */
  deps: number;
  /** Mean obliquity of date, degrees. */
  mobl: number;
  /** True obliquity of date, degrees. */
  tobl: number;
  /** Equation of the equinoxes, arcseconds. */
  ee: number;
}

/** From the J2000 mean equator (astronomy-engine's EQJ) to the mean ecliptic of date, with that instant's tilt. */
export interface EclipticFrame {
  /** TT, days from J2000.0. */
  readonly tt: number;
  /** The rotation, row by row. */
  readonly rows: readonly number[];
  readonly tilt: Tilt;
}

/** The nutation and obliquity at `tt`, TT days from J2000.0. */
export declare function tilt(tt: number): Tilt;

/** The frame at `tt`, TT days from J2000.0 (astronomy-engine's `time.tt`). */
export declare function eclipticFrame(tt: number): EclipticFrame;

/** An EQJ vector on the mean ecliptic and equinox of date, [x, y, z]. */
export declare function meanEcliptic(frame: EclipticFrame, x: number, y: number, z: number): [number, number, number];

/** An EQJ vector's longitude and latitude on the true ecliptic and equinox of date at `tt`, degrees. */
export declare function eclipticOfDate(x: number, y: number, z: number, tt: number): { lon: number; lat: number };
