// Generated by scripts/build-time-basis.mjs. Do not edit.
// Declarations for the bundle beside this file: the engine's own time basis.
import type { DeltaT } from '@zodiacs/engine/deltat';
import type { TimeScale, TimeScaleName } from '@zodiacs/engine';

/** An instant's UT1 and TT, days since 2000-01-01T12:00 on each scale, with the record a chart carries. */
export interface TimeBasis {
  /** The UTC instant, ms; where the civil instant is read as UT1, that instant. */
  utcMs: number;
  ut1Days: number;
  ttDays: number;
  deltaT: DeltaT;
  timeScale: TimeScale;
}

/** UT1 and TT for an instant (ms) on `scale`; a pin is a caller's ΔT (TT − UT1) in seconds. */
export declare function timeBasis(ms: number, scale?: TimeScaleName, pin?: number): TimeBasis;

/**
 * The time between two samples taken `days` apart on an input's scale, in days:
 * `days` where both lie in one piece of the time basis, else the TT between them.
 */
export declare function elapsedDays(before: TimeBasis, after: TimeBasis, days: number): number;

/** The span astronomy-engine tabulates, as the root entry exports it: TT days from J2000.0, inclusive. */
export declare const EPHEMERIS_SPAN: Readonly<{
  timeScale: 'TT';
  daysFromJ2000: Readonly<{ from: number; to: number }>;
  fromTT: string;
  toTT: string;
}>;
