/** English-only Phase 3 capture copy; selected only while the daily flag is complete. */
export const DAILY_CAPTURE_EN = {
  kicker: 'Free daily horoscope',
  title: 'Your day ahead.',
  personalTitle: 'Your {sign} day ahead.',
  copy: 'Each morning, the day’s reading for your sign — one email, free, unsubscribe anytime.',
  emailLabel: 'Email address',
  emailPlaceholder: 'you@example.com',
  signLegend: 'Your Sun sign',
  usingSign: 'Using your Sun sign: {sign}',
  changeSign: 'Change',
  submit: 'Email my daily horoscope',
  submitting: 'Subscribing…',
  success: 'You’re set. If confirmation or a change is needed, check your inbox.',
  missingSign: 'Choose your Sun sign so we can send its daily horoscope.',
  invalidEmail: 'That email address doesn’t look complete.',
  error: "Couldn't start the subscription. Please try again.",
  privacy: 'We store your email and your chosen sign — nothing else. Never your birth details.',
  honeypot: 'Leave this field blank',
  footerTitle: 'The daily, by email.',
  footerCopy: 'Your sign’s reading each morning. Free, unsubscribe anytime.',
} as const;
