import type { ChartContext, ContextPlacement } from '../../lib/chart-context';
import { planetLabel } from '../../lib/i18n/astrology';
import type { CatalogLocale } from '../../lib/i18n';
import { signBySlug, signName } from '../../lib/signs';
export type ContextSection = 'shape' | 'rulers' | 'dispositors' | 'dignities';
export const CONTEXT_SECTIONS: ContextSection[] = ['shape','rulers','dispositors','dignities'];
const en = {
  title:'Shape and classical rulers', shape:'Chart shape', rulers:'Chart and house rulers', dispositors:'Dispositors', dignities:'Classical dignities',
  unavailable:'Unavailable from these chart facts', reference:'Reference positions only; birth time unknown. These facts have not been established across the whole birth day.',
  noClear:'No clear shape', unknownSign:'Sign unresolved', noLabels:'None of these four labels', notCovered:'Not covered by the classical seven-planet table',
  chartRuler:'Classical chart ruler', house:'House', show:'Show on chart', final:'Final dispositor', noFinal:'No single established final dispositor',
  self:'Own domicile', mutual:'Mutual reception by domicile', cycle:'Closed chain', incomplete:'Incomplete chain', system:'Calculated house system',
  largestGap:'Largest empty arc', span:'Occupied span', grid:'Measurements rounded to', band:'Margin around each threshold', convention:'Convention',
  definition:'These traditional labels describe a planet’s relationship to a sign. They do not measure a person’s worth, ability or future.',
  graphDefinition:'Each arrow leads to the classical ruler of the preceding planet’s sign. Only the seven classical planets participate. An exaltation is not a domicile.',
  shapeDefinition:'Ten planets, Sun through Pluto, use their original positions with equal weight. Nodes, houses, angles and displaced glyphs do not enter this measurement.',
  sourceNotice:'Missing time, place or valid cusps withholds the affected ruler facts. The chart ruler and final dispositor are different concepts.',
  create:'Create image', close:'Close image', save:'Save image', share:'Share image', preparing:'Preparing image…', ready:'Image ready.', failed:'The image could not be prepared. Your chart remains available. Try again.',
  shared:'Image shared.', downloaded:'Image download started.', deliveryFailed:'The image could not be delivered. Try Save image.',
  whole:'Whole sign', placidus:'Placidus', domicile:'Domicile', exaltation:'Exaltation', detriment:'Detriment', fall:'Fall',
  bundle:'Bundle', bowl:'Bowl', locomotive:'Locomotive', bucket:'Bucket', seesaw:'Seesaw', splash:'Splash',
  near:'Near a threshold', ambiguous:'More than one qualifying membership', outside:'Outside these conventions', handle:'Handle',
};
export type ContextCopy = Record<keyof typeof en,string>;
export const CONTEXT_COPY: Record<CatalogLocale,ContextCopy> = {
  en,
  es:{title:'Forma y regentes clásicos',shape:'Forma de la carta',rulers:'Regentes de la carta y las casas',dispositors:'Dispositores',dignities:'Dignidades clásicas',
    unavailable:'No disponible con estos datos',reference:'Solo posiciones de referencia; hora de nacimiento desconocida. Estos datos no se han establecido para todo el día de nacimiento.',
    noClear:'Sin forma clara',unknownSign:'Signo sin resolver',noLabels:'Ninguna de estas cuatro etiquetas',notCovered:'Fuera de la tabla clásica de siete planetas',chartRuler:'Regente clásico de la carta',house:'Casa',show:'Mostrar en la carta',final:'Dispositor final',noFinal:'Sin un único dispositor final establecido',
    self:'Domicilio propio',mutual:'Recepción mutua por domicilio',cycle:'Cadena cerrada',incomplete:'Cadena incompleta',system:'Sistema de casas calculado',largestGap:'Mayor arco vacío',span:'Arco ocupado',grid:'Medidas redondeadas a',band:'Margen de cada umbral',convention:'Convención',
    definition:'Estas etiquetas tradicionales describen la relación de un planeta con un signo. No miden el valor, la capacidad ni el futuro de una persona.',graphDefinition:'Cada flecha lleva al regente clásico del signo del planeta anterior. Solo participan los siete planetas clásicos. Una exaltación no es un domicilio.',shapeDefinition:'Diez planetas, del Sol a Plutón, usan sus posiciones originales con el mismo peso. Los nodos, las casas, los ángulos y los glifos desplazados no intervienen.',sourceNotice:'La falta de hora, lugar o cúspides válidas impide establecer los regentes afectados. El regente de la carta y el dispositor final son conceptos distintos.',
    create:'Crear imagen',close:'Cerrar imagen',save:'Guardar imagen',share:'Compartir imagen',preparing:'Preparando imagen…',ready:'Imagen lista.',failed:'No se pudo preparar la imagen. Tu carta sigue disponible. Inténtalo de nuevo.',shared:'Imagen compartida.',downloaded:'Descarga de imagen iniciada.',deliveryFailed:'No se pudo entregar la imagen. Prueba Guardar imagen.',whole:'Signos completos',placidus:'Placidus',domicile:'Domicilio',exaltation:'Exaltación',detriment:'Detrimento',fall:'Caída',bundle:'Racimo',bowl:'Cuenco',locomotive:'Locomotora',bucket:'Cubo',seesaw:'Balancín',splash:'Dispersión',near:'Cerca de un umbral',ambiguous:'Más de una agrupación válida',outside:'Fuera de estas convenciones',handle:'Asa'},
  pt:{title:'Forma e regentes clássicos',shape:'Forma do mapa',rulers:'Regentes do mapa e das casas',dispositors:'Dispositores',dignities:'Dignidades clássicas',
    unavailable:'Indisponível com estes dados',reference:'Apenas posições de referência; hora de nascimento desconhecida. Estes dados não foram estabelecidos para todo o dia de nascimento.',
    noClear:'Sem forma clara',unknownSign:'Signo não determinado',noLabels:'Nenhum destes quatro rótulos',notCovered:'Fora da tabela clássica de sete planetas',chartRuler:'Regente clássico do mapa',house:'Casa',show:'Mostrar no mapa',final:'Dispositor final',noFinal:'Sem um único dispositor final estabelecido',self:'Domicílio próprio',mutual:'Recepção mútua por domicílio',cycle:'Cadeia fechada',incomplete:'Cadeia incompleta',system:'Sistema de casas calculado',largestGap:'Maior arco vazio',span:'Arco ocupado',grid:'Medidas arredondadas para',band:'Margem de cada limiar',convention:'Convenção',
    definition:'Estes rótulos tradicionais descrevem a relação de um planeta com um signo. Não medem o valor, a capacidade ou o futuro de uma pessoa.',graphDefinition:'Cada seta leva ao regente clássico do signo do planeta anterior. Participam apenas os sete planetas clássicos. Uma exaltação não é um domicílio.',shapeDefinition:'Dez planetas, do Sol a Plutão, usam as posições originais com o mesmo peso. Nodos, casas, ângulos e glifos deslocados não entram nesta medida.',sourceNotice:'A falta de hora, lugar ou cúspides válidas impede estabelecer os regentes afetados. O regente do mapa e o dispositor final são conceitos distintos.',
    create:'Criar imagem',close:'Fechar imagem',save:'Guardar imagem',share:'Partilhar imagem',preparing:'A preparar imagem…',ready:'Imagem pronta.',failed:'Não foi possível preparar a imagem. O mapa continua disponível. Tente novamente.',shared:'Imagem partilhada.',downloaded:'Download da imagem iniciado.',deliveryFailed:'Não foi possível entregar a imagem. Tente Guardar imagem.',whole:'Signos inteiros',placidus:'Placidus',domicile:'Domicílio',exaltation:'Exaltação',detriment:'Detrimento',fall:'Queda',bundle:'Feixe',bowl:'Taça',locomotive:'Locomotiva',bucket:'Balde',seesaw:'Gangorra',splash:'Dispersão',near:'Perto de um limiar',ambiguous:'Mais de um agrupamento válido',outside:'Fora destas convenções',handle:'Alça'},
  fr:{title:'Forme et maîtres classiques',shape:'Forme du thème',rulers:'Maîtres du thème et des maisons',dispositors:'Dispositeurs',dignities:'Dignités classiques',
    unavailable:'Indisponible avec ces données',reference:'Positions de référence uniquement ; heure de naissance inconnue. Ces données ne sont pas établies pour toute la journée de naissance.',
    noClear:'Aucune forme nette',unknownSign:'Signe indéterminé',noLabels:'Aucune de ces quatre étiquettes',notCovered:'Hors de la table classique des sept planètes',chartRuler:'Maître classique du thème',house:'Maison',show:'Montrer sur le thème',final:'Dispositeur final',noFinal:'Aucun dispositeur final unique établi',self:'Domicile propre',mutual:'Réception mutuelle par domicile',cycle:'Chaîne fermée',incomplete:'Chaîne incomplète',system:'Système de maisons calculé',largestGap:'Plus grand arc vide',span:'Arc occupé',grid:'Mesures arrondies à',band:'Marge autour de chaque seuil',convention:'Convention',
    definition:'Ces étiquettes traditionnelles décrivent le rapport entre une planète et un signe. Elles ne mesurent ni la valeur, ni les capacités, ni l’avenir d’une personne.',graphDefinition:'Chaque flèche mène au maître classique du signe de la planète précédente. Seules les sept planètes classiques participent. Une exaltation n’est pas un domicile.',shapeDefinition:'Dix planètes, du Soleil à Pluton, utilisent leurs positions originales avec le même poids. Les nœuds, maisons, angles et glyphes déplacés ne participent pas à cette mesure.',sourceNotice:'Sans heure, lieu ou cuspides valides, les maîtrises concernées restent indéterminées. Le maître du thème et le dispositeur final sont deux notions distinctes.',
    create:'Créer une image',close:'Fermer l’image',save:'Enregistrer l’image',share:'Partager l’image',preparing:'Préparation de l’image…',ready:'Image prête.',failed:'Impossible de préparer l’image. Le thème reste disponible. Réessayez.',shared:'Image partagée.',downloaded:'Téléchargement de l’image lancé.',deliveryFailed:'Impossible de transmettre l’image. Essayez de l’enregistrer.',whole:'Signes entiers',placidus:'Placidus',domicile:'Domicile',exaltation:'Exaltation',detriment:'Exil',fall:'Chute',bundle:'Grappe',bowl:'Bol',locomotive:'Locomotive',bucket:'Seau',seesaw:'Balançoire',splash:'Éclaboussure',near:'Près d’un seuil',ambiguous:'Plusieurs groupements admissibles',outside:'Hors de ces conventions',handle:'Anse'},
  it:{title:'Forma e governatori classici',shape:'Forma del tema',rulers:'Governatori del tema e delle case',dispositors:'Dispositori',dignities:'Dignità classiche',
    unavailable:'Non disponibile con questi dati',reference:'Solo posizioni di riferimento; ora di nascita sconosciuta. Questi dati non sono stabiliti per tutta la giornata di nascita.',
    noClear:'Nessuna forma chiara',unknownSign:'Segno non determinato',noLabels:'Nessuna di queste quattro etichette',notCovered:'Fuori dalla tabella classica dei sette pianeti',chartRuler:'Governatore classico del tema',house:'Casa',show:'Mostra nel tema',final:'Dispositore finale',noFinal:'Nessun unico dispositore finale stabilito',self:'Domicilio proprio',mutual:'Mutua ricezione per domicilio',cycle:'Catena chiusa',incomplete:'Catena incompleta',system:'Sistema di case calcolato',largestGap:'Arco vuoto maggiore',span:'Arco occupato',grid:'Misure arrotondate a',band:'Margine intorno a ogni soglia',convention:'Convenzione',
    definition:'Queste etichette tradizionali descrivono la relazione tra un pianeta e un segno. Non misurano il valore, le capacità o il futuro di una persona.',graphDefinition:'Ogni freccia porta al governatore classico del segno del pianeta precedente. Partecipano solo i sette pianeti classici. Un’esaltazione non è un domicilio.',shapeDefinition:'Dieci pianeti, dal Sole a Plutone, usano le posizioni originali con lo stesso peso. Nodi, case, angoli e glifi spostati non entrano in questa misura.',sourceNotice:'Senza ora, luogo o cuspidi valide, i governatori interessati non si possono stabilire. Il governatore del tema e il dispositore finale sono concetti diversi.',
    create:'Crea immagine',close:'Chiudi immagine',save:'Salva immagine',share:'Condividi immagine',preparing:'Preparazione immagine…',ready:'Immagine pronta.',failed:'Impossibile preparare l’immagine. Il tema resta disponibile. Riprova.',shared:'Immagine condivisa.',downloaded:'Download dell’immagine avviato.',deliveryFailed:'Impossibile inviare l’immagine. Prova Salva immagine.',whole:'Segni interi',placidus:'Placidus',domicile:'Domicilio',exaltation:'Esaltazione',detriment:'Esilio',fall:'Caduta',bundle:'Grappolo',bowl:'Coppa',locomotive:'Locomotiva',bucket:'Secchio',seesaw:'Altalena',splash:'Sparso',near:'Vicino a una soglia',ambiguous:'Più raggruppamenti validi',outside:'Fuori da queste convenzioni',handle:'Manico'},
  ru:{title:'Форма и классические управители',shape:'Форма карты',rulers:'Управители карты и домов',dispositors:'Диспозиторы',dignities:'Классические достоинства',
    unavailable:'Недоступно по этим данным',reference:'Только опорные положения; время рождения неизвестно. Эти данные не установлены для всего дня рождения.',
    noClear:'Нет чёткой формы',unknownSign:'Знак не установлен',noLabels:'Нет ни одной из этих четырёх меток',notCovered:'Не входит в классическую таблицу семи планет',chartRuler:'Классический управитель карты',house:'Дом',show:'Показать на карте',final:'Конечный диспозитор',noFinal:'Единый конечный диспозитор не установлен',self:'Собственная обитель',mutual:'Взаимная рецепция по обители',cycle:'Замкнутая цепочка',incomplete:'Неполная цепочка',system:'Рассчитанная система домов',largestGap:'Наибольшая пустая дуга',span:'Занятая дуга',grid:'Округление измерений до',band:'Отступ от каждого порога',convention:'Правило',
    definition:'Эти традиционные метки описывают связь планеты со знаком. Они не измеряют ценность, способности или будущее человека.',graphDefinition:'Каждая стрелка ведёт к классическому управителю знака предыдущей планеты. Участвуют только семь классических планет. Экзальтация не означает обитель.',shapeDefinition:'Десять планет, от Солнца до Плутона, учитываются по исходным положениям с равным весом. Узлы, дома, углы и смещённые символы в измерении не участвуют.',sourceNotice:'Без времени, места или достоверных куспидов соответствующие управители не определяются. Управитель карты и конечный диспозитор — разные понятия.',
    create:'Создать изображение',close:'Закрыть изображение',save:'Сохранить изображение',share:'Поделиться изображением',preparing:'Подготовка изображения…',ready:'Изображение готово.',failed:'Не удалось подготовить изображение. Карта по-прежнему доступна. Попробуйте снова.',shared:'Изображение отправлено.',downloaded:'Скачивание изображения началось.',deliveryFailed:'Не удалось отправить изображение. Попробуйте сохранить его.',whole:'Целые знаки',placidus:'Плацидус',domicile:'Обитель',exaltation:'Экзальтация',detriment:'Изгнание',fall:'Падение',bundle:'Связка',bowl:'Чаша',locomotive:'Локомотив',bucket:'Корзина',seesaw:'Качели',splash:'Брызги',near:'Рядом с порогом',ambiguous:'Несколько допустимых группировок',outside:'Вне этих правил',handle:'Ручка'},
};
export const SHAPE_RULE_COPY: Record<CatalogLocale, string[]> = {
  en:['Bundle: occupied span ≤120°.', 'Bowl: span 150°–180°; internal gaps ≤60°.', 'Locomotive: span 225°–255°; internal gaps ≤60°.', 'Bucket: one unique handle; nine planets span 120°–180°, internal gaps ≤60°, separating gaps ≥60°, handle within 30° of opposition to the arc midpoint.', 'Seesaw: two groups of 3–7 planets, each spanning ≤90°; internal gaps ≤60°, separating gaps ≥60°, midpoints within 30° of opposition.', 'Splash: every cyclic gap ≤60°.', 'A clear result must meet exactly one tightened rule with no competing relaxed candidate. Each angular threshold has a 2° exclusion band; this is a product convention, not an error estimate.'],
  es:['Racimo: arco ocupado ≤120°.', 'Cuenco: arco 150°–180°; huecos internos ≤60°.', 'Locomotora: arco 225°–255°; huecos internos ≤60°.', 'Cubo: una única asa; nueve planetas en 120°–180°, huecos internos ≤60°, separaciones ≥60°, asa a ≤30° de la oposición al centro del arco.', 'Balancín: dos grupos de 3–7 planetas, cada uno en ≤90°; huecos internos ≤60°, separaciones ≥60°, centros a ≤30° de la oposición.', 'Dispersión: todos los huecos circulares ≤60°.', 'Una forma clara cumple una sola regla estricta sin otra candidata relajada. Cada umbral angular tiene una banda de exclusión de 2°; es una convención del producto, no una estimación de error.'],
  pt:['Feixe: arco ocupado ≤120°.', 'Taça: arco 150°–180°; intervalos internos ≤60°.', 'Locomotiva: arco 225°–255°; intervalos internos ≤60°.', 'Balde: uma única alça; nove planetas em 120°–180°, intervalos internos ≤60°, separações ≥60°, alça a ≤30° da oposição ao centro do arco.', 'Gangorra: dois grupos de 3–7 planetas, cada um em ≤90°; intervalos internos ≤60°, separações ≥60°, centros a ≤30° da oposição.', 'Dispersão: todos os intervalos circulares ≤60°.', 'Uma forma clara cumpre uma única regra estrita sem outra candidata relaxada. Cada limiar angular tem uma faixa de exclusão de 2°; é uma convenção do produto, não uma estimativa de erro.'],
  fr:['Grappe : arc occupé ≤120°.', 'Bol : arc 150°–180° ; écarts internes ≤60°.', 'Locomotive : arc 225°–255° ; écarts internes ≤60°.', 'Seau : une seule anse ; neuf planètes sur 120°–180°, écarts internes ≤60°, séparations ≥60°, anse à ≤30° de l’opposition au milieu de l’arc.', 'Balançoire : deux groupes de 3–7 planètes, chacun sur ≤90° ; écarts internes ≤60°, séparations ≥60°, milieux à ≤30° de l’opposition.', 'Éclaboussure : tous les écarts circulaires ≤60°.', 'Une forme nette respecte une seule règle resserrée sans autre candidate élargie. Chaque seuil angulaire a une bande d’exclusion de 2° ; c’est une convention du produit, pas une estimation d’erreur.'],
  it:['Grappolo: arco occupato ≤120°.', 'Coppa: arco 150°–180°; spazi interni ≤60°.', 'Locomotiva: arco 225°–255°; spazi interni ≤60°.', 'Secchio: un solo manico; nove pianeti in 120°–180°, spazi interni ≤60°, separazioni ≥60°, manico entro 30° dall’opposizione al centro dell’arco.', 'Altalena: due gruppi di 3–7 pianeti, ciascuno in ≤90°; spazi interni ≤60°, separazioni ≥60°, centri entro 30° dall’opposizione.', 'Sparso: tutti gli spazi circolari ≤60°.', 'Una forma chiara soddisfa una sola regola ristretta senza altre candidate allargate. Ogni soglia angolare ha una fascia di esclusione di 2°; è una convenzione del prodotto, non una stima dell’errore.'],
  ru:['Связка: занятая дуга ≤120°.', 'Чаша: дуга 150°–180°; внутренние промежутки ≤60°.', 'Локомотив: дуга 225°–255°; внутренние промежутки ≤60°.', 'Корзина: единственная ручка; девять планет на дуге 120°–180°, внутренние промежутки ≤60°, разделяющие промежутки ≥60°, ручка в пределах 30° от оппозиции к середине дуги.', 'Качели: две группы по 3–7 планет, каждая на дуге ≤90°; внутренние промежутки ≤60°, разделяющие промежутки ≥60°, середины в пределах 30° от оппозиции.', 'Брызги: все круговые промежутки ≤60°.', 'Чёткая форма должна соответствовать одному ужесточённому правилу без конкурирующего ослабленного варианта. У каждого углового порога есть полоса исключения 2°; это правило продукта, а не оценка погрешности.'],
};
export const DIGNITY_RULE_COPY:Record<CatalogLocale,string[]>={
  en:['Domicile: a sign the planet rules in the classical system.','Exaltation: a traditional sign of special association with the planet.','Detriment: the sign opposite a classical domicile.','Fall: the sign opposite an exaltation. These four labels do not cover every traditional dignity.'],
  es:['Domicilio: un signo regido por el planeta en el sistema clásico.','Exaltación: un signo tradicionalmente asociado de manera especial con el planeta.','Detrimento: el signo opuesto a un domicilio clásico.','Caída: el signo opuesto a una exaltación. Estas cuatro etiquetas no abarcan todas las dignidades tradicionales.'],
  pt:['Domicílio: um signo regido pelo planeta no sistema clássico.','Exaltação: um signo tradicionalmente associado de modo especial ao planeta.','Detrimento: o signo oposto a um domicílio clássico.','Queda: o signo oposto a uma exaltação. Estes quatro rótulos não abrangem todas as dignidades tradicionais.'],
  fr:['Domicile : un signe gouverné par la planète dans le système classique.','Exaltation : un signe traditionnellement associé de manière particulière à la planète.','Exil : le signe opposé à un domicile classique.','Chute : le signe opposé à une exaltation. Ces quatre étiquettes ne couvrent pas toutes les dignités traditionnelles.'],
  it:['Domicilio: un segno governato dal pianeta nel sistema classico.','Esaltazione: un segno tradizionalmente associato in modo particolare al pianeta.','Esilio: il segno opposto a un domicilio classico.','Caduta: il segno opposto a un’esaltazione. Queste quattro etichette non comprendono tutte le dignità tradizionali.'],
  ru:['Обитель: знак, которым планета управляет в классической системе.','Экзальтация: знак особой традиционной связи с планетой.','Изгнание: знак напротив классической обители.','Падение: знак напротив экзальтации. Эти четыре метки не охватывают все традиционные достоинства.'],
};
export function placementText(p: ContextPlacement, locale: CatalogLocale): string {
  const c=CONTEXT_COPY[locale];
  const sign=p.sign ? signName(signBySlug(p.sign),locale) : `${c.unknownSign}${p.conditionalSigns.length?`: ${p.conditionalSigns.map(s=>signName(signBySlug(s),locale)).join(' / ')}`:''}`;
  return `${planetLabel(locale,p.body)} · ${sign}${p.house ? ` · ${c.house} ${p.house}` : ''}`;
}
/** The UI and each image share these factual lines; no source identity is exported. */
export function contextSectionLines(model: ChartContext, section: ContextSection, locale: CatalogLocale): string[] {
  const c=CONTEXT_COPY[locale], lines:string[]=[];
  if (!model.timeKnown) lines.push(c.reference);
  if (section==='shape') {
    const shape=model.shape;
    lines.push(shape.status==='clear' && shape.kind ? c[shape.kind] : shape.status==='unavailable' ? c.unavailable : c.noClear);
    if (shape.reason==='near-threshold') lines.push(c.near);
    if (shape.reason==='ambiguous-membership') lines.push(c.ambiguous);
    if (shape.reason==='outside-conventions') lines.push(c.outside);
    if (shape.largestGap!==null) lines.push(`${c.largestGap}: ${shape.largestGap}°`,`${c.span}: ${shape.occupiedSpan}°`);
    if (shape.status==='clear') for (const candidate of shape.candidates) {
      if(candidate.handle) lines.push(`${c.handle}: ${planetLabel(locale,candidate.handle)}`);
      candidate.groups.forEach((group,i)=>lines.push(`${group.map(body=>planetLabel(locale,body)).join(', ')} · ${candidate.spans[i]}°`));
    }
    lines.push(`${c.grid}: 0.001° · ${c.band}: 2°`,c.shapeDefinition);
  } else if (section==='rulers') {
    const r=model.rulers;
    lines.push(r.chart ? `${c.chartRuler}: ${signName(signBySlug(r.chart.sign),locale)} → ${placementText(r.chart.placement,locale)}` : `${c.chartRuler}: ${c.unavailable}`);
    if(r.system) lines.push(`${c.system}: ${r.system==='whole'?c.whole:c.placidus}`);
    for(const h of r.houses) lines.push(`${c.house} ${h.house} · ${signName(signBySlug(h.sign),locale)} → ${placementText(h.placement,locale)}`);
    if(!r.houses.length) lines.push(`${c.rulers}: ${c.unavailable}`);
    lines.push(c.sourceNotice);
  } else if(section==='dispositors') {
    lines.push(model.dispositors.final ? `${c.final}: ${planetLabel(locale,model.dispositors.final)}` : c.noFinal);
    for(const chain of model.dispositors.chains) lines.push(`${chain.members.map(b=>planetLabel(locale,b)).join(' → ')}${chain.status==='incomplete'?` · ${c.incomplete}`:''}`);
    for(const terminal of model.dispositors.terminals) lines.push(`${c[terminal.kind]}: ${terminal.members.map(b=>planetLabel(locale,b)).join(' → ')}`);
    lines.push(c.graphDefinition);
  } else {
    for(const p of model.placements) lines.push(`${placementText(p,locale)}: ${!p.covered?c.notCovered:!p.sign?c.unknownSign:p.dignities.length?p.dignities.map(d=>c[d]).join(' + '):c.noLabels}`);
    lines.push(c.definition);
  }
  return lines;
}
