/**
 * Tour copy — module-local dictionary, both locales, compile-time key
 * parity via `satisfies` (the SHARE_COPY precedent in
 * PositionsShareSurface.tsx). Lives inside the lazy tour module so none of
 * these strings land in any page's initial JS closure — /birth-chart/ has
 * fractions of a kilobyte of budget headroom and the shared UI dictionary
 * is statically imported by every page.
 *
 * Voice: plain, warm, specific. State computed facts; label interpretation
 * as tradition; never woo, never salesy.
 */
import type { CatalogLocale as Locale } from '../../../lib/i18n';

const TOUR_COPY = {
  en: {
    // Chrome
    kicker: 'Chapter {n} of {total}',
    next: 'Next',
    prev: 'Back',
    finish: 'Finish the tour',
    exitAria: 'End the tour',
    dotsLabel: 'Chapters',
    dotAria: '{title} — chapter {n} of {total}',
    ended: 'Tour ended.',
    backToTour: '← Back to the tour',
    allTypes: 'All',
    aspectTypesLabel: 'Aspect types',
    previewNote: 'A preview only — your chart stays in {system}. Change it in the form above.',
    rotateToAries: 'Put 0° Aries on the left',
    rotateToAsc: 'Back to your Ascendant',
    morphToPlacidus: 'See it in Placidus',
    morphToWhole: 'See it in whole sign',
    diffCount: '{n} placements change house',
    diffOne: '1 placement changes house',
    diffNone: 'No placements change house for this birth',
    polarNote: "This far from the equator Placidus isn't defined, so this chart uses whole sign either way.",
    loudest: "This chart's four loudest:",
    wholeSign: 'whole sign',
    placidus: 'Placidus',

    // Four-step first reading
    quickKicker: 'Your chart story · {n} of {total}',
    quickFinish: 'Show my year ahead',
    quickFinishNoTime: 'See my birthday-year',
    quickExitAria: 'Close the first reading',
    quickDotsLabel: 'First-reading steps',
    quickWhyLabel: 'Why this matters',
    quickRoleDrive: 'What drives you',
    quickRoleNeed: 'What you need',
    quickRoleImpression: 'How you come across',
    quickBigThreeWhy: 'This mix can explain why people see one side of you while the people closest to you experience another.',
    quickSunWhy: 'This points to one life area worth watching when you decide what deserves more attention.',
    quickSunPersonal: 'Your {sign} Sun describes the style you bring to purpose and self-expression.',
    quickAspectWhy: 'This is a recurring pattern that may feel like a strength, tension, or choice point — not an event that must happen and not a verdict about you.',
    quickAspectPersonal: '{a} and {b} form one of your clearest recurring patterns. Notice what happens when these two needs meet.',
    quickFutureWhy: 'Think weather, not fate: a forecast can show what may need attention, while your choices decide what happens next.',
    quickPersonalTimingLabel: 'Personal timing',
    quickPersonalTimingTitle: 'Your year ahead',
    quickPersonalTimingBody: 'Your exact birth chart, compared with the sky at your latest birthday.',
    quickPersonalTimingNoTimeTitle: 'Your birthday-year themes',
    quickPersonalTimingNoTimeBody: 'Your Sun still gives a useful yearly theme. Add a birth time before reading return houses or a return rising sign.',
    quickHoroscopeLabel: 'Sun-sign horoscope',
    quickHoroscopeBody: 'A broader monthly forecast — useful even without a birth time.',
    quickHoroscopeAction: 'Read my {sign} horoscope',
    quickHoroscopeEnglishNote: 'Horoscope available in English.',
    quickNextBigThree: 'See where it shows up',
    quickNextSun: 'Find my key pattern',
    quickNextAspect: 'Look ahead',
    quickAspectEmpty: 'No major aspect involving your Sun, Moon, Mercury, Venus, or Mars stands out. That is a real result, not missing data. Next, we will look at timing.',
    quickSunHouse: 'With your birth time, the Sun also falls in house {n}. The house tells you where in life that placement tends to show up.',
    quickSunNoHouse: 'Without a birth time, the Sun by sign is still reliable. Houses answer “where,” so this reading leaves that part open instead of guessing.',
    quickSeeAspect: 'Learn what this aspect means →',
    quickSave: 'Save this chart',
    quickToday: "See today's sky",
    'first-big-threeTitle': 'You’re more than your Sun sign',
    'first-big-threeBody1': 'Your chart separates what drives you, what you need, and how you come across. That gap is often where a chart starts feeling personal.',
    'first-sunTitle': 'Where you’re built to shine',
    'first-sunBody1': 'Your Sun describes what makes you feel most like yourself. Its sign shapes the style; its house points to the part of life where that energy tends to show up.',
    'first-aspectTitle': 'A pattern you may recognize',
    'first-aspectBody1': 'This step looks for a clear recurring pattern involving your personal planets. Some charts have one that stands out; others do not.',
    'first-nextTitle': 'What your chart says about the future',
    'first-nextBody1': 'Not a fixed script. Your birth chart describes recurring patterns; horoscopes and the moving sky show when certain themes may get louder.',

    // Chapters
    skyTitle: 'This is your sky',
    skyBody1: 'Everything on this wheel was computed from one instant: the sky over your birthplace at your birth time. Nothing is looked up — it is calculated, on your device.',
    skyBody2: 'The tour walks the wheel one layer at a time. Tap anything along the way; the tour waits.',
    zodiacTitle: 'The zodiac ring',
    zodiacBody1: "The outer ring is the zodiac: twelve equal 30° segments of the Sun's yearly path. It is the wheel's fixed scale — every position is read against it.",
    zodiacBody2: 'Your Sun stays lit — a sun sign just names the segment that one degree falls in.',
    zodiacRotateNote: 'Charts are usually drawn with your Ascendant on the left. The ring never changes — only where we start reading.',
    horizonTitle: 'Your horizon',
    horizonBody1: 'ASC marks the degree rising in the east at your birth minute; the sign it sits in is your rising sign. Straight across sits the Descendant, where the sky was setting; MC is the degree at its highest.',
    horizonBody2: 'This axis is why the minute matters: it moves about a degree every four minutes, and the whole wheel is anchored to it.',
    'big-threeTitle': 'The big three',
    'big-threeBody1': 'Sun, Moon, rising — identity, instinct, entrance. Read these three first; everything else refines them.',
    planetsTitle: 'The planets',
    planetsBody1: 'Each disc is a planet at its true degree. Mercury through Mars move fast and read personally; Jupiter and Saturn move in years and set the longer themes; the outer three mark generations.',
    planetsBody2: 'Tap any disc for its receipt — position, speed, house, aspects. Rx means retrograde: apparent backward motion, common and ordinary.',
    housesTitle: 'The houses',
    housesBody1: 'The twelve wedges are the houses — where in life a planet does its work. They come from your birth time and place, not the calendar.',
    housesBody2: 'Two honest ways to slice them: whole sign gives each house one sign; Placidus divides by exact horizon math. Try the other one — the planets never move, only the walls.',
    aspectsTitle: 'The conversations',
    aspectsBody1: 'The chords in the middle are aspects: set angles between planets, each a kind of conversation. Thicker chords sit closer to exact — they do the most work; dashed ones are already separating.',
    wholeTitle: 'The whole picture',
    wholeBody1: "Everything back on. A chart isn't a list of traits — it's one sky with everything happening at once. The reading below walks it line by line.",
    wholeBody2: 'Save it and your profile page computes its year ahead — still on this device. The share link carries the data in the link itself; it never touches a server.',
    'no-housesTitle': 'Why this chart has no houses',
    'no-housesBody1': "Houses depend on the birth time and the sky’s rotation. Without a birth time, we show reference positions; these do not establish every planet’s birth sign. Rising and houses are omitted.",
    'no-housesBody2': 'If the time ever turns up (birth certificates usually have it), add it above — the wheel gains its rooms, and you gain a rising sign.',
  },
  es: {
    kicker: 'Capítulo {n} de {total}',
    next: 'Siguiente',
    prev: 'Atrás',
    finish: 'Terminar el recorrido',
    exitAria: 'Salir del recorrido',
    dotsLabel: 'Capítulos',
    dotAria: '{title} — capítulo {n} de {total}',
    ended: 'Recorrido terminado.',
    backToTour: '← Volver al recorrido',
    allTypes: 'Todos',
    aspectTypesLabel: 'Tipos de aspecto',
    previewNote: 'Solo una vista previa — tu carta sigue en {system}. Cambia el sistema en el formulario de arriba.',
    rotateToAries: 'Poner 0° de Aries a la izquierda',
    rotateToAsc: 'Volver a tu ascendente',
    morphToPlacidus: 'Verla en Placidus',
    morphToWhole: 'Verla en signos completos',
    diffCount: '{n} posiciones cambian de casa',
    diffOne: '1 posición cambia de casa',
    diffNone: 'Ninguna posición cambia de casa para este nacimiento',
    polarNote: 'Tan lejos del ecuador, Placidus no está definido, así que esta carta usa signos completos de todos modos.',
    loudest: 'Los cuatro más fuertes de esta carta:',
    wholeSign: 'signos completos',
    placidus: 'Placidus',

    quickKicker: 'La historia de tu carta · {n} de {total}',
    quickFinish: 'Ver mi próximo año',
    quickFinishNoTime: 'Ver mi año personal',
    quickExitAria: 'Cerrar la primera lectura',
    quickDotsLabel: 'Pasos de la primera lectura',
    quickWhyLabel: 'Por qué esto importa',
    quickRoleDrive: 'Lo que te impulsa',
    quickRoleNeed: 'Lo que necesitas',
    quickRoleImpression: 'Cómo te ven los demás',
    quickBigThreeWhy: 'Esta combinación puede explicar por qué los demás ven una faceta de ti mientras las personas más cercanas conocen otra.',
    quickSunWhy: 'Esto señala un área de tu vida que conviene observar cuando decides qué merece más atención.',
    quickSunPersonal: 'Tu Sol en {sign} describe tu forma de buscar un propósito y expresar quién eres.',
    quickAspectWhy: 'Es un talento, una tensión o una elección que se repite — no un suceso inevitable ni un veredicto sobre ti.',
    quickAspectPersonal: '{a} y {b} forman uno de tus patrones recurrentes más claros. Observa qué ocurre cuando estas dos necesidades se encuentran.',
    quickFutureWhy: 'Piensa en el clima, no en el destino: un pronóstico puede mostrar qué podría necesitar atención, pero tus decisiones marcan lo que ocurre después.',
    quickPersonalTimingLabel: 'Ciclos personales',
    quickPersonalTimingTitle: 'Tu próximo año',
    quickPersonalTimingBody: 'Tu carta exacta, comparada con el cielo alrededor de tu cumpleaños.',
    quickPersonalTimingNoTimeTitle: 'Tus temas de cumpleaños a cumpleaños',
    quickPersonalTimingNoTimeBody: 'Tu Sol sigue ofreciendo un tema anual útil. Agrega tu hora de nacimiento antes de interpretar las casas o el ascendente del retorno solar.',
    quickHoroscopeLabel: 'Horóscopo de tu signo solar',
    quickHoroscopeBody: 'Un pronóstico mensual más general — útil incluso sin hora de nacimiento.',
    quickHoroscopeAction: 'Leer mi horóscopo de {sign}',
    quickHoroscopeEnglishNote: 'Horóscopo disponible en inglés.',
    quickNextBigThree: 'Ver dónde aparece en mi vida',
    quickNextSun: 'Encontrar mi patrón clave',
    quickNextAspect: 'Ver lo que viene',
    quickAspectEmpty: 'No destaca ningún aspecto mayor que implique a tu Sol, Luna, Mercurio, Venus o Marte. Es un resultado real, no falta información. Ahora veremos cómo se mira hacia adelante.',
    quickSunHouse: 'Con tu hora de nacimiento, el Sol también cae en la casa {n}. La casa indica en qué parte de la vida suele aparecer esta posición.',
    quickSunNoHouse: 'Sin hora de nacimiento, el signo del Sol sigue siendo confiable. Las casas responden “dónde”, así que dejamos esa parte abierta en vez de adivinar.',
    quickSeeAspect: 'Aprende qué significa este aspecto →',
    quickSave: 'Guardar esta carta',
    quickToday: 'Ver el cielo de hoy',
    'first-big-threeTitle': 'Eres mucho más que tu signo solar',
    'first-big-threeBody1': 'Tu carta separa lo que te impulsa, lo que necesitas y cómo te ven los demás. La diferencia entre esas facetas suele ser el punto en que la carta empieza a sentirse realmente personal.',
    'first-sunTitle': 'Dónde brillas con más naturalidad',
    'first-sunBody1': 'Tu Sol describe lo que te hace sentir más tú. Su signo marca el estilo; su casa señala el área de la vida donde esa energía suele aparecer.',
    'first-aspectTitle': 'Patrones entre tus planetas',
    'first-aspectBody1': 'Este paso busca un patrón recurrente claro que implique a tus planetas personales. En algunas cartas destaca uno; en otras, no.',
    'first-nextTitle': 'Lo que tu carta dice sobre tu futuro',
    'first-nextBody1': 'No es un guion fijo. Tu carta natal describe patrones que se repiten; los horóscopos y el cielo en movimiento muestran cuándo ciertos temas pueden cobrar más fuerza.',

    skyTitle: 'Este es tu cielo',
    skyBody1: 'Todo en esta rueda se calculó a partir de un instante: el cielo sobre tu lugar de nacimiento a tu hora de nacimiento. Nada se busca en tablas — se calcula, en tu dispositivo.',
    skyBody2: 'El recorrido repasa la rueda capa por capa. Toca lo que quieras por el camino; el recorrido espera.',
    zodiacTitle: 'El anillo del zodiaco',
    zodiacBody1: 'El anillo exterior es el zodiaco: doce segmentos iguales de 30° del camino anual del Sol. Es la regla fija de la rueda: cada posición se mide sobre ella.',
    zodiacBody2: 'Tu Sol sigue encendido — un signo solar solo nombra el segmento donde cae ese grado.',
    zodiacRotateNote: 'Las cartas suelen dibujarse con tu ascendente a la izquierda. El anillo no cambia — solo dónde empezamos a leer.',
    horizonTitle: 'Tu horizonte',
    horizonBody1: 'ASC marca el grado que subía por el este en tu minuto de nacimiento — tu ascendente. Justo enfrente está el descendente, donde el cielo se ponía; el MC es el grado en lo más alto.',
    horizonBody2: 'Este eje es la razón de que importe el minuto: se mueve alrededor de un grado cada cuatro minutos, y toda la rueda está anclada a él.',
    'big-threeTitle': 'Los tres grandes',
    'big-threeBody1': 'Sol, Luna, ascendente: identidad, instinto, presencia. Lee estos tres primero; todo lo demás los matiza.',
    planetsTitle: 'Los planetas',
    planetsBody1: 'Cada disco es un planeta en su grado real. De Mercurio a Marte van rápido y se leen en clave personal; Júpiter y Saturno marcan los temas de largo plazo; los tres exteriores marcan generaciones.',
    planetsBody2: 'Toca cualquier disco para ver su ficha — posición, velocidad, casa, aspectos. Rx significa retrógrado: movimiento aparente hacia atrás, común y corriente.',
    housesTitle: 'Las casas',
    housesBody1: 'Las doce cuñas son las casas — en qué parte de la vida trabaja cada planeta. Salen de tu hora y lugar de nacimiento, no del calendario.',
    housesBody2: 'Dos maneras honestas de dividirlas: el sistema de signos completos da un signo a cada casa; Placidus divide con la trigonometría exacta del horizonte. Prueba la otra — los planetas no se mueven, solo las paredes.',
    aspectsTitle: 'Las conversaciones',
    aspectsBody1: 'Las cuerdas del centro son aspectos: ángulos fijos entre planetas, cada uno un tipo de conversación. Las cuerdas más gruesas son ángulos más exactos — son las de mayor peso; las discontinuas ya se están separando.',
    wholeTitle: 'La imagen completa',
    wholeBody1: 'Todo encendido otra vez. Una carta no es una lista de rasgos — es un solo cielo con todo a la vez. La lectura de abajo la recorre línea por línea.',
    wholeBody2: 'Guárdala y tu página de perfil calcula sus próximos doce meses — siempre en este dispositivo. El enlace para compartir lleva los datos dentro del propio enlace; nunca pasa por un servidor.',
    'no-housesTitle': 'Por qué esta carta no tiene casas',
    'no-housesBody1': "Las casas dependen de la hora de nacimiento y de la rotación del cielo. Sin hora, mostramos posiciones de referencia; estas no establecen el signo natal de cada planeta. No se muestran el ascendente ni las casas.",
    'no-housesBody2': 'Si la hora aparece algún día (el certificado de nacimiento suele tenerla), agrégala arriba — la rueda gana sus casas, y tú un ascendente.',
  },
  pt: {
    kicker: 'Capítulo {n} de {total}',
    next: 'Próximo',
    prev: 'Voltar',
    finish: 'Concluir o passeio',
    exitAria: 'Encerrar o passeio',
    dotsLabel: 'Capítulos',
    dotAria: '{title} — capítulo {n} de {total}',
    ended: 'Passeio encerrado.',
    backToTour: '← Voltar ao passeio',
    allTypes: 'Todos',
    aspectTypesLabel: 'Tipos de aspecto',
    previewNote: 'Apenas uma prévia — seu mapa continua em {system}. Mude o sistema no formulário acima.',
    rotateToAries: 'Colocar 0° de Áries à esquerda',
    rotateToAsc: 'Voltar ao seu ascendente',
    morphToPlacidus: 'Ver em Placidus',
    morphToWhole: 'Ver em signos inteiros',
    diffCount: '{n} posições mudam de casa',
    diffOne: '1 posição muda de casa',
    diffNone: 'Nenhuma posição muda de casa neste nascimento',
    polarNote: 'Tão longe do equador, Placidus não é definido; por isso, este mapa usa signos inteiros de qualquer forma.',
    loudest: 'Os quatro aspectos mais fortes deste mapa:',
    wholeSign: 'signos inteiros',
    placidus: 'Placidus',

    quickKicker: 'A história do seu mapa · {n} de {total}',
    quickFinish: 'Ver meu próximo ano',
    quickFinishNoTime: 'Ver meu ano pessoal',
    quickExitAria: 'Fechar a primeira leitura',
    quickDotsLabel: 'Etapas da primeira leitura',
    quickWhyLabel: 'Por que isso importa',
    quickRoleDrive: 'O que move você',
    quickRoleNeed: 'O que você precisa',
    quickRoleImpression: 'Como os outros veem você',
    quickBigThreeWhy: 'Essa combinação pode explicar por que os outros veem um lado seu, enquanto as pessoas mais próximas conhecem outro.',
    quickSunWhy: 'Isso aponta para uma área da vida que vale observar quando você decide o que merece mais atenção.',
    quickSunPersonal: 'Seu Sol em {sign} descreve seu jeito de buscar propósito e expressar quem você é.',
    quickAspectWhy: 'É um talento, uma tensão ou uma escolha que se repete — não um acontecimento inevitável nem um veredicto sobre você.',
    quickAspectPersonal: '{a} e {b} formam um dos seus padrões recorrentes mais claros. Observe o que acontece quando essas duas necessidades se encontram.',
    quickFutureWhy: 'Pense em clima, não em destino: a previsão mostra o que pode exigir atenção, mas suas escolhas definem o que acontece depois.',
    quickPersonalTimingLabel: 'Ciclos pessoais',
    quickPersonalTimingTitle: 'Seu próximo ano',
    quickPersonalTimingBody: 'Seu mapa exato, comparado ao céu ao redor do seu aniversário.',
    quickPersonalTimingNoTimeTitle: 'Seus temas de um aniversário ao outro',
    quickPersonalTimingNoTimeBody: 'Seu Sol ainda oferece um tema anual útil. Adicione a hora de nascimento antes de interpretar as casas ou o ascendente do retorno solar.',
    quickHoroscopeLabel: 'Horóscopo do seu signo solar',
    quickHoroscopeBody: 'Uma previsão mensal mais ampla — útil mesmo sem a hora de nascimento.',
    quickHoroscopeAction: 'Ler meu horóscopo de {sign}',
    quickHoroscopeEnglishNote: 'Horóscopo disponível em inglês.',
    quickNextBigThree: 'Ver onde isso aparece na minha vida',
    quickNextSun: 'Encontrar meu padrão principal',
    quickNextAspect: 'Ver o que vem pela frente',
    quickAspectEmpty: 'Nenhum aspecto maior envolvendo seu Sol, sua Lua, Mercúrio, Vênus ou Marte se destaca. É um resultado real, não falta de dados. Agora, vamos olhar para os ciclos à frente.',
    quickSunHouse: 'Com sua hora de nascimento, o Sol também cai na casa {n}. A casa mostra em que área da vida essa posição tende a aparecer.',
    quickSunNoHouse: 'Sem hora de nascimento, o signo do Sol continua confiável. As casas respondem “onde”, então esta leitura deixa essa parte em aberto em vez de adivinhar.',
    quickSeeAspect: 'Entenda o que este aspecto significa →',
    quickSave: 'Salvar este mapa',
    quickToday: 'Ver o céu de hoje',
    'first-big-threeTitle': 'Você é mais do que seu signo solar',
    'first-big-threeBody1': 'Seu mapa separa o que move você, o que você precisa e como os outros veem você. A diferença entre esses lados costuma ser o ponto em que o mapa começa a parecer realmente pessoal.',
    'first-sunTitle': 'Onde você brilha naturalmente',
    'first-sunBody1': 'Seu Sol descreve o que faz você se sentir mais você. O signo dá o estilo; a casa aponta para a área da vida em que essa energia tende a aparecer.',
    'first-aspectTitle': 'Padrões entre seus planetas',
    'first-aspectBody1': 'Esta etapa procura um padrão recorrente claro envolvendo seus planetas pessoais. Em alguns mapas, um padrão se destaca; em outros, não.',
    'first-nextTitle': 'O que seu mapa diz sobre o futuro',
    'first-nextBody1': 'Não é um roteiro fixo. Seu mapa natal descreve padrões que se repetem; os horóscopos e o céu em movimento mostram quando certos temas podem ganhar força.',

    skyTitle: 'Este é o seu céu',
    skyBody1: 'Tudo nesta roda foi calculado a partir de um instante: o céu sobre seu local de nascimento na hora em que você nasceu. Nada é consultado em tabelas — tudo é calculado no seu dispositivo.',
    skyBody2: 'O passeio percorre a roda, uma camada de cada vez. Toque no que quiser durante o caminho; o passeio espera.',
    zodiacTitle: 'O anel do zodíaco',
    zodiacBody1: 'O anel externo é o zodíaco: doze segmentos iguais de 30° no caminho anual do Sol. É a escala fixa da roda — cada posição é lida em relação a ela.',
    zodiacBody2: 'Seu Sol continua aceso — o signo solar apenas dá nome ao segmento em que esse grau cai.',
    zodiacRotateNote: 'Os mapas costumam ser desenhados com o ascendente à esquerda. O anel nunca muda — muda apenas o ponto em que começamos a leitura.',
    horizonTitle: 'Seu horizonte',
    horizonBody1: 'ASC marca o grau que surgia a leste no minuto do seu nascimento; o signo em que ele está é seu ascendente. Exatamente do outro lado está o descendente, onde o céu se punha; MC é o grau no ponto mais alto.',
    horizonBody2: 'Este eixo mostra por que o minuto importa: ele se move cerca de um grau a cada quatro minutos, e toda a roda se ancora nele.',
    'big-threeTitle': 'Os três grandes',
    'big-threeBody1': 'Sol, Lua, ascendente — identidade, instinto, presença. Leia estes três primeiro; todo o resto acrescenta nuances.',
    planetsTitle: 'Os planetas',
    planetsBody1: 'Cada disco é um planeta em seu grau real. De Mercúrio a Marte, eles se movem rápido e têm uma leitura pessoal; Júpiter e Saturno se movem ao longo de anos e definem temas mais longos; os três externos marcam gerações.',
    planetsBody2: 'Toque em qualquer disco para ver os detalhes — posição, velocidade, casa e aspectos. Rx significa retrógrado: movimento aparente para trás, comum e normal.',
    housesTitle: 'As casas',
    housesBody1: 'As doze fatias são as casas — onde cada planeta atua na vida. Elas vêm da hora e do local de nascimento, não do calendário.',
    housesBody2: 'Duas formas honestas de dividi-las: signos inteiros atribuem um signo a cada casa; Placidus divide pela matemática exata do horizonte. Experimente a outra — os planetas nunca se movem, apenas as paredes.',
    aspectsTitle: 'As conversas',
    aspectsBody1: 'As cordas no centro são aspectos: ângulos definidos entre planetas, cada um como um tipo de conversa. Cordas mais grossas ficam mais perto do ponto exato — elas têm mais peso; as tracejadas já estão se separando.',
    wholeTitle: 'O quadro completo',
    wholeBody1: 'Tudo aceso novamente. Um mapa não é uma lista de traços — é um único céu com tudo acontecendo ao mesmo tempo. A leitura abaixo o percorre linha por linha.',
    wholeBody2: 'Salve-o e sua página de perfil calcula os próximos doze meses — sempre neste dispositivo. O link de compartilhamento leva os dados no próprio link; eles nunca passam por um servidor.',
    'no-housesTitle': 'Por que este mapa não tem casas',
    'no-housesBody1': "As casas dependem da hora de nascimento e da rotação do céu. Sem a hora, mostramos posições de referência; elas não estabelecem o signo natal de cada planeta. O ascendente e as casas não são mostrados.",
    'no-housesBody2': 'Se o horário aparecer algum dia (a certidão de nascimento costuma registrá-lo), adicione-o acima — a roda ganha suas casas, e você ganha um ascendente.',
  },
  fr: {
    kicker: 'Chapitre {n} sur {total}',
    next: 'Suivant',
    prev: 'Retour',
    finish: 'Terminer la visite',
    exitAria: 'Quitter la visite',
    dotsLabel: 'Chapitres',
    dotAria: '{title} — chapitre {n} sur {total}',
    ended: 'Visite terminée.',
    backToTour: '← Revenir à la visite',
    allTypes: 'Tous',
    aspectTypesLabel: 'Types d’aspects',
    previewNote: 'Aperçu uniquement — ton thème reste en {system}. Change ce réglage dans le formulaire ci-dessus.',
    rotateToAries: 'Placer 0° du Bélier à gauche',
    rotateToAsc: 'Revenir à ton ascendant',
    morphToPlacidus: 'Voir en Placidus',
    morphToWhole: 'Voir en signes entiers',
    diffCount: '{n} positions changent de maison',
    diffOne: '1 position change de maison',
    diffNone: 'Aucune position ne change de maison pour cette naissance',
    polarNote: 'À cette distance de l’équateur, Placidus n’est pas défini ; ce thème utilise donc les signes entiers dans tous les cas.',
    loudest: 'Les quatre aspects les plus marqués de ce thème :',
    wholeSign: 'signes entiers',
    placidus: 'Placidus',

    quickKicker: 'L’histoire de ton thème · {n} sur {total}',
    quickFinish: 'Voir mon année à venir',
    quickFinishNoTime: 'Voir mon année personnelle',
    quickExitAria: 'Fermer la première lecture',
    quickDotsLabel: 'Étapes de la première lecture',
    quickWhyLabel: 'Pourquoi c’est important',
    quickRoleDrive: 'Ce qui te motive',
    quickRoleNeed: 'Ce dont tu as besoin',
    quickRoleImpression: 'L’impression que tu donnes',
    quickBigThreeWhy: 'Ce mélange peut expliquer pourquoi les autres voient une facette de toi, tandis que tes proches en connaissent une autre.',
    quickSunWhy: 'Cela indique un domaine de ta vie à observer quand tu choisis ce qui mérite le plus d’attention.',
    quickSunPersonal: 'Ton Soleil en {sign} décrit ta façon de chercher ce qui a du sens pour toi et d’exprimer qui tu es.',
    quickAspectWhy: 'C’est un talent, une tension ou un choix qui revient — pas un événement inévitable ni un jugement sur toi.',
    quickAspectPersonal: '{a} et {b} forment l’un de tes schémas récurrents les plus nets. Observe ce qui se passe lorsque ces deux besoins se rencontrent.',
    quickFutureWhy: 'Pense météo, pas destin : une prévision peut montrer ce qui pourrait demander ton attention, mais tes choix déterminent la suite.',
    quickPersonalTimingLabel: 'Cycles personnels',
    quickPersonalTimingTitle: 'Ton année à venir',
    quickPersonalTimingBody: 'Ton thème précis, comparé au ciel autour de ton anniversaire.',
    quickPersonalTimingNoTimeTitle: 'Tes thèmes d’un anniversaire à l’autre',
    quickPersonalTimingNoTimeBody: 'Ton Soleil donne tout de même un thème annuel utile. Ajoute ton heure de naissance avant d’interpréter les maisons ou l’ascendant de ta révolution solaire.',
    quickHoroscopeLabel: 'Horoscope de ton signe solaire',
    quickHoroscopeBody: 'Une prévision mensuelle plus générale — utile même sans heure de naissance.',
    quickHoroscopeAction: 'Lire mon horoscope {sign}',
    quickHoroscopeEnglishNote: 'Horoscope disponible en anglais.',
    quickNextBigThree: 'Voir où cela apparaît dans ma vie',
    quickNextSun: 'Trouver mon schéma principal',
    quickNextAspect: 'Voir la suite',
    quickAspectEmpty: 'Aucun aspect majeur impliquant ton Soleil, ta Lune, Mercure, Vénus ou Mars ne se démarque. C’est un vrai résultat, pas une donnée manquante. Passons maintenant aux cycles à venir.',
    quickSunHouse: 'Avec ton heure de naissance, le Soleil tombe aussi dans la maison {n}. La maison indique où cette position tend à se manifester dans la vie.',
    quickSunNoHouse: 'Sans heure de naissance, le signe du Soleil reste fiable. Les maisons répondent à la question « où » ; cette lecture laisse donc ce point ouvert au lieu de deviner.',
    quickSeeAspect: 'Comprendre cet aspect →',
    quickSave: 'Enregistrer ce thème',
    quickToday: 'Voir le ciel d’aujourd’hui',
    'first-big-threeTitle': 'Tu es bien plus que ton signe solaire',
    'first-big-threeBody1': 'Ton thème distingue ce qui te motive, ce dont tu as besoin et l’impression que tu donnes. C’est souvent dans l’écart entre ces facettes qu’un thème commence à te parler vraiment.',
    'first-sunTitle': 'Là où tu brilles naturellement',
    'first-sunBody1': 'Ton Soleil décrit ce qui te fait te sentir pleinement toi-même. Son signe donne le style ; sa maison indique le domaine de la vie où cette énergie tend à se manifester.',
    'first-aspectTitle': 'Les schémas entre tes planètes',
    'first-aspectBody1': 'Cette étape cherche un schéma récurrent clair impliquant tes planètes personnelles. Un tel schéma ressort nettement dans certains thèmes, mais pas dans tous.',
    'first-nextTitle': 'Ce que ton thème dit de ton avenir',
    'first-nextBody1': 'Pas de scénario écrit d’avance. Ton thème astral décrit des schémas récurrents ; les horoscopes et le ciel en mouvement montrent quand certains thèmes peuvent prendre plus d’ampleur.',

    skyTitle: 'Voici ton ciel',
    skyBody1: 'Tout ce qui figure sur cette roue a été calculé à partir d’un seul instant : le ciel au-dessus de ton lieu de naissance à l’heure de ta naissance. Rien n’est extrait d’une table — tout est calculé sur ton appareil.',
    skyBody2: 'La visite parcourt la roue couche par couche. Touche ce que tu veux en chemin ; la visite attendra.',
    zodiacTitle: 'L’anneau du zodiaque',
    zodiacBody1: 'L’anneau extérieur est le zodiaque : douze segments égaux de 30° sur le parcours annuel du Soleil. C’est l’échelle fixe de la roue — chaque position se lit par rapport à elle.',
    zodiacBody2: 'Ton Soleil reste mis en évidence — un signe solaire désigne simplement le segment dans lequel tombe ce degré.',
    zodiacRotateNote: 'Les thèmes sont généralement dessinés avec l’ascendant à gauche. L’anneau ne change jamais — seul le point de départ de la lecture se déplace.',
    horizonTitle: 'Ton horizon',
    horizonBody1: 'L’ASC marque le degré qui se levait à l’est à la minute de ta naissance ; le signe où il se trouve est ton ascendant. Juste en face se trouve le descendant, là où le ciel se couchait ; le MC correspond au degré qui était au plus haut.',
    horizonBody2: 'Cet axe explique pourquoi la minute compte : il se déplace d’environ un degré toutes les quatre minutes, et toute la roue s’y ancre.',
    'big-threeTitle': 'Les trois piliers',
    'big-threeBody1': 'Soleil, Lune, ascendant — identité, instinct, présence. Lis ces trois éléments en premier ; tout le reste les précise.',
    planetsTitle: 'Les planètes',
    planetsBody1: 'Chaque disque représente une planète à son degré réel. De Mercure à Mars, les planètes se déplacent vite et se lisent sur un plan personnel ; Jupiter et Saturne avancent sur plusieurs années et donnent les thèmes de fond ; les trois planètes extérieures marquent les générations.',
    planetsBody2: 'Touche un disque pour voir ses données — position, vitesse, maison, aspects. Rx signifie rétrograde : un mouvement apparent vers l’arrière, courant et ordinaire.',
    housesTitle: 'Les maisons',
    housesBody1: 'Les douze secteurs sont les maisons — les domaines de la vie où chaque planète agit. Ils viennent de ton heure et de ton lieu de naissance, pas du calendrier.',
    housesBody2: 'Deux façons rigoureuses de les diviser : les signes entiers attribuent un signe à chaque maison ; Placidus s’appuie sur le calcul exact de l’horizon. Essaie l’autre méthode — les planètes ne bougent jamais, seules les limites changent.',
    aspectsTitle: 'Les conversations',
    aspectsBody1: 'Les lignes au centre sont les aspects : des angles définis entre les planètes, chacun comme une forme de conversation. Les lignes plus épaisses sont plus proches du point exact — elles pèsent davantage ; celles en pointillé sont déjà en train de se séparer.',
    wholeTitle: 'La vue d’ensemble',
    wholeBody1: 'Tout est de nouveau visible. Un thème n’est pas une liste de traits — c’est un seul ciel où tout se produit en même temps. La lecture ci-dessous le parcourt ligne par ligne.',
    wholeBody2: 'Enregistre-le et ta page de profil calcule son année à venir — toujours sur cet appareil. Le lien de partage contient les données dans le lien lui-même ; elles ne passent jamais par un serveur.',
    'no-housesTitle': 'Pourquoi ce thème n’a pas de maisons',
    'no-housesBody1': "Les maisons dépendent de l’heure de naissance et de la rotation du ciel. Sans heure, nous affichons des positions de référence ; elles ne déterminent pas le signe natal de chaque planète. L’ascendant et les maisons sont omis.",
    'no-housesBody2': 'Si l’heure refait surface un jour — elle figure souvent sur l’acte de naissance — ajoute-la ci-dessus : la roue gagne ses maisons et toi, un ascendant.',
  },
  it: {
    kicker: 'Capitolo {n} di {total}',
    next: 'Avanti',
    prev: 'Indietro',
    finish: 'Concludi il tour',
    exitAria: 'Esci dal tour',
    dotsLabel: 'Capitoli',
    dotAria: '{title} — capitolo {n} di {total}',
    ended: 'Tour concluso.',
    backToTour: '← Torna al tour',
    allTypes: 'Tutti',
    aspectTypesLabel: 'Tipi di aspetto',
    previewNote: 'Solo un’anteprima — il tuo tema resta in {system}. Cambia il sistema nel modulo qui sopra.',
    rotateToAries: 'Metti 0° dell’Ariete a sinistra',
    rotateToAsc: 'Torna al tuo ascendente',
    morphToPlacidus: 'Visualizza in Placidus',
    morphToWhole: 'Visualizza a segno intero',
    diffCount: '{n} posizioni cambiano casa',
    diffOne: '1 posizione cambia casa',
    diffNone: 'Nessuna posizione cambia casa con questi dati di nascita',
    polarNote: 'A questa distanza dall’equatore, Placidus non è definito; questo tema usa quindi le case a segno intero in ogni caso.',
    loudest: 'I quattro aspetti più marcati di questo tema:',
    wholeSign: 'segno intero',
    placidus: 'Placidus',

    quickKicker: 'La storia del tuo tema · {n} di {total}',
    quickFinish: 'Scopri il mio anno a venire',
    quickFinishNoTime: 'Vedi il mio anno personale',
    quickExitAria: 'Chiudi la prima lettura',
    quickDotsLabel: 'Passaggi della prima lettura',
    quickWhyLabel: 'Perché è importante',
    quickRoleDrive: 'Cosa ti motiva',
    quickRoleNeed: 'Di cosa hai bisogno',
    quickRoleImpression: 'Come ti vedono gli altri',
    quickBigThreeWhy: 'Questa combinazione può spiegare perché gli altri vedono un lato di te, mentre chi ti è più vicino ne conosce un altro.',
    quickSunWhy: 'Questo indica un ambito della vita da tenere d’occhio quando decidi cosa merita più attenzione.',
    quickSunPersonal: 'Il tuo Sole in {sign} descrive il modo in cui cerchi uno scopo ed esprimi chi sei.',
    quickAspectWhy: 'È un talento, una tensione o una scelta che si ripete — non un evento inevitabile né un giudizio su di te.',
    quickAspectPersonal: '{a} e {b} formano uno dei tuoi schemi ricorrenti più evidenti. Osserva cosa succede quando questi due bisogni si incontrano.',
    quickFutureWhy: 'Pensa al meteo, non al destino: una previsione può mostrare cosa potrebbe richiedere attenzione, ma le tue scelte determinano ciò che accade.',
    quickPersonalTimingLabel: 'Cicli personali',
    quickPersonalTimingTitle: 'Il tuo anno a venire',
    quickPersonalTimingBody: 'Il tuo tema preciso, confrontato con il cielo intorno al tuo compleanno.',
    quickPersonalTimingNoTimeTitle: 'I tuoi temi da un compleanno all’altro',
    quickPersonalTimingNoTimeBody: 'Il tuo Sole offre comunque un tema annuale utile. Aggiungi l’ora di nascita prima di interpretare le case o l’ascendente della rivoluzione solare.',
    quickHoroscopeLabel: 'Oroscopo del tuo segno solare',
    quickHoroscopeBody: 'Una previsione mensile più ampia — utile anche senza l’ora di nascita.',
    quickHoroscopeAction: 'Leggi il mio oroscopo per {sign}',
    quickHoroscopeEnglishNote: 'Oroscopo disponibile in inglese.',
    quickNextBigThree: 'Scopri dove emerge nella mia vita',
    quickNextSun: 'Trova il mio schema principale',
    quickNextAspect: 'Guarda avanti',
    quickAspectEmpty: 'Non emerge alcun aspetto maggiore che coinvolga il tuo Sole, la tua Luna, Mercurio, Venere o Marte. È un risultato reale, non un dato mancante. Ora guardiamo ai cicli futuri.',
    quickSunHouse: 'Con l’ora di nascita, il Sole cade anche nella casa {n}. La casa indica dove questa posizione tende a manifestarsi nella vita.',
    quickSunNoHouse: 'Senza l’ora di nascita, il segno del Sole resta affidabile. Le case rispondono alla domanda “dove”, quindi questa lettura lascia aperta quella parte invece di indovinare.',
    quickSeeAspect: 'Scopri cosa significa questo aspetto →',
    quickSave: 'Salva questo tema',
    quickToday: 'Vedi il cielo di oggi',
    'first-big-threeTitle': 'Sei molto più del tuo segno solare',
    'first-big-threeBody1': 'Il tuo tema distingue ciò che ti motiva, ciò di cui hai bisogno e come ti vedono gli altri. È spesso nella distanza tra questi lati che un tema comincia a parlarti davvero.',
    'first-sunTitle': 'Dove brilli naturalmente',
    'first-sunBody1': 'Il tuo Sole descrive ciò che ti fa sentire davvero te. Il segno ne definisce lo stile; la casa indica l’ambito della vita in cui quell’energia tende a manifestarsi.',
    'first-aspectTitle': 'Gli schemi tra i tuoi pianeti',
    'first-aspectBody1': 'Questo passaggio cerca uno schema ricorrente chiaro che coinvolga i tuoi pianeti personali. In alcuni temi ne emerge uno; in altri no.',
    'first-nextTitle': 'Cosa dice il tuo tema sul tuo futuro',
    'first-nextBody1': 'Non è un copione fisso. Il tema natale descrive schemi ricorrenti; gli oroscopi e il cielo in movimento mostrano quando alcuni temi possono farsi più intensi.',

    skyTitle: 'Questo è il tuo cielo',
    skyBody1: 'Tutto in questa ruota è stato calcolato a partire da un solo istante: il cielo sopra il tuo luogo di nascita all’ora della tua nascita. Nulla viene cercato in una tabella — tutto viene calcolato sul tuo dispositivo.',
    skyBody2: 'Il tour percorre la ruota uno strato alla volta. Tocca ciò che vuoi lungo il percorso; il tour aspetterà.',
    zodiacTitle: 'L’anello dello zodiaco',
    zodiacBody1: 'L’anello esterno è lo zodiaco: dodici segmenti uguali di 30° lungo il percorso annuale del Sole. È la scala fissa della ruota — ogni posizione viene letta rispetto a essa.',
    zodiacBody2: 'Il tuo Sole resta evidenziato — il segno solare indica semplicemente il segmento in cui cade quel grado.',
    zodiacRotateNote: 'I temi vengono di solito disegnati con l’ascendente a sinistra. L’anello non cambia mai — cambia solo il punto da cui iniziamo a leggere.',
    horizonTitle: 'Il tuo orizzonte',
    horizonBody1: 'L’ASC indica il grado che stava sorgendo a est nel minuto della tua nascita; il segno in cui si trova è il tuo ascendente. Di fronte si trova il discendente, dove il cielo stava tramontando; il MC è il grado che si trovava più in alto.',
    horizonBody2: 'Questo asse spiega perché il minuto conta: si sposta di circa un grado ogni quattro minuti e l’intera ruota è ancorata a esso.',
    'big-threeTitle': 'I tre pilastri',
    'big-threeBody1': 'Sole, Luna, ascendente — identità, istinto, presenza. Leggi prima questi tre; tutto il resto ne precisa il significato.',
    planetsTitle: 'I pianeti',
    planetsBody1: 'Ogni disco rappresenta un pianeta al suo grado reale. Da Mercurio a Marte, i pianeti si muovono rapidamente e si leggono sul piano personale; Giove e Saturno si muovono nell’arco di anni e definiscono i temi più lunghi; i tre pianeti esterni segnano le generazioni.',
    planetsBody2: 'Tocca un disco per vederne i dati — posizione, velocità, casa, aspetti. Rx significa retrogrado: un moto apparente all’indietro, comune e normale.',
    housesTitle: 'Le case',
    housesBody1: 'I dodici settori sono le case — gli ambiti della vita in cui agisce ogni pianeta. Derivano dalla tua ora e dal tuo luogo di nascita, non dal calendario.',
    housesBody2: 'Due modi rigorosi per dividerle: il sistema a segno intero assegna un segno a ogni casa; Placidus divide usando il calcolo esatto dell’orizzonte. Prova l’altro sistema — i pianeti non si muovono mai, cambiano solo i confini.',
    aspectsTitle: 'Le conversazioni',
    aspectsBody1: 'Le linee al centro sono gli aspetti: angoli definiti tra i pianeti, ciascuno dei quali rappresenta un tipo di conversazione. Le linee più spesse corrispondono agli aspetti più esatti — sono quelli che pesano di più; quelle tratteggiate si stanno già separando.',
    wholeTitle: 'Il quadro completo',
    wholeBody1: 'Tutto è di nuovo visibile. Un tema non è un elenco di tratti — è un solo cielo in cui tutto accade insieme. La lettura qui sotto lo percorre riga per riga.',
    wholeBody2: 'Salvalo e la pagina del tuo profilo ne calcola i prossimi dodici mesi — sempre su questo dispositivo. Il link di condivisione contiene i dati nel link stesso; non passano mai da un server.',
    'no-housesTitle': 'Perché questo tema non ha case',
    'no-housesBody1': "Le case dipendono dall’ora di nascita e dalla rotazione del cielo. Senza un’ora, mostriamo posizioni di riferimento; queste non stabiliscono il segno natale di ogni pianeta. L’ascendente e le case non vengono mostrati.",
    'no-housesBody2': 'Se un giorno ritrovi l’ora — il certificato di nascita spesso la riporta — aggiungila qui sopra: la ruota si completa con le case e compare anche il tuo ascendente.',
  },
  ru: {
    kicker: 'Глава {n} из {total}',
    next: 'Дальше',
    prev: 'Назад',
    finish: 'Завершить экскурсию',
    exitAria: 'Закрыть экскурсию',
    dotsLabel: 'Главы',
    dotAria: '{title} — глава {n} из {total}',
    ended: 'Экскурсия завершена.',
    backToTour: '← Вернуться к экскурсии',
    allTypes: 'Все',
    aspectTypesLabel: 'Типы аспектов',
    previewNote: 'Это только предварительный вид — ваша карта остаётся в системе {system}. Изменить её можно в форме выше.',
    rotateToAries: 'Поставить 0° Овна слева',
    rotateToAsc: 'Вернуться к асценденту',
    morphToPlacidus: 'Посмотреть в Плацидусе',
    morphToWhole: 'Посмотреть в целых знаках',
    diffCount: '{n} положений меняют дом',
    diffOne: '1 положение меняет дом',
    diffNone: 'Ни одно положение не меняет дом для этого рождения',
    polarNote: 'Так далеко от экватора дома Плацидуса не определены, поэтому карта в любом случае использует целые знаки.',
    loudest: 'Четыре самых заметных элемента карты:',
    wholeSign: 'целые знаки',
    placidus: 'Плацидус',

    quickKicker: 'История вашей карты · {n} из {total}',
    quickFinish: 'Показать мой год впереди',
    quickFinishNoTime: 'Посмотреть мой год от дня рождения',
    quickExitAria: 'Закрыть первое чтение',
    quickDotsLabel: 'Шаги первого чтения',
    quickWhyLabel: 'Почему это важно',
    quickRoleDrive: 'Что вами движет',
    quickRoleNeed: 'Что вам нужно',
    quickRoleImpression: 'Как вы выглядите со стороны',
    quickBigThreeWhy: 'Эта смесь может объяснить, почему окружающие видят одну вашу сторону, а близкие — другую.',
    quickSunWhy: 'Это указывает на область жизни, за которой стоит наблюдать, когда вы решаете, что заслуживает внимания.',
    quickSunPersonal: 'Солнце в знаке {sign} описывает стиль, с которым вы ищете смысл и выражаете себя.',
    quickAspectWhy: 'Это повторяющийся ресурс, напряжение или точка выбора — не неизбежное событие и не приговор.',
    quickAspectPersonal: '{a} и {b} образуют один из самых ясных повторяющихся рисунков вашей карты. Замечайте, что происходит при встрече этих двух потребностей.',
    quickFutureWhy: 'Думайте о погоде, а не о судьбе: прогноз показывает, что может попросить внимания, а дальнейшее решают ваши поступки.',
    quickPersonalTimingLabel: 'Личное время',
    quickPersonalTimingTitle: 'Ваш год впереди',
    quickPersonalTimingBody: 'Ваша точная натальная карта рядом с небом последнего дня рождения.',
    quickPersonalTimingNoTimeTitle: 'Темы вашего года от дня рождения',
    quickPersonalTimingNoTimeBody: 'Солнце всё равно даёт полезную тему года. Добавьте время рождения, прежде чем читать дома и асцендент солнечного возвращения.',
    quickHoroscopeLabel: 'Гороскоп по солнечному знаку',
    quickHoroscopeBody: 'Более широкий прогноз на месяц — полезен и без времени рождения.',
    quickHoroscopeAction: 'Прочитать гороскоп для {sign}',
    quickHoroscopeEnglishNote: 'Гороскоп пока доступен по-английски.',
    quickNextBigThree: 'Посмотреть, где это проявляется',
    quickNextSun: 'Найти ключевой рисунок',
    quickNextAspect: 'Посмотреть вперёд',
    quickAspectEmpty: 'Ни один мажорный аспект Солнца, Луны, Меркурия, Венеры или Марса не выделяется. Это настоящий результат, а не пропущенные данные. Дальше посмотрим на время.',
    quickSunHouse: 'При известном времени рождения Солнце также попадает в дом {n}. Дом показывает, в какой области жизни обычно проявляется это положение.',
    quickSunNoHouse: 'Без времени рождения знак Солнца остаётся надёжным. Дома отвечают на вопрос «где», поэтому мы оставляем эту часть открытой, а не угадываем.',
    quickSeeAspect: 'Что значит этот аспект →',
    quickSave: 'Сохранить карту',
    quickToday: 'Небо сегодня',
    'first-big-threeTitle': 'Вы — больше, чем солнечный знак',
    'first-big-threeBody1': 'Карта разделяет то, что вами движет, что вам нужно и как вы выглядите со стороны. Часто именно разница между ними делает чтение личным.',
    'first-sunTitle': 'Где вам естественно сиять',
    'first-sunBody1': 'Солнце описывает то, что помогает вам чувствовать себя собой. Знак задаёт стиль, дом — область жизни, где эта энергия проявляется.',
    'first-aspectTitle': 'Знакомый вам рисунок',
    'first-aspectBody1': 'На этом шаге мы ищем ясный повторяющийся рисунок с участием личных планет. В одних картах он выделяется, в других — нет.',
    'first-nextTitle': 'Что карта говорит о будущем',
    'first-nextBody1': 'Не фиксированный сценарий. Натальная карта описывает повторяющиеся рисунки, а гороскопы и движущееся небо — когда некоторые темы могут стать громче.',

    skyTitle: 'Это ваше небо',
    skyBody1: 'Всё на этом колесе рассчитано для одного момента: неба над местом рождения в час вашего рождения. Ничего не берётся из готовой таблицы — расчёт идёт на вашем устройстве.',
    skyBody2: 'Экскурсия проходит колесо слой за слоем. По пути можно коснуться любого элемента — экскурсия подождёт.',
    zodiacTitle: 'Зодиакальный круг',
    zodiacBody1: 'Внешнее кольцо — зодиак: двенадцать равных отрезков по 30° на годовом пути Солнца. Это неподвижная шкала колеса, по которой читается каждое положение.',
    zodiacBody2: 'Ваше Солнце остаётся подсвеченным: солнечный знак просто называет отрезок, куда попал этот градус.',
    zodiacRotateNote: 'Обычно карту рисуют с асцендентом слева. Сам круг не меняется — меняется лишь точка, с которой мы начинаем читать.',
    horizonTitle: 'Ваш горизонт',
    horizonBody1: 'ASC отмечает градус, восходивший на востоке в минуту рождения; знак в этой точке — ваш асцендент. Напротив находится десцендент, где небо заходило; MC — градус в самой высокой точке.',
    horizonBody2: 'Поэтому минута важна: эта ось сдвигается примерно на градус каждые четыре минуты, и к ней привязано всё колесо.',
    'big-threeTitle': 'Большая тройка',
    'big-threeBody1': 'Солнце, Луна, асцендент — личность, инстинкт, первое впечатление. Сначала читайте их; всё остальное добавляет точности.',
    planetsTitle: 'Планеты',
    planetsBody1: 'Каждый диск — планета в своём точном градусе. Меркурий–Марс движутся быстро и читаются лично; Юпитер и Сатурн задают долгие темы; три внешние планеты отмечают поколения.',
    planetsBody2: 'Коснитесь диска, чтобы увидеть положение, скорость, дом и аспекты. Rx означает ретроградность — обычное видимое движение назад.',
    housesTitle: 'Дома',
    housesBody1: 'Двенадцать секторов — дома: области жизни, где работает планета. Они зависят от времени и места рождения, а не от календаря.',
    housesBody2: 'Два честных способа деления: целые знаки дают каждому дому один знак; Плацидус делит круг по точной геометрии горизонта. Попробуйте другой вариант — планеты не двигаются, меняются только границы.',
    aspectsTitle: 'Разговоры',
    aspectsBody1: 'Линии в центре — аспекты: определённые углы между планетами, каждый со своим типом разговора. Более толстые линии ближе к точности; пунктирные уже расходятся.',
    wholeTitle: 'Вся картина',
    wholeBody1: 'Все слои снова видны. Карта — не список качеств, а одно небо, где всё происходит одновременно. Чтение ниже проходит его строка за строкой.',
    wholeBody2: 'Сохраните карту, и профиль рассчитает её год впереди — по-прежнему на этом устройстве. Ссылка несёт данные внутри себя и не касается сервера.',
    'no-housesTitle': 'Почему в карте нет домов',
    'no-housesBody1': "Дома зависят от времени рождения и вращения неба. Без времени показываем опорные положения; они не устанавливают знак каждой планеты в момент рождения. Асцендент и дома не показываются.",
    'no-housesBody2': 'Если время найдётся — оно часто есть в свидетельстве о рождении — добавьте его выше. У колеса появятся комнаты, а у вас — асцендент.',
  },
} as const satisfies Record<Locale, Record<string, string>>;

export type TourKey = keyof typeof TOUR_COPY.en;

export function tourText(locale: Locale, key: TourKey): string {
  return TOUR_COPY[locale][key];
}

export function tourFormat(
  locale: Locale,
  key: TourKey,
  values: Record<string, string | number>,
): string {
  return tourText(locale, key).replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (token, name: string) => (
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : token
  ));
}
