/**
 * What the shipped artifact is allowed to contain, and whether the archive the
 * site distributes still matches the package it was built from.
 *
 * These are the checks that make the adapter's central claim structural rather
 * than asserted: a model-supplied argument cannot become a command, a path, a
 * module name or a URL, because the code that would carry it out is not in the
 * bundle at all.
 */
import { describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildServerBundle } from './build-mcp-server.mjs';
import { manifestFor } from './pack-mcp-server.mjs';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const BUNDLE = resolve(ROOT, 'examples/mcp-server/server.mjs');
const PUBLIC = resolve(ROOT, 'public/examples');

const bundle = await readFile(BUNDLE, 'utf8');
const manifest = JSON.parse(await readFile(join(PUBLIC, 'mcp-server.json'), 'utf8'));
const archive = await readFile(join(PUBLIC, manifest.file));

describe('the built server bundle', () => {
  it('is what the generator produces from the current source', async () => {
    const { bytes } = await buildServerBundle();
    expect(Buffer.from(bundle).equals(bytes)).toBe(true);
  });

  /**
   * The capability allowlist. A model-supplied argument can become a number, a
   * date or one of a fixed set of option strings. For it to become anything
   * more dangerous, one of these would have to be in the bundle.
   */
  it.each([
    'node:fs', 'node:child_process', 'node:process', 'node:net', 'node:http', 'node:https',
    'node:tls', 'node:dgram', 'node:dns', 'node:vm', 'node:worker_threads', 'node:cluster',
    'node:repl', 'node:module', 'createRequire', 'require(', 'import(',
    'new Function', 'eval(', 'fetch(', 'XMLHttpRequest', 'WebSocket', 'localStorage',
  ])('carries no %s', (marker) => {
    expect(bundle.includes(marker), `${marker} appears in the bundle`).toBe(false);
  });

  it('writes to stdout in exactly one place: handing it to the transport', () => {
    const uses = bundle.split('\n')
      .map((line, index) => ({ line: line.trim(), number: index + 1 }))
      .filter((row) => row.line.includes('process.stdout'));
    expect(uses).toHaveLength(1);
    expect(uses[0].line).toContain('new StdioServerTransport(gate, process.stdout');
  });

  /**
   * Nothing in the bundle may write to stdout through console either. The two
   * `console.trace()` calls that do appear are the vendored ephemeris's own
   * argument validators: trace is stderr-family in Node, takes no arguments
   * here, and is immediately followed by a throw the tool handler catches.
   */
  it('carries no console call that would write to stdout', () => {
    for (const method of ['log', 'info', 'debug', 'dir', 'table', 'group', 'count', 'time']) {
      expect(bundle.includes(`console.${method}`), `console.${method} appears in the bundle`).toBe(false);
    }
    const consoleCalls = [...bundle.matchAll(/console\.(\w+)/g)].map((match) => match[1]);
    expect([...new Set(consoleCalls)]).toEqual(['trace']);
    expect(bundle.includes('console.trace();')).toBe(true);
    expect(bundle.includes('console.trace(')).toBe(true);
    // …and never with an argument, which is what could carry a value.
    expect(/console\.trace\(\s*[^)\s]/.test(bundle)).toBe(false);
  });

  it('imports only the three pinned published packages, plus node:stream', () => {
    // `node:stream` arrived with the line gate that keeps an oversized request
    // from ending the session. It is not in the forbidden family above: a
    // stream transform cannot run a command, open a file or reach a network.
    const specifiers = [...bundle.matchAll(/^import\s.*?from\s+"([^"]+)";$/gm)].map((match) => match[1]);
    expect([...new Set(specifiers)].sort()).toEqual([
      '@modelcontextprotocol/server', '@modelcontextprotocol/server/stdio', 'node:stream', 'zod',
    ]);
  });

  it('records its own provenance in a header a reader can check', () => {
    expect(bundle.startsWith('// Generated by scripts/build-mcp-server.mjs')).toBe(true);
    for (const claim of ['@zodiacs/engine', 'src/lib/compare/', 'esbuild', 'Opens no listener']) {
      expect(bundle.slice(0, 1200)).toContain(claim);
    }
  });
});

describe('the recorded evidence', () => {
  /**
   * The drives refuse to run against a stale bundle, but nothing checked that
   * the record they wrote names the bundle that ships — and an AI review found
   * `protocol-drive.json` pinned to a superseded artifact while the claims
   * README quoted its 70/70 as established for this commit. The guard protected
   * the run; this guards the record.
   */
  const digest = createHash('sha256').update(bundle).digest('hex');
  it.each(['protocol-drive.json', 'benchmark.json', 'host-drive.json'])(
    '%s was measured against the bundle that ships', async (name) => {
      const record = JSON.parse(await readFile(resolve(ROOT, 'docs/platform/evidence/mcp-adapter', name), 'utf8'));
      expect(record.server?.sha256, `${name} names another artifact`).toBe(digest);
    },
  );
});

describe('the archive the site distributes', () => {
  it('matches the digest and size the manifest publishes', () => {
    expect(createHash('sha256').update(archive).digest('hex')).toBe(manifest.sha256);
    expect(archive.length).toBe(manifest.bytes);
  });

  it('is described by a manifest rebuilt from the package itself', async () => {
    const rebuilt = await manifestFor(manifest.file, archive, manifest.artifactCommit);
    expect(rebuilt).toEqual(manifest);
  });

  it('names the archive after the version inside it', () => {
    expect(manifest.file).toBe(`zodiacs-mcp-server-${manifest.version}.tgz`);
    expect(manifest.releaseStatus).toBe('unpublished-candidate');
  });

  it('ships a lockfile whose root version matches the package', async () => {
    // The published install command is `npm ci`, which reads this file. The root
    // version had drifted from rc.1 to rc.4 unnoticed while the command was
    // `npm install`, which does not read it. npm turns out to enforce only
    // dependency agreement, so `npm ci` still succeeded — but an archive that
    // disagrees with itself about its own version is not something to ship, and
    // nothing was watching the field.
    const shrinkwrap = JSON.parse(await readFile(resolve(ROOT, 'examples/mcp-server/npm-shrinkwrap.json'), 'utf8'));
    expect(shrinkwrap.version).toBe(manifest.version);
    expect(shrinkwrap.packages[''].version).toBe(manifest.version);
  });

  it('tells a downloader to extract the archive they actually downloaded', async () => {
    // The README is hand-written and travels inside the archive, so its example
    // commands name a filename. At the rc.2 bump they kept naming rc.1, which a
    // reader would have followed straight into a missing file. Pinned here so a
    // version bump cannot leave them behind again.
    const readme = await readFile(resolve(ROOT, 'examples/mcp-server/README.md'), 'utf8');
    const named = [...readme.matchAll(/zodiacs-mcp-server-([0-9][^.\s]*(?:\.[^.\s]+)*)\.tgz/g)]
      .map((match) => match[1]);
    expect(new Set(named), 'README archive filenames').toEqual(new Set([manifest.version]));
    expect(readme).toContain(`| adapter | \`${manifest.version}\`, unpublished candidate |`);
  });

  it('carries exactly the seven files the package declares, and no more', () => {
    // Read the tar header names directly rather than extracting: the point is
    // to know what is in the archive, not to run it.
    const tar = gunzipSync(archive);
    const names = [];
    for (let offset = 0; offset + 512 <= tar.length; offset += 512) {
      const header = tar.subarray(offset, offset + 512);
      if (header.every((byte) => byte === 0)) break;
      const name = header.subarray(0, 100).toString('ascii').replace(/\0.*$/, '');
      const size = Number.parseInt(header.subarray(124, 136).toString('ascii').replace(/[\0 ]/g, ''), 8);
      names.push(name);
      offset += Math.ceil(size / 512) * 512;
    }
    expect(names.sort()).toEqual([
      'package/NOTICE', 'package/README.md', 'package/candidate.json', 'package/npm-shrinkwrap.json',
      'package/package.json', 'package/server.mjs', 'package/verify.mjs',
    ]);
  });

  it('declares the licence of what it bundles and carries the engine NOTICE', async () => {
    // server.mjs inlines the engine, whose ΔT module holds 32 values of Table
    // S15 under CC BY 4.0: an MIT-only label would drop that attribution.
    const pkg = JSON.parse(await readFile(resolve(ROOT, 'examples/mcp-server/package.json'), 'utf8'));
    expect(pkg.license).toBe('MIT AND CC-BY-4.0');
    expect(pkg.files).toContain('NOTICE');
    const notice = await readFile(resolve(ROOT, 'examples/mcp-server/NOTICE'), 'utf8');
    const engineNotice = await readFile(
      resolve(ROOT, 'node_modules/@zodiacs/engine/NOTICE'), 'utf8');
    expect(notice.endsWith(engineNotice), 'the engine NOTICE, unchanged, at the end').toBe(true);
    expect(notice).toContain('Table S15');
    expect(bundle).toContain('var SY = [');
  });

  it('pins every runtime dependency exactly, and locks the whole tree', async () => {
    const pkg = JSON.parse(await readFile(resolve(ROOT, 'examples/mcp-server/package.json'), 'utf8'));
    for (const [name, range] of Object.entries(pkg.dependencies)) {
      expect(range, `${name} is not pinned exactly`).toMatch(/^\d+\.\d+\.\d+$/);
    }
    const lock = JSON.parse(await readFile(resolve(ROOT, 'examples/mcp-server/npm-shrinkwrap.json'), 'utf8'));
    const runtime = Object.entries(lock.packages)
      .filter(([path, entry]) => path && !entry.dev)
      .map(([path]) => path.replace('node_modules/', ''))
      .sort();
    expect(runtime).toEqual(['@modelcontextprotocol/core', '@modelcontextprotocol/server', 'zod']);
  });

  it('advertises no npm install command for a package that is not published', async () => {
    const readme = await readFile(resolve(ROOT, 'examples/mcp-server/README.md'), 'utf8');
    // Only the fenced blocks are checked: those are the commands a reader
    // copies. The prose says the package is not on npm, which necessarily
    // spells out the command that does not exist.
    const commands = [...readme.matchAll(/```[a-z]*\n([\s\S]*?)```/g)].map((match) => match[1]).join('\n');
    expect(commands).not.toMatch(/npm (?:install|i) +zodiacs-mcp-server/);
    expect(readme).toContain('There is no `npm install zodiacs-mcp-server`');
    const pkg = JSON.parse(await readFile(resolve(ROOT, 'examples/mcp-server/package.json'), 'utf8'));
    expect(pkg.private).toBe(true);
  });

  it('states the privacy distinction in the README a downloader reads first', async () => {
    const readme = await readFile(resolve(ROOT, 'examples/mcp-server/README.md'), 'utf8');
    expect(readme).toMatch(/not the same as a local AI experience/);
    expect(readme).toMatch(/it is not anonymous/);
    // And does not make the claim the mandate rules out for a cloud assistant.
    expect(readme).not.toMatch(/your birth data never leaves your device/i);
  });
});
