// Generated by scripts/build-mcp-remote.mjs. Do not edit.
// Declarations for the bundle beside this file; the source is src/mcp/hosted-http.ts.
export { createHostedMcpHandler } from '../../src/mcp/hosted-http.js';
