import type { CatalogLocale } from '../i18n/core';

export const RETURN_EN = {
  "discovery": "Keep exploring",
  "calendarTitle": "Subscribe to the sky",
  "calendarLede": "New and full moons, eclipse peaks, and planetary retrograde windows in your calendar. These events are the same for everyone.",
  "subscribe": "Subscribe to calendar",
  "downloadCalendar": "Download calendar",
  "calendarUrl": "Calendar subscription URL",
  "calendarHelp": "Open the subscription link in your calendar app, or paste this URL into its “Subscribe from URL” setting. Downloading imports a snapshot; subscribing checks this same URL for updates.",
  "calendarRange": "Includes 2026–2030. We extend this public feed as new years are verified. Times appear in your calendar’s timezone.",
  "calendarPrivacy": "This feed contains public sky events only. No birth details or personal chart positions are included.",
  "newMoon": "New moon",
  "fullMoon": "Full moon",
  "solarEclipse": "Solar eclipse",
  "lunarEclipse": "Lunar eclipse",
  "retrogradeWindow": "{planet} retrograde",
  "calendarEventNote": "Computed astronomical instant. Astrology is a symbolic interpretation; this is not a personal forecast.",
  "eclipseNote": "Global eclipse peak, not a local visibility time. Check local visibility separately.",
  "retrogradeNote": "Apparent retrograde motion. A window clipped at the feed boundary is not a station time.",
  "nextCrossing": "Your next Saturn crossing",
  "countdownDays": "{n} days to the next crossing",
  "countdownToday": "The next crossing is today",
  "countdownOver": "No further crossing in the searched return window.",
  "countdownApprox": "Approximate: without a known birth time these dates use a reference instant.",
  "kitTitle": "Make a client-ready chart PDF",
  "kitLede": "A clean chart, placement and aspect tables, and the calculation receipt. Made on your device, free, with no account needed.",
  "makePdf": "Prepare chart PDF",
  "downloadPdf": "Download chart PDF",
  "pdfNote": "This PDF includes the name and birth details you enter. Review it before sharing with your client. Nothing is uploaded.",
  "pdfTitle": "Birth chart",
  "positions": "Planetary positions",
  "aspects": "Major aspects",
  "houses": "Houses",
  "accuracy": "Check our math",
  "computedInstant": "Computed UTC instant",
  "referenceInstant": "Reference UTC instant — birth time unknown",
  "engine": "Engine",
  "conventions": "Tropical zodiac · Whole sign houses when birth time is known",
  "unknownNote": "Birth time unknown. Rising and houses are omitted; positions and Moon aspects depend on the actual time.",
  "interpretationNote": "Astrology offers symbolic prompts, not a scientific personality test or prediction.",
  "clientName": "Client name or nickname",
  "opening": "Your chart offers a starting point for a conversation about how you move through life.",
  "savedChart": "Use a saved chart",
  "chooseChart": "Choose a chart",
  "noSaved": "No saved charts on this browser yet.",
  "saveChart": "Save a birth chart",
  "wrappedTitle": "Your sky, wrapped",
  "wrappedLede": "See when Jupiter and Saturn touched your Sun, Moon, and rising this year, then make a card to share. Use a saved chart or enter birth details.",
  "enterDetails": "Enter birth details",
  "wrappedSaveHint": "Saving a chart lets you come back to it without typing again.",
  "makeWrapped": "Review this year",
  "wrappedOpening": "Your chart gives you dates to reflect on; you decide what, if anything, they meant to you.",
  "wrappedScope": "We count each exact conjunction, square, and opposition from Jupiter and Saturn to your Sun, Moon, and rising during this UTC calendar year. Retrograde repeat passes count separately. This is a selected transit timeline, not a record of what happened in your life.",
  "wrappedUnknown": "Unknown birth time: only reference Sun contacts are shown, with approximate dates. Moon and rising are left out.",
  "wrappedPreview": "The year is still in progress. Later contacts are labelled upcoming; the card counts scheduled contacts across the full year.",
  "wrappedYear": "{year} · Selected slow transits",
  "year": "Year",
  "contactCount": "{n} scheduled contacts",
  "upcoming": "Upcoming",
  "emptyContacts": "No selected contacts in this year.",
  "wrappedShare": "Share year card",
  "wrappedCardNote": "1080 × 1920 image. No name, birth details, natal degrees, or individual contact dates are included.",
  "generating": "Preparing…",
  "error": "Could not prepare this result. Check your details and try again.",
  "savedRemoved": "This saved chart changed or was removed. Choose it again and recalculate.",
  "dayTitle": "Chart of the day",
  "dayLede": "A sourced public figure’s chart, with a clear account of what is known and what is uncertain.",
  "dayLatest": "Latest chart · {name} · {day}",
  "dayToday": "Today · {name}",
  "dayPending": "No approved chart for this day yet. Explore the sourced people directory while we review the next edition.",
  "daySource": "Birth data source",
  "dayReliability": "Source reliability",
  "dayTimeUnknown": "Birth time unknown. No rising or houses are shown.",
  "dayNews": "Why this person today",
  "dayOpening": "A public chart is a way to explore astrology, not a claim about someone’s private life.",
  "dayError": "The chart could not load. Please try again.",
  "details": "Calculation details",
  "birthDetails": "Birth details",
  "cancel": "Cancel"
} as const;
export type ReturnKey = keyof typeof RETURN_EN;
export type ReturnCopy = Record<ReturnKey, string>;
export const RETURN_COPY = {
  en: RETURN_EN,
es: {
  "discovery": "Sigue explorando",
  "calendarTitle": "Suscríbete al cielo",
  "calendarLede": "Lunas nuevas y llenas, máximos de eclipses y periodos retrógrados en tu calendario. Son los mismos eventos para todos.",
  "subscribe": "Suscribirse al calendario",
  "downloadCalendar": "Descargar calendario",
  "calendarUrl": "URL de suscripción al calendario",
  "calendarHelp": "Abre el enlace en tu aplicación de calendario o pega esta URL en su opción de suscripción por URL. La descarga importa una copia; la suscripción consulta esta misma URL para buscar actualizaciones.",
  "calendarRange": "Incluye 2026–2030. Ampliamos este calendario público al verificar nuevos años. Las horas aparecen en la zona horaria de tu calendario.",
  "calendarPrivacy": "Solo contiene eventos celestes públicos. No incluye datos de nacimiento ni posiciones personales.",
  "newMoon": "Luna nueva",
  "fullMoon": "Luna llena",
  "solarEclipse": "Eclipse solar",
  "lunarEclipse": "Eclipse lunar",
  "retrogradeWindow": "{planet} retrógrado",
  "calendarEventNote": "Instante astronómico calculado. La astrología es una interpretación simbólica; esto no es un pronóstico personal.",
  "eclipseNote": "Máximo global del eclipse, no hora de visibilidad local. Revisa la visibilidad por separado.",
  "retrogradeNote": "Movimiento retrógrado aparente. Un periodo recortado por los límites del calendario no indica una estación.",
  "nextCrossing": "Tu próximo cruce de Saturno",
  "countdownDays": "{n} días hasta el próximo cruce",
  "countdownToday": "El próximo cruce es hoy",
  "countdownOver": "No hay más cruces en el intervalo de retornos examinado.",
  "countdownApprox": "Aproximado: sin una hora de nacimiento conocida, estas fechas usan un instante de referencia.",
  "kitTitle": "Prepara un PDF para tu cliente",
  "kitLede": "Una carta clara, tablas de posiciones y aspectos, y el comprobante del cálculo. En tu dispositivo, gratis y sin cuenta.",
  "makePdf": "Preparar PDF de la carta",
  "downloadPdf": "Descargar PDF de la carta",
  "pdfNote": "El PDF incluye el nombre y los datos de nacimiento que ingreses. Revísalo antes de compartirlo. No se sube nada.",
  "pdfTitle": "Carta natal",
  "positions": "Posiciones planetarias",
  "aspects": "Aspectos principales",
  "houses": "Casas",
  "accuracy": "Revisa nuestros cálculos",
  "computedInstant": "Instante UTC calculado",
  "referenceInstant": "Instante UTC de referencia — hora de nacimiento desconocida",
  "engine": "Motor",
  "conventions": "Zodiaco tropical · Casas de signos completos con hora de nacimiento conocida",
  "unknownNote": "Hora de nacimiento desconocida. Se omiten ascendente y casas; las posiciones y los aspectos lunares dependen de la hora real.",
  "interpretationNote": "La astrología ofrece ideas simbólicas, no una prueba científica de personalidad ni una predicción.",
  "clientName": "Nombre o apodo del cliente",
  "opening": "Tu carta ofrece un punto de partida para conversar sobre cómo te mueves por la vida.",
  "savedChart": "Usar una carta guardada",
  "chooseChart": "Elige una carta",
  "noSaved": "Todavía no hay cartas guardadas en este navegador.",
  "saveChart": "Guardar una carta natal",
  "wrappedTitle": "Tu cielo, en retrospectiva",
  "wrappedLede": "Mira cuándo Júpiter y Saturno tocaron tu Sol, Luna y ascendente este año y crea una tarjeta. Usa una carta guardada o ingresa tus datos de nacimiento.",
  "enterDetails": "Ingresar datos de nacimiento",
  "wrappedSaveHint": "Si guardas una carta, podrás volver sin escribir de nuevo.",
  "makeWrapped": "Revisar este año",
  "wrappedOpening": "Tu carta te da fechas para reflexionar; tú decides qué significaron, si significaron algo.",
  "wrappedScope": "Contamos cada conjunción, cuadratura y oposición exacta de Júpiter y Saturno a tu Sol, Luna y ascendente durante este año UTC. Las pasadas retrógradas repetidas cuentan por separado. Es una selección de tránsitos, no un registro de lo que viviste.",
  "wrappedUnknown": "Hora desconocida: solo se muestran contactos al Sol de referencia, con fechas aproximadas. Se omiten Luna y ascendente.",
  "wrappedPreview": "El año sigue en curso. Los contactos posteriores se indican como próximos; la tarjeta cuenta los programados para todo el año.",
  "wrappedYear": "{year} · Tránsitos lentos seleccionados",
  "year": "Año",
  "contactCount": "{n} contactos programados",
  "upcoming": "Próximo",
  "emptyContacts": "No hay contactos seleccionados este año.",
  "wrappedShare": "Compartir tarjeta del año",
  "wrappedCardNote": "Imagen de 1080 × 1920. Sin nombre, datos de nacimiento, grados ni fechas de contactos individuales.",
  "generating": "Preparando…",
  "error": "No se pudo preparar el resultado. Revisa tus datos e inténtalo de nuevo.",
  "savedRemoved": "Esta carta cambió o se eliminó. Selecciónala de nuevo y vuelve a calcular.",
  "dayTitle": "Carta del día",
  "dayLede": "La carta de una figura pública con fuentes y una explicación clara de lo conocido y lo incierto.",
  "dayLatest": "Carta más reciente · {name} · {day}",
  "dayToday": "Hoy · {name}",
  "dayPending": "Aún no hay carta aprobada para hoy. Explora el directorio con fuentes mientras revisamos la próxima edición.",
  "daySource": "Fuente de los datos de nacimiento",
  "dayReliability": "Confiabilidad de la fuente",
  "dayTimeUnknown": "Hora de nacimiento desconocida. Sin ascendente ni casas.",
  "dayNews": "Por qué esta persona hoy",
  "dayOpening": "Una carta pública permite explorar la astrología, sin afirmar nada sobre la vida privada de alguien.",
  "dayError": "No se pudo cargar la carta. Inténtalo de nuevo.",
  "details": "Detalles del cálculo",
  "birthDetails": "Datos de nacimiento",
  "cancel": "Cancelar"
},
pt: {
  "discovery": "Continue explorando",
  "calendarTitle": "Assine o calendário do céu",
  "calendarLede": "Luas novas e cheias, picos de eclipses e períodos retrógrados no seu calendário. Os eventos são os mesmos para todos.",
  "subscribe": "Assinar calendário",
  "downloadCalendar": "Baixar calendário",
  "calendarUrl": "URL de assinatura do calendário",
  "calendarHelp": "Abra o link no seu aplicativo de calendário ou cole esta URL na opção de assinatura por URL. Baixar importa uma cópia; assinar consulta esta mesma URL para atualizações.",
  "calendarRange": "Inclui 2026–2030. Ampliamos este calendário público à medida que verificamos novos anos. Os horários aparecem no fuso do seu calendário.",
  "calendarPrivacy": "Este calendário contém apenas eventos públicos do céu. Sem dados de nascimento ou posições pessoais.",
  "newMoon": "Lua nova",
  "fullMoon": "Lua cheia",
  "solarEclipse": "Eclipse solar",
  "lunarEclipse": "Eclipse lunar",
  "retrogradeWindow": "{planet} retrógrado",
  "calendarEventNote": "Instante astronômico calculado. A astrologia é uma interpretação simbólica; não é uma previsão pessoal.",
  "eclipseNote": "Pico global do eclipse, não o horário de visibilidade local. Confira a visibilidade separadamente.",
  "retrogradeNote": "Movimento retrógrado aparente. Um período limitado pelas bordas do calendário não indica uma estação.",
  "nextCrossing": "Sua próxima passagem de Saturno",
  "countdownDays": "{n} dias até a próxima passagem",
  "countdownToday": "A próxima passagem é hoje",
  "countdownOver": "Sem outras passagens no intervalo de retornos examinado.",
  "countdownApprox": "Aproximado: sem hora de nascimento conhecida, as datas usam um instante de referência.",
  "kitTitle": "Faça um PDF para seu cliente",
  "kitLede": "Um mapa claro, tabelas de posições e aspectos e o registro do cálculo. No seu dispositivo, grátis e sem conta.",
  "makePdf": "Preparar PDF do mapa",
  "downloadPdf": "Baixar PDF do mapa",
  "pdfNote": "O PDF inclui o nome e os dados de nascimento informados. Revise antes de compartilhar. Nada é enviado.",
  "pdfTitle": "Mapa astral",
  "positions": "Posições planetárias",
  "aspects": "Aspectos principais",
  "houses": "Casas",
  "accuracy": "Confira nossos cálculos",
  "computedInstant": "Instante UTC calculado",
  "referenceInstant": "Instante UTC de referência — hora de nascimento desconhecida",
  "engine": "Motor",
  "conventions": "Zodíaco tropical · Casas de signos inteiros quando a hora de nascimento é conhecida",
  "unknownNote": "Hora de nascimento desconhecida. Ascendente e casas são omitidos; posições e aspectos lunares dependem da hora real.",
  "interpretationNote": "A astrologia oferece reflexões simbólicas, não um teste científico de personalidade ou uma previsão.",
  "clientName": "Nome ou apelido do cliente",
  "opening": "Seu mapa oferece um ponto de partida para conversar sobre como você vive a vida.",
  "savedChart": "Usar um mapa salvo",
  "chooseChart": "Escolha um mapa",
  "noSaved": "Ainda não há mapas salvos neste navegador.",
  "saveChart": "Salvar um mapa astral",
  "wrappedTitle": "Seu céu em retrospectiva",
  "wrappedLede": "Veja quando Júpiter e Saturno tocaram seu Sol, sua Lua e seu ascendente este ano e crie um cartão para compartilhar. Use um mapa salvo ou informe os dados.",
  "enterDetails": "Informar dados de nascimento",
  "wrappedSaveHint": "Salvar um mapa permite voltar sem digitar tudo de novo.",
  "makeWrapped": "Rever este ano",
  "wrappedOpening": "Seu mapa oferece datas para refletir; você decide o que significaram, se significaram algo.",
  "wrappedScope": "Contamos cada conjunção, quadratura e oposição exata de Júpiter e Saturno ao seu Sol, Lua e ascendente neste ano UTC. Passagens retrógradas repetidas contam separadamente. É uma seleção de trânsitos, não um registro do que você viveu.",
  "wrappedUnknown": "Hora de nascimento desconhecida: mostramos apenas contatos ao Sol de referência, com datas aproximadas. Lua e ascendente são omitidos.",
  "wrappedPreview": "O ano ainda está em andamento. Contatos futuros são indicados; o cartão conta os programados para o ano inteiro.",
  "wrappedYear": "{year} · Trânsitos lentos selecionados",
  "year": "Ano",
  "contactCount": "{n} contatos programados",
  "upcoming": "Em breve",
  "emptyContacts": "Sem contatos selecionados neste ano.",
  "wrappedShare": "Compartilhar cartão do ano",
  "wrappedCardNote": "Imagem de 1080 × 1920. Sem nome, dados natais, graus ou datas de contatos individuais.",
  "generating": "Preparando…",
  "error": "Não foi possível preparar o resultado. Confira os dados e tente novamente.",
  "savedRemoved": "Este mapa mudou ou foi removido. Selecione novamente e recalcule.",
  "dayTitle": "Mapa do dia",
  "dayLede": "O mapa de uma figura pública com fontes e uma explicação clara do que é conhecido e incerto.",
  "dayLatest": "Mapa mais recente · {name} · {day}",
  "dayToday": "Hoje · {name}",
  "dayPending": "Nenhum mapa aprovado para hoje. Explore o diretório com fontes enquanto revisamos a próxima edição.",
  "daySource": "Fonte dos dados natais",
  "dayReliability": "Confiabilidade da fonte",
  "dayTimeUnknown": "Hora de nascimento desconhecida. Sem ascendente nem casas.",
  "dayNews": "Por que esta pessoa hoje",
  "dayOpening": "Um mapa público permite explorar astrologia, sem afirmar nada sobre a vida privada de alguém.",
  "dayError": "Não foi possível carregar o mapa. Tente novamente.",
  "details": "Detalhes do cálculo",
  "birthDetails": "Dados de nascimento",
  "cancel": "Cancelar"
},
fr: {
  "discovery": "Continue à explorer",
  "calendarTitle": "Abonne-toi au ciel",
  "calendarLede": "Nouvelles et pleines lunes, maxima des éclipses et périodes rétrogrades dans ton calendrier. Ces événements sont les mêmes pour tous.",
  "subscribe": "S’abonner au calendrier",
  "downloadCalendar": "Télécharger le calendrier",
  "calendarUrl": "URL d’abonnement au calendrier",
  "calendarHelp": "Ouvre le lien dans ton application de calendrier ou colle cette URL dans son réglage « S’abonner à partir d’une URL ». Le téléchargement importe une copie ; l’abonnement consulte cette même URL pour les mises à jour.",
  "calendarRange": "Inclut 2026–2030. Nous étendons ce calendrier public à mesure que de nouvelles années sont vérifiées. Les heures suivent le fuseau de ton calendrier.",
  "calendarPrivacy": "Ce calendrier contient uniquement des événements célestes publics. Aucune donnée de naissance ni position personnelle.",
  "newMoon": "Nouvelle Lune",
  "fullMoon": "Pleine Lune",
  "solarEclipse": "Éclipse solaire",
  "lunarEclipse": "Éclipse lunaire",
  "retrogradeWindow": "{planet} rétrograde",
  "calendarEventNote": "Instant astronomique calculé. L’astrologie est une interprétation symbolique ; ce n’est pas une prévision personnelle.",
  "eclipseNote": "Maximum mondial de l’éclipse, pas une heure de visibilité locale. Vérifie la visibilité séparément.",
  "retrogradeNote": "Mouvement rétrograde apparent. Une période limitée par les bornes du calendrier n’indique pas une station.",
  "nextCrossing": "Ton prochain passage de Saturne",
  "countdownDays": "{n} jours avant le prochain passage",
  "countdownToday": "Le prochain passage est aujourd’hui",
  "countdownOver": "Aucun autre passage dans la fenêtre de retour examinée.",
  "countdownApprox": "Approximatif : sans heure de naissance connue, ces dates utilisent un instant de référence.",
  "kitTitle": "Crée un PDF de thème pour ton client",
  "kitLede": "Un thème clair, des tableaux de positions et d’aspects, et le relevé du calcul. Sur ton appareil, gratuitement et sans compte.",
  "makePdf": "Préparer le PDF du thème",
  "downloadPdf": "Télécharger le PDF du thème",
  "pdfNote": "Ce PDF contient le nom et les données de naissance saisis. Relis-le avant de le partager. Rien n’est envoyé.",
  "pdfTitle": "Thème astral",
  "positions": "Positions planétaires",
  "aspects": "Aspects majeurs",
  "houses": "Maisons",
  "accuracy": "Vérifie nos calculs",
  "computedInstant": "Instant UTC calculé",
  "referenceInstant": "Instant UTC de référence — heure inconnue",
  "engine": "Moteur",
  "conventions": "Zodiaque tropical · Maisons en signes entiers si l’heure est connue",
  "unknownNote": "Heure de naissance inconnue. Ascendant et maisons omis ; les positions et aspects lunaires dépendent de l’heure réelle.",
  "interpretationNote": "L’astrologie propose des pistes symboliques, pas un test scientifique de personnalité ni une prédiction.",
  "clientName": "Nom ou surnom du client",
  "opening": "Ton thème est un point de départ pour parler de la façon dont tu traverses la vie.",
  "savedChart": "Utiliser un thème enregistré",
  "chooseChart": "Choisis un thème",
  "noSaved": "Aucun thème enregistré dans ce navigateur pour le moment.",
  "saveChart": "Enregistrer un thème astral",
  "wrappedTitle": "Ton ciel, en rétrospective",
  "wrappedLede": "Vois quand Jupiter et Saturne ont touché ton Soleil, ta Lune et ton ascendant cette année, puis crée une carte à partager. Utilise un thème enregistré ou saisis tes données de naissance.",
  "enterDetails": "Saisir des données de naissance",
  "wrappedSaveHint": "Enregistrer un thème te permet d’y revenir sans tout ressaisir.",
  "makeWrapped": "Revoir cette année",
  "wrappedOpening": "Ton thème te donne des dates pour réfléchir ; tu décides de leur sens éventuel.",
  "wrappedScope": "Nous comptons chaque conjonction, carré et opposition exacte de Jupiter et Saturne à ton Soleil, ta Lune et ton ascendant pendant cette année UTC. Les passages rétrogrades répétés comptent séparément. C’est une sélection de transits, pas un récit de ta vie.",
  "wrappedUnknown": "Heure inconnue : seuls les contacts au Soleil de référence sont montrés, avec des dates approximatives. Lune et ascendant omis.",
  "wrappedPreview": "L’année continue. Les contacts ultérieurs sont signalés à venir ; la carte compte ceux prévus sur l’année entière.",
  "wrappedYear": "{year} · Transits lents sélectionnés",
  "year": "Année",
  "contactCount": "{n} contacts prévus",
  "upcoming": "À venir",
  "emptyContacts": "Aucun contact sélectionné cette année.",
  "wrappedShare": "Partager la carte de l’année",
  "wrappedCardNote": "Image de 1080 × 1920. Sans nom, données de naissance, degrés ni dates de contacts individuels.",
  "generating": "Préparation…",
  "error": "Impossible de préparer le résultat. Vérifie tes données et réessaie.",
  "savedRemoved": "Ce thème a changé ou a été supprimé. Sélectionne-le à nouveau et recalcule.",
  "dayTitle": "Thème du jour",
  "dayLede": "Le thème d’une personnalité publique, avec des sources et une explication claire de ce qui est connu ou incertain.",
  "dayLatest": "Dernier thème · {name} · {day}",
  "dayToday": "Aujourd’hui · {name}",
  "dayPending": "Aucun thème approuvé pour aujourd’hui. Explore le répertoire des personnes documentées pendant que nous préparons la prochaine édition.",
  "daySource": "Source des données de naissance",
  "dayReliability": "Fiabilité de la source",
  "dayTimeUnknown": "Heure de naissance inconnue. Ni ascendant ni maisons.",
  "dayNews": "Pourquoi cette personne aujourd’hui",
  "dayOpening": "Un thème public permet d’explorer l’astrologie, sans rien affirmer sur la vie privée de quelqu’un.",
  "dayError": "Le thème n’a pas pu être chargé. Réessaie.",
  "details": "Détails du calcul",
  "birthDetails": "Données de naissance",
  "cancel": "Annuler"
},
it: {
  "discovery": "Continua a esplorare",
  "calendarTitle": "Iscriviti al cielo",
  "calendarLede": "Lune nuove e piene, massimi delle eclissi e periodi retrogradi nel tuo calendario. Gli eventi sono gli stessi per tutti.",
  "subscribe": "Iscriviti al calendario",
  "downloadCalendar": "Scarica calendario",
  "calendarUrl": "URL di iscrizione al calendario",
  "calendarHelp": "Apri il link nell’app calendario o incolla questo URL nell’opzione di iscrizione tramite URL. Il download importa una copia; l’iscrizione consulta questo stesso URL per gli aggiornamenti.",
  "calendarRange": "Include il 2026–2030. Estendiamo questo calendario pubblico quando verifichiamo nuovi anni. Gli orari seguono il fuso del tuo calendario.",
  "calendarPrivacy": "Solo eventi celesti pubblici. Nessun dato di nascita o posizione personale.",
  "newMoon": "Luna nuova",
  "fullMoon": "Luna piena",
  "solarEclipse": "Eclissi solare",
  "lunarEclipse": "Eclissi lunare",
  "retrogradeWindow": "{planet} retrogrado",
  "calendarEventNote": "Istante astronomico calcolato. L’astrologia è un’interpretazione simbolica, non una previsione personale.",
  "eclipseNote": "Massimo globale dell’eclissi, non orario di visibilità locale. Controlla la visibilità separatamente.",
  "retrogradeNote": "Moto retrogrado apparente. Un periodo limitato dai confini del calendario non indica una stazione.",
  "nextCrossing": "Il tuo prossimo passaggio di Saturno",
  "countdownDays": "{n} giorni al prossimo passaggio",
  "countdownToday": "Il prossimo passaggio è oggi",
  "countdownOver": "Nessun altro passaggio nell’intervallo dei ritorni esaminato.",
  "countdownApprox": "Approssimativo: senza un’ora di nascita nota, queste date usano un istante di riferimento.",
  "kitTitle": "Crea un PDF del tema per il tuo cliente",
  "kitLede": "Un tema chiaro, tabelle di posizioni e aspetti e il resoconto del calcolo. Sul tuo dispositivo, gratis e senza account.",
  "makePdf": "Prepara PDF del tema",
  "downloadPdf": "Scarica PDF del tema",
  "pdfNote": "Il PDF include nome e dati di nascita inseriti. Controllalo prima di condividerlo. Nulla viene caricato.",
  "pdfTitle": "Tema natale",
  "positions": "Posizioni planetarie",
  "aspects": "Aspetti principali",
  "houses": "Case",
  "accuracy": "Controlla i nostri calcoli",
  "computedInstant": "Istante UTC calcolato",
  "referenceInstant": "Istante UTC di riferimento — ora sconosciuta",
  "engine": "Motore",
  "conventions": "Zodiaco tropicale · Case a segno intero con ora di nascita nota",
  "unknownNote": "Ora di nascita sconosciuta. Ascendente e case omessi; posizioni e aspetti lunari dipendono dall’ora reale.",
  "interpretationNote": "L’astrologia offre spunti simbolici, non un test scientifico della personalità o una previsione.",
  "clientName": "Nome o soprannome del cliente",
  "opening": "Il tuo tema offre un punto di partenza per parlare del tuo modo di vivere.",
  "savedChart": "Usa un tema salvato",
  "chooseChart": "Scegli un tema",
  "noSaved": "Non ci sono ancora temi salvati in questo browser.",
  "saveChart": "Salva un tema natale",
  "wrappedTitle": "Il tuo cielo, in retrospettiva",
  "wrappedLede": "Scopri quando Giove e Saturno hanno toccato il tuo Sole, la tua Luna e l’ascendente quest’anno, poi crea un’immagine da condividere. Usa un tema salvato o inserisci i dati di nascita.",
  "enterDetails": "Inserisci i dati di nascita",
  "wrappedSaveHint": "Salvare un tema ti permette di tornarci senza riscrivere tutto.",
  "makeWrapped": "Rivedi quest’anno",
  "wrappedOpening": "Il tema ti offre date su cui riflettere; decidi tu cosa hanno significato, se hanno significato qualcosa.",
  "wrappedScope": "Contiamo ogni congiunzione, quadratura e opposizione esatta di Giove e Saturno al tuo Sole, Luna e ascendente in questo anno UTC. I passaggi retrogradi ripetuti contano separatamente. È una selezione di transiti, non un resoconto della tua vita.",
  "wrappedUnknown": "Ora sconosciuta: mostriamo solo contatti al Sole di riferimento, con date approssimative. Luna e ascendente omessi.",
  "wrappedPreview": "L’anno è ancora in corso. I contatti successivi sono indicati come futuri; l’immagine conta quelli previsti per tutto l’anno.",
  "wrappedYear": "{year} · Transiti lenti selezionati",
  "year": "Anno",
  "contactCount": "{n} contatti previsti",
  "upcoming": "In arrivo",
  "emptyContacts": "Nessun contatto selezionato quest’anno.",
  "wrappedShare": "Condividi immagine dell’anno",
  "wrappedCardNote": "Immagine di 1080 × 1920. Senza nome, dati di nascita, gradi o date dei singoli contatti.",
  "generating": "Preparazione…",
  "error": "Impossibile preparare il risultato. Controlla i dati e riprova.",
  "savedRemoved": "Questo tema è cambiato o è stato rimosso. Selezionalo di nuovo e ricalcola.",
  "dayTitle": "Tema del giorno",
  "dayLede": "Il tema di una figura pubblica con fonti e una spiegazione chiara di ciò che è noto e incerto.",
  "dayLatest": "Tema più recente · {name} · {day}",
  "dayToday": "Oggi · {name}",
  "dayPending": "Nessun tema approvato per oggi. Esplora il repertorio con fonti mentre rivediamo la prossima edizione.",
  "daySource": "Fonte dei dati di nascita",
  "dayReliability": "Affidabilità della fonte",
  "dayTimeUnknown": "Ora di nascita sconosciuta. Senza ascendente né case.",
  "dayNews": "Perché questa persona oggi",
  "dayOpening": "Un tema pubblico permette di esplorare l’astrologia, senza affermare nulla sulla vita privata di qualcuno.",
  "dayError": "Impossibile caricare il tema. Riprova.",
  "details": "Dettagli del calcolo",
  "birthDetails": "Dati di nascita",
  "cancel": "Annulla"
},
ru: {
  "discovery": "Что ещё посмотреть",
  "calendarTitle": "Подпишитесь на небесный календарь",
  "calendarLede": "Новолуния, полнолуния, максимумы затмений и периоды ретроградности в вашем календаре. Эти события одинаковы для всех.",
  "subscribe": "Подписаться на календарь",
  "downloadCalendar": "Скачать календарь",
  "calendarUrl": "URL подписки на календарь",
  "calendarHelp": "Откройте ссылку в приложении календаря или вставьте URL в настройку подписки по ссылке. Скачивание импортирует копию; подписка проверяет обновления по этому же URL.",
  "calendarRange": "Включает 2026–2030 годы. Мы расширяем календарь после проверки новых лет. Время отображается в часовом поясе вашего календаря.",
  "calendarPrivacy": "Только общедоступные небесные события. Без данных рождения и личных положений планет.",
  "newMoon": "Новолуние",
  "fullMoon": "Полнолуние",
  "solarEclipse": "Солнечное затмение",
  "lunarEclipse": "Лунное затмение",
  "retrogradeWindow": "Ретроградность: {planet}",
  "calendarEventNote": "Рассчитанный астрономический момент. Астрология — символическая интерпретация, а не личный прогноз.",
  "eclipseNote": "Глобальный максимум затмения, а не время местной видимости. Проверяйте видимость отдельно.",
  "retrogradeNote": "Видимое ретроградное движение. Период, обрезанный границами календаря, не обозначает момент стоянки.",
  "nextCrossing": "Следующий проход Сатурна по натальному градусу",
  "countdownDays": "До следующего прохода: {n} дн.",
  "countdownToday": "Следующий проход — сегодня",
  "countdownOver": "В исследованном интервале больше нет проходов.",
  "countdownApprox": "Приблизительно: без известного времени рождения даты рассчитаны для опорного момента.",
  "kitTitle": "Создайте PDF карты для клиента",
  "kitLede": "Чёткая карта, таблицы положений и аспектов и сведения о расчёте. На вашем устройстве, бесплатно и без аккаунта.",
  "makePdf": "Подготовить PDF карты",
  "downloadPdf": "Скачать PDF карты",
  "pdfNote": "PDF содержит введённые имя и данные рождения. Проверьте его перед отправкой клиенту. Ничего не загружается на сервер.",
  "pdfTitle": "Натальная карта",
  "positions": "Положения планет",
  "aspects": "Основные аспекты",
  "houses": "Дома",
  "accuracy": "Проверьте наши расчёты",
  "computedInstant": "Рассчитанный момент UTC",
  "referenceInstant": "Опорный момент UTC — время рождения неизвестно",
  "engine": "Движок",
  "conventions": "Тропический зодиак · Дома целых знаков при известном времени рождения",
  "unknownNote": "Время рождения неизвестно. Асцендент и дома исключены; положения и лунные аспекты зависят от реального времени.",
  "interpretationNote": "Астрология предлагает символические темы для размышления, а не научный тест личности или предсказание.",
  "clientName": "Имя или псевдоним клиента",
  "opening": "Ваша карта может стать отправной точкой для разговора о том, как вы живёте.",
  "savedChart": "Использовать сохранённую карту",
  "chooseChart": "Выберите карту",
  "noSaved": "В этом браузере пока нет сохранённых карт.",
  "saveChart": "Сохранить натальную карту",
  "wrappedTitle": "Ваше небо: итоги года",
  "wrappedLede": "Узнайте, когда в этом году Юпитер и Сатурн касались вашего Солнца, Луны и асцендента, и создайте карточку, чтобы поделиться. Используйте сохранённую карту или введите данные рождения.",
  "enterDetails": "Ввести данные рождения",
  "wrappedSaveHint": "Сохранённую карту можно открыть снова без повторного ввода.",
  "makeWrapped": "Посмотреть этот год",
  "wrappedOpening": "Карта даёт даты для размышления; вы решаете, имели ли они для вас значение.",
  "wrappedScope": "Считаем каждое точное соединение, квадратуру и оппозицию Юпитера и Сатурна к вашему Солнцу, Луне и асценденту за календарный год UTC. Повторные ретроградные проходы считаются отдельно. Это избранные транзиты, а не запись событий вашей жизни.",
  "wrappedUnknown": "Время неизвестно: только контакты к опорному Солнцу с приблизительными датами. Луна и асцендент исключены.",
  "wrappedPreview": "Год ещё продолжается. Поздние контакты отмечены как предстоящие; карточка считает запланированные контакты за весь год.",
  "wrappedYear": "{year} · Избранные медленные транзиты",
  "year": "Год",
  "contactCount": "Запланировано контактов: {n}",
  "upcoming": "Предстоит",
  "emptyContacts": "В этом году нет выбранных контактов.",
  "wrappedShare": "Поделиться итогами года",
  "wrappedCardNote": "Изображение 1080 × 1920. Без имени, данных рождения, натальных градусов и дат отдельных контактов.",
  "generating": "Подготовка…",
  "error": "Не удалось подготовить результат. Проверьте данные и попробуйте снова.",
  "savedRemoved": "Карта изменилась или удалена. Выберите её заново и пересчитайте.",
  "dayTitle": "Карта дня",
  "dayLede": "Карта публичной личности с источниками и ясным объяснением известных и неопределённых данных.",
  "dayLatest": "Последняя карта · {name} · {day}",
  "dayToday": "Сегодня · {name}",
  "dayPending": "Сегодня пока нет одобренной карты. Изучите каталог с источниками, пока мы проверяем следующий выпуск.",
  "daySource": "Источник данных рождения",
  "dayReliability": "Надёжность источника",
  "dayTimeUnknown": "Время рождения неизвестно. Асцендент и дома не показаны.",
  "dayNews": "Почему именно сегодня",
  "dayOpening": "Публичная карта помогает изучать астрологию, не утверждая ничего о частной жизни человека.",
  "dayError": "Не удалось загрузить карту. Попробуйте снова.",
  "details": "Сведения о расчёте",
  "birthDetails": "Данные рождения",
  "cancel": "Отмена"
},
} satisfies Record<CatalogLocale, ReturnCopy>;
export function returnText(locale: CatalogLocale, key: ReturnKey, values: Record<string, string | number> = {}): string {
  return RETURN_COPY[locale][key].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token);
}
